export const austrianUniversities = [
  {
    name: 'University of Vienna',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sciences', 'Social Sciences & Humanities', 'Law & Politics', 'Business & Economics', 'Medicine & Health'],
    admissionPeriod: 'February - September',
    website: 'https://www.univie.ac.at',
    description: 'Founded in 1365, the University of Vienna is one of the oldest and largest universities in the German-speaking world. A leading research university with 21 Nobel laureates.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 90000,
    globalRank: 137,
  },
  {
    name: 'TU Wien (Vienna University of Technology)',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering & Technology', 'Sciences', 'Architecture'],
    admissionPeriod: 'February - September',
    website: 'https://www.tuwien.at',
    description: 'Austria\'s largest research and educational institution in the fields of technology and natural sciences. Known for engineering, computer science, and architecture.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 28000,
    globalRank: 191,
  },
  {
    name: 'University of Innsbruck',
    country: 'Austria',
    region: 'Tyrol',
    city: 'Innsbruck',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sciences', 'Social Sciences & Humanities', 'Law & Politics', 'Engineering & Technology', 'Medicine & Health'],
    admissionPeriod: 'February - September',
    website: 'https://www.uibk.ac.at',
    description: 'A comprehensive university in the heart of the Alps. Known for physics, quantum computing, and alpine research. Beautiful mountain campus setting.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 28000,
    globalRank: 266,
  },
  {
    name: 'University of Graz',
    country: 'Austria',
    region: 'Styria',
    city: 'Graz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sciences', 'Social Sciences & Humanities', 'Law & Politics', 'Business & Economics'],
    admissionPeriod: 'February - September',
    website: 'https://www.uni-graz.at',
    description: 'Austria\'s second-oldest university, founded in 1585. Strong in humanities, natural sciences, and law. Part of the UNESCO World Heritage city.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 32000,
    globalRank: 351,
  },
  {
    name: 'Medical University of Vienna',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine & Health'],
    admissionPeriod: 'February - July',
    website: 'https://www.meduniwien.ac.at',
    description: 'One of the most prestigious medical schools in Europe. The largest medical university in the German-speaking world with cutting-edge research facilities.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 8000,
    globalRank: 45,
  },
  {
    name: 'Medical University of Graz',
    country: 'Austria',
    region: 'Styria',
    city: 'Graz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine & Health'],
    admissionPeriod: 'February - July',
    website: 'https://www.medunigraz.at',
    description: 'Leading medical university known for biomedical research, regenerative medicine, and sustainable health research.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 4500,
    globalRank: 251,
  },
  {
    name: 'Medical University of Innsbruck',
    country: 'Austria',
    region: 'Tyrol',
    city: 'Innsbruck',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine & Health'],
    admissionPeriod: 'February - July',
    website: 'https://www.i-med.ac.at',
    description: 'Known for excellence in medical research, particularly in transplantation medicine, genetics, and neuroscience.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 3500,
    globalRank: 201,
  },
  {
    name: 'TU Graz (Graz University of Technology)',
    country: 'Austria',
    region: 'Styria',
    city: 'Graz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering & Technology', 'Sciences', 'Architecture'],
    admissionPeriod: 'February - September',
    website: 'https://www.tugraz.at',
    description: 'One of Austria\'s leading technical universities. Strong in automotive engineering, biomedical engineering, and sustainable technologies.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 17000,
    globalRank: 301,
  },
  {
    name: 'Johannes Kepler University Linz',
    country: 'Austria',
    region: 'Upper Austria',
    city: 'Linz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sciences', 'Engineering & Technology', 'Business & Economics', 'Law & Politics', 'Social Sciences & Humanities'],
    admissionPeriod: 'February - September',
    website: 'https://www.jku.at',
    description: 'Modern university known for mechatronics, AI, and law. Austria\'s first AI bachelor\'s program. Strong industry connections.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 23000,
    globalRank: 401,
  },
  {
    name: 'University of Salzburg',
    country: 'Austria',
    region: 'Salzburg',
    city: 'Salzburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sciences', 'Social Sciences & Humanities', 'Law & Politics', 'Business & Economics'],
    admissionPeriod: 'February - September',
    website: 'https://www.plus.ac.at',
    description: 'Located in Mozart\'s birthplace. Strong in cognitive science, legal studies, and cultural heritage. Beautiful baroque city setting.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 18000,
    globalRank: 401,
  },
  {
    name: 'WU Vienna (Vienna University of Economics and Business)',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business & Economics', 'Law & Politics'],
    admissionPeriod: 'February - September',
    website: 'https://www.wu.ac.at',
    description: 'One of Europe\'s largest business universities. Triple-accredited (AMBA, EQUIS, AACSB). Award-winning campus by Zaha Hadid Architects.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 23000,
    globalRank: null,
  },
  {
    name: 'University of Natural Resources and Life Sciences Vienna (BOKU)',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Agriculture & Environment', 'Sciences', 'Engineering & Technology'],
    admissionPeriod: 'February - September',
    website: 'https://www.boku.ac.at',
    description: 'Leading university for life sciences, natural resources, and environmental sciences. Focus on sustainability and biotechnology.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 13000,
    globalRank: 201,
  },
  {
    name: 'University of Veterinary Medicine Vienna',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine & Health', 'Sciences'],
    admissionPeriod: 'February - July',
    website: 'https://www.vetmeduni.ac.at',
    description: 'The only veterinary university in Austria and one of the oldest in the German-speaking world. Known for comparative medicine research.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 2500,
    globalRank: 51,
  },
  {
    name: 'Montanuniversität Leoben',
    country: 'Austria',
    region: 'Styria',
    city: 'Leoben',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering & Technology', 'Sciences'],
    admissionPeriod: 'February - September',
    website: 'https://www.unileoben.ac.at',
    description: 'Specialized university for mining, metallurgy, and materials science. Strong industry connections with high graduate employment.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 4000,
    globalRank: 501,
  },
  {
    name: 'University of Klagenfurt',
    country: 'Austria',
    region: 'Carinthia',
    city: 'Klagenfurt',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sciences', 'Social Sciences & Humanities', 'Engineering & Technology', 'Business & Economics'],
    admissionPeriod: 'February - September',
    website: 'https://www.aau.at',
    description: 'Modern university with focus on interdisciplinary studies, sustainability, and digital transformation. Lakeside campus setting.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 12000,
    globalRank: 601,
  },
  {
    name: 'University of Art and Design Linz',
    country: 'Austria',
    region: 'Upper Austria',
    city: 'Linz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Arts & Design', 'Media & Communication'],
    admissionPeriod: 'January - March',
    website: 'https://www.kunstuni-linz.at',
    description: 'Leading art university known for media art, interface cultures, and fashion/textile design. UNESCO City of Media Arts.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 1500,
    globalRank: null,
  },
  {
    name: 'Academy of Fine Arts Vienna',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Arts & Design', 'Architecture'],
    admissionPeriod: 'January - March',
    website: 'https://www.akbild.ac.at',
    description: 'One of the world\'s oldest art academies, founded in 1692. Known for contemporary art, architecture, and art theory.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 1500,
    globalRank: null,
  },
  {
    name: 'University of Applied Arts Vienna',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Arts & Design', 'Architecture', 'Media & Communication'],
    admissionPeriod: 'January - March',
    website: 'https://www.dieangewandte.at',
    description: 'Elite art and design university. Known for architecture, design, and digital arts. Produces world-renowned artists and designers.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 2000,
    globalRank: null,
  },
  {
    name: 'Mozarteum University Salzburg',
    country: 'Austria',
    region: 'Salzburg',
    city: 'Salzburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Arts & Design', 'Social Sciences & Humanities'],
    admissionPeriod: 'January - March',
    website: 'https://www.moz.ac.at',
    description: 'World-renowned conservatory for music and performing arts. Named after Mozart, located in his birthplace.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 2000,
    globalRank: null,
  },
  {
    name: 'University of Music and Performing Arts Vienna (MDW)',
    country: 'Austria',
    region: 'Vienna',
    city: 'Vienna',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Arts & Design', 'Social Sciences & Humanities'],
    admissionPeriod: 'January - March',
    website: 'https://www.mdw.ac.at',
    description: 'One of the world\'s largest and most prestigious music universities. Known for classical music, conducting, and film direction.',
    englishPrograms: true,
    tuitionFeeEu: '€363.36/semester',
    tuitionFeeNonEu: '€726.72/semester',
    tuitionPeriod: 'per semester',
    totalEnrollment: 3000,
    globalRank: null,
  },
];
