import type { InsertCostOfLiving } from "@shared/schema";

export const costOfLivingData: InsertCostOfLiving[] = [
  // Spain - Major Cities
  {
    country: 'Spain',
    city: 'Madrid',
    rentShared: 450,
    rentSolo: 850,
    utilities: 80,
    groceries: 200,
    dining: 150,
    transport: 55,
    healthcare: 50,
    entertainment: 100,
  },
  {
    country: 'Spain',
    city: 'Barcelona',
    rentShared: 500,
    rentSolo: 950,
    utilities: 85,
    groceries: 210,
    dining: 160,
    transport: 55,
    healthcare: 50,
    entertainment: 120,
  },
  {
    country: 'Spain',
    city: 'Valencia',
    rentShared: 350,
    rentSolo: 650,
    utilities: 70,
    groceries: 180,
    dining: 120,
    transport: 45,
    healthcare: 45,
    entertainment: 80,
  },
  {
    country: 'Spain',
    city: 'Seville',
    rentShared: 320,
    rentSolo: 580,
    utilities: 65,
    groceries: 170,
    dining: 110,
    transport: 40,
    healthcare: 45,
    entertainment: 75,
  },
  {
    country: 'Spain',
    city: 'Bilbao',
    rentShared: 380,
    rentSolo: 700,
    utilities: 75,
    groceries: 190,
    dining: 130,
    transport: 50,
    healthcare: 50,
    entertainment: 90,
  },
  {
    country: 'Spain',
    city: 'Málaga',
    rentShared: 350,
    rentSolo: 620,
    utilities: 65,
    groceries: 175,
    dining: 115,
    transport: 40,
    healthcare: 45,
    entertainment: 80,
  },
  {
    country: 'Spain',
    city: 'Granada',
    rentShared: 280,
    rentSolo: 480,
    utilities: 55,
    groceries: 160,
    dining: 100,
    transport: 35,
    healthcare: 40,
    entertainment: 65,
  },
  {
    country: 'Spain',
    city: 'Salamanca',
    rentShared: 260,
    rentSolo: 450,
    utilities: 55,
    groceries: 155,
    dining: 95,
    transport: 30,
    healthcare: 40,
    entertainment: 60,
  },
  {
    country: 'Spain',
    city: 'Zaragoza',
    rentShared: 300,
    rentSolo: 520,
    utilities: 60,
    groceries: 165,
    dining: 105,
    transport: 38,
    healthcare: 45,
    entertainment: 70,
  },
  {
    country: 'Spain',
    city: 'Santiago de Compostela',
    rentShared: 270,
    rentSolo: 480,
    utilities: 60,
    groceries: 160,
    dining: 100,
    transport: 35,
    healthcare: 42,
    entertainment: 65,
  },

  // Germany - Major Cities
  {
    country: 'Germany',
    city: 'Munich',
    rentShared: 650,
    rentSolo: 1200,
    utilities: 120,
    groceries: 250,
    dining: 180,
    transport: 65,
    healthcare: 110,
    entertainment: 120,
  },
  {
    country: 'Germany',
    city: 'Berlin',
    rentShared: 500,
    rentSolo: 900,
    utilities: 100,
    groceries: 220,
    dining: 150,
    transport: 86,
    healthcare: 110,
    entertainment: 100,
  },
  {
    country: 'Germany',
    city: 'Hamburg',
    rentShared: 520,
    rentSolo: 950,
    utilities: 105,
    groceries: 230,
    dining: 155,
    transport: 80,
    healthcare: 110,
    entertainment: 105,
  },
  {
    country: 'Germany',
    city: 'Frankfurt',
    rentShared: 580,
    rentSolo: 1050,
    utilities: 110,
    groceries: 240,
    dining: 165,
    transport: 75,
    healthcare: 110,
    entertainment: 110,
  },
  {
    country: 'Germany',
    city: 'Cologne',
    rentShared: 480,
    rentSolo: 850,
    utilities: 95,
    groceries: 210,
    dining: 140,
    transport: 70,
    healthcare: 110,
    entertainment: 95,
  },
  {
    country: 'Germany',
    city: 'Stuttgart',
    rentShared: 550,
    rentSolo: 1000,
    utilities: 105,
    groceries: 235,
    dining: 160,
    transport: 75,
    healthcare: 110,
    entertainment: 100,
  },
  {
    country: 'Germany',
    city: 'Düsseldorf',
    rentShared: 500,
    rentSolo: 900,
    utilities: 100,
    groceries: 225,
    dining: 150,
    transport: 72,
    healthcare: 110,
    entertainment: 100,
  },
  {
    country: 'Germany',
    city: 'Leipzig',
    rentShared: 350,
    rentSolo: 600,
    utilities: 85,
    groceries: 190,
    dining: 120,
    transport: 65,
    healthcare: 110,
    entertainment: 80,
  },
  {
    country: 'Germany',
    city: 'Dresden',
    rentShared: 340,
    rentSolo: 580,
    utilities: 80,
    groceries: 185,
    dining: 115,
    transport: 62,
    healthcare: 110,
    entertainment: 75,
  },
  {
    country: 'Germany',
    city: 'Heidelberg',
    rentShared: 480,
    rentSolo: 850,
    utilities: 95,
    groceries: 215,
    dining: 145,
    transport: 68,
    healthcare: 110,
    entertainment: 90,
  },
  {
    country: 'Germany',
    city: 'Freiburg',
    rentShared: 450,
    rentSolo: 800,
    utilities: 90,
    groceries: 210,
    dining: 140,
    transport: 65,
    healthcare: 110,
    entertainment: 85,
  },
  {
    country: 'Germany',
    city: 'Bonn',
    rentShared: 420,
    rentSolo: 750,
    utilities: 90,
    groceries: 200,
    dining: 135,
    transport: 68,
    healthcare: 110,
    entertainment: 85,
  },

  // Hungary - Major Cities
  {
    country: 'Hungary',
    city: 'Budapest',
    rentShared: 280,
    rentSolo: 550,
    utilities: 70,
    groceries: 150,
    dining: 100,
    transport: 35,
    healthcare: 30,
    entertainment: 60,
  },
  {
    country: 'Hungary',
    city: 'Debrecen',
    rentShared: 180,
    rentSolo: 350,
    utilities: 55,
    groceries: 120,
    dining: 70,
    transport: 25,
    healthcare: 25,
    entertainment: 45,
  },
  {
    country: 'Hungary',
    city: 'Szeged',
    rentShared: 170,
    rentSolo: 320,
    utilities: 50,
    groceries: 115,
    dining: 65,
    transport: 22,
    healthcare: 25,
    entertainment: 40,
  },
  {
    country: 'Hungary',
    city: 'Pécs',
    rentShared: 160,
    rentSolo: 300,
    utilities: 50,
    groceries: 110,
    dining: 60,
    transport: 20,
    healthcare: 25,
    entertainment: 38,
  },
  {
    country: 'Hungary',
    city: 'Miskolc',
    rentShared: 150,
    rentSolo: 280,
    utilities: 48,
    groceries: 105,
    dining: 55,
    transport: 18,
    healthcare: 22,
    entertainment: 35,
  },
  {
    country: 'Hungary',
    city: 'Győr',
    rentShared: 200,
    rentSolo: 380,
    utilities: 55,
    groceries: 125,
    dining: 75,
    transport: 24,
    healthcare: 25,
    entertainment: 45,
  },
  {
    country: 'Hungary',
    city: 'Eger',
    rentShared: 145,
    rentSolo: 270,
    utilities: 45,
    groceries: 100,
    dining: 52,
    transport: 18,
    healthcare: 22,
    entertainment: 35,
  },
  {
    country: 'Hungary',
    city: 'Veszprém',
    rentShared: 155,
    rentSolo: 290,
    utilities: 48,
    groceries: 108,
    dining: 58,
    transport: 20,
    healthcare: 22,
    entertainment: 38,
  },
];
