import type { InsertCostOfLiving } from "@shared/schema";

export const costOfLivingData: InsertCostOfLiving[] = [
  // Spain - Major Cities
  {
    country: 'Spain',
    city: 'Madrid',
    rentShared: 450,
    rentSolo: 850,
    utilities: 80,
    groceries: 200,
    dining: 150,
    transport: 55,
    healthcare: 50,
    entertainment: 100,
  },
  {
    country: 'Spain',
    city: 'Barcelona',
    rentShared: 500,
    rentSolo: 950,
    utilities: 85,
    groceries: 210,
    dining: 160,
    transport: 55,
    healthcare: 50,
    entertainment: 120,
  },
  {
    country: 'Spain',
    city: 'Valencia',
    rentShared: 350,
    rentSolo: 650,
    utilities: 70,
    groceries: 180,
    dining: 120,
    transport: 45,
    healthcare: 45,
    entertainment: 80,
  },
  {
    country: 'Spain',
    city: 'Seville',
    rentShared: 320,
    rentSolo: 580,
    utilities: 65,
    groceries: 170,
    dining: 110,
    transport: 40,
    healthcare: 45,
    entertainment: 75,
  },
  {
    country: 'Spain',
    city: 'Bilbao',
    rentShared: 380,
    rentSolo: 700,
    utilities: 75,
    groceries: 190,
    dining: 130,
    transport: 50,
    healthcare: 50,
    entertainment: 90,
  },
  {
    country: 'Spain',
    city: 'Málaga',
    rentShared: 350,
    rentSolo: 620,
    utilities: 65,
    groceries: 175,
    dining: 115,
    transport: 40,
    healthcare: 45,
    entertainment: 80,
  },
  {
    country: 'Spain',
    city: 'Granada',
    rentShared: 280,
    rentSolo: 480,
    utilities: 55,
    groceries: 160,
    dining: 100,
    transport: 35,
    healthcare: 40,
    entertainment: 65,
  },
  {
    country: 'Spain',
    city: 'Salamanca',
    rentShared: 260,
    rentSolo: 450,
    utilities: 55,
    groceries: 155,
    dining: 95,
    transport: 30,
    healthcare: 40,
    entertainment: 60,
  },
  {
    country: 'Spain',
    city: 'Zaragoza',
    rentShared: 300,
    rentSolo: 520,
    utilities: 60,
    groceries: 165,
    dining: 105,
    transport: 38,
    healthcare: 45,
    entertainment: 70,
  },
  {
    country: 'Spain',
    city: 'Santiago de Compostela',
    rentShared: 270,
    rentSolo: 480,
    utilities: 60,
    groceries: 160,
    dining: 100,
    transport: 35,
    healthcare: 42,
    entertainment: 65,
  },

  // Germany - Major Cities
  {
    country: 'Germany',
    city: 'Munich',
    rentShared: 650,
    rentSolo: 1200,
    utilities: 120,
    groceries: 250,
    dining: 180,
    transport: 65,
    healthcare: 110,
    entertainment: 120,
  },
  {
    country: 'Germany',
    city: 'Berlin',
    rentShared: 500,
    rentSolo: 900,
    utilities: 100,
    groceries: 220,
    dining: 150,
    transport: 86,
    healthcare: 110,
    entertainment: 100,
  },
  {
    country: 'Germany',
    city: 'Hamburg',
    rentShared: 520,
    rentSolo: 950,
    utilities: 105,
    groceries: 230,
    dining: 155,
    transport: 80,
    healthcare: 110,
    entertainment: 105,
  },
  {
    country: 'Germany',
    city: 'Frankfurt',
    rentShared: 580,
    rentSolo: 1050,
    utilities: 110,
    groceries: 240,
    dining: 165,
    transport: 75,
    healthcare: 110,
    entertainment: 110,
  },
  {
    country: 'Germany',
    city: 'Cologne',
    rentShared: 480,
    rentSolo: 850,
    utilities: 95,
    groceries: 210,
    dining: 140,
    transport: 70,
    healthcare: 110,
    entertainment: 95,
  },
  {
    country: 'Germany',
    city: 'Stuttgart',
    rentShared: 550,
    rentSolo: 1000,
    utilities: 105,
    groceries: 235,
    dining: 160,
    transport: 75,
    healthcare: 110,
    entertainment: 100,
  },
  {
    country: 'Germany',
    city: 'Düsseldorf',
    rentShared: 500,
    rentSolo: 900,
    utilities: 100,
    groceries: 225,
    dining: 150,
    transport: 72,
    healthcare: 110,
    entertainment: 100,
  },
  {
    country: 'Germany',
    city: 'Leipzig',
    rentShared: 350,
    rentSolo: 600,
    utilities: 85,
    groceries: 190,
    dining: 120,
    transport: 65,
    healthcare: 110,
    entertainment: 80,
  },
  {
    country: 'Germany',
    city: 'Dresden',
    rentShared: 340,
    rentSolo: 580,
    utilities: 80,
    groceries: 185,
    dining: 115,
    transport: 62,
    healthcare: 110,
    entertainment: 75,
  },
  {
    country: 'Germany',
    city: 'Heidelberg',
    rentShared: 480,
    rentSolo: 850,
    utilities: 95,
    groceries: 215,
    dining: 145,
    transport: 68,
    healthcare: 110,
    entertainment: 90,
  },
  {
    country: 'Germany',
    city: 'Freiburg',
    rentShared: 450,
    rentSolo: 800,
    utilities: 90,
    groceries: 210,
    dining: 140,
    transport: 65,
    healthcare: 110,
    entertainment: 85,
  },
  {
    country: 'Germany',
    city: 'Bonn',
    rentShared: 420,
    rentSolo: 750,
    utilities: 90,
    groceries: 200,
    dining: 135,
    transport: 68,
    healthcare: 110,
    entertainment: 85,
  },

  // Hungary - Major Cities
  {
    country: 'Hungary',
    city: 'Budapest',
    rentShared: 280,
    rentSolo: 550,
    utilities: 70,
    groceries: 150,
    dining: 100,
    transport: 35,
    healthcare: 30,
    entertainment: 60,
  },
  {
    country: 'Hungary',
    city: 'Debrecen',
    rentShared: 180,
    rentSolo: 350,
    utilities: 55,
    groceries: 120,
    dining: 70,
    transport: 25,
    healthcare: 25,
    entertainment: 45,
  },
  {
    country: 'Hungary',
    city: 'Szeged',
    rentShared: 170,
    rentSolo: 320,
    utilities: 50,
    groceries: 115,
    dining: 65,
    transport: 22,
    healthcare: 25,
    entertainment: 40,
  },
  {
    country: 'Hungary',
    city: 'Pécs',
    rentShared: 160,
    rentSolo: 300,
    utilities: 50,
    groceries: 110,
    dining: 60,
    transport: 20,
    healthcare: 25,
    entertainment: 38,
  },
  {
    country: 'Hungary',
    city: 'Miskolc',
    rentShared: 150,
    rentSolo: 280,
    utilities: 48,
    groceries: 105,
    dining: 55,
    transport: 18,
    healthcare: 22,
    entertainment: 35,
  },
  {
    country: 'Hungary',
    city: 'Győr',
    rentShared: 200,
    rentSolo: 380,
    utilities: 55,
    groceries: 125,
    dining: 75,
    transport: 24,
    healthcare: 25,
    entertainment: 45,
  },
  {
    country: 'Hungary',
    city: 'Eger',
    rentShared: 145,
    rentSolo: 270,
    utilities: 45,
    groceries: 100,
    dining: 52,
    transport: 18,
    healthcare: 22,
    entertainment: 35,
  },
  {
    country: 'Hungary',
    city: 'Veszprém',
    rentShared: 155,
    rentSolo: 290,
    utilities: 48,
    groceries: 108,
    dining: 58,
    transport: 20,
    healthcare: 22,
    entertainment: 38,
  },
  
  // Italy - Major Cities
  {
    country: 'Italy',
    city: 'Milan',
    rentShared: 550,
    rentSolo: 1100,
    utilities: 120,
    groceries: 250,
    dining: 180,
    transport: 40,
    healthcare: 50,
    entertainment: 120,
  },
  {
    country: 'Italy',
    city: 'Rome',
    rentShared: 480,
    rentSolo: 950,
    utilities: 110,
    groceries: 230,
    dining: 160,
    transport: 40,
    healthcare: 50,
    entertainment: 110,
  },
  {
    country: 'Italy',
    city: 'Bologna',
    rentShared: 420,
    rentSolo: 800,
    utilities: 100,
    groceries: 210,
    dining: 140,
    transport: 35,
    healthcare: 45,
    entertainment: 90,
  },
  {
    country: 'Italy',
    city: 'Florence',
    rentShared: 450,
    rentSolo: 900,
    utilities: 105,
    groceries: 220,
    dining: 150,
    transport: 35,
    healthcare: 45,
    entertainment: 100,
  },
  {
    country: 'Italy',
    city: 'Turin',
    rentShared: 380,
    rentSolo: 720,
    utilities: 95,
    groceries: 200,
    dining: 130,
    transport: 38,
    healthcare: 45,
    entertainment: 85,
  },
  {
    country: 'Italy',
    city: 'Naples',
    rentShared: 320,
    rentSolo: 600,
    utilities: 85,
    groceries: 180,
    dining: 100,
    transport: 30,
    healthcare: 40,
    entertainment: 70,
  },
  {
    country: 'Italy',
    city: 'Padua',
    rentShared: 380,
    rentSolo: 700,
    utilities: 90,
    groceries: 195,
    dining: 120,
    transport: 30,
    healthcare: 42,
    entertainment: 80,
  },
  {
    country: 'Italy',
    city: 'Pisa',
    rentShared: 350,
    rentSolo: 650,
    utilities: 88,
    groceries: 190,
    dining: 115,
    transport: 28,
    healthcare: 40,
    entertainment: 75,
  },
  {
    country: 'Italy',
    city: 'Venice',
    rentShared: 480,
    rentSolo: 950,
    utilities: 115,
    groceries: 240,
    dining: 170,
    transport: 35,
    healthcare: 50,
    entertainment: 100,
  },
  {
    country: 'Italy',
    city: 'Genoa',
    rentShared: 350,
    rentSolo: 680,
    utilities: 90,
    groceries: 190,
    dining: 120,
    transport: 32,
    healthcare: 42,
    entertainment: 75,
  },
  {
    country: 'Italy',
    city: 'Verona',
    rentShared: 380,
    rentSolo: 720,
    utilities: 92,
    groceries: 200,
    dining: 125,
    transport: 30,
    healthcare: 42,
    entertainment: 80,
  },
  {
    country: 'Italy',
    city: 'Palermo',
    rentShared: 280,
    rentSolo: 500,
    utilities: 75,
    groceries: 165,
    dining: 90,
    transport: 25,
    healthcare: 35,
    entertainment: 60,
  },
  {
    country: 'Italy',
    city: 'Catania',
    rentShared: 260,
    rentSolo: 480,
    utilities: 72,
    groceries: 160,
    dining: 85,
    transport: 24,
    healthcare: 35,
    entertainment: 55,
  },
  {
    country: 'Italy',
    city: 'Trieste',
    rentShared: 340,
    rentSolo: 620,
    utilities: 88,
    groceries: 185,
    dining: 110,
    transport: 28,
    healthcare: 40,
    entertainment: 72,
  },
  {
    country: 'Italy',
    city: 'Trento',
    rentShared: 400,
    rentSolo: 750,
    utilities: 95,
    groceries: 205,
    dining: 130,
    transport: 32,
    healthcare: 45,
    entertainment: 85,
  },
  
  // Poland - Major Cities
  {
    country: 'Poland',
    city: 'Warsaw',
    rentShared: 450,
    rentSolo: 850,
    utilities: 100,
    groceries: 180,
    dining: 120,
    transport: 30,
    healthcare: 40,
    entertainment: 80,
  },
  {
    country: 'Poland',
    city: 'Krakow',
    rentShared: 380,
    rentSolo: 700,
    utilities: 90,
    groceries: 165,
    dining: 100,
    transport: 25,
    healthcare: 35,
    entertainment: 70,
  },
  {
    country: 'Poland',
    city: 'Wroclaw',
    rentShared: 350,
    rentSolo: 650,
    utilities: 85,
    groceries: 160,
    dining: 95,
    transport: 25,
    healthcare: 35,
    entertainment: 65,
  },
  {
    country: 'Poland',
    city: 'Poznan',
    rentShared: 340,
    rentSolo: 620,
    utilities: 82,
    groceries: 155,
    dining: 90,
    transport: 24,
    healthcare: 35,
    entertainment: 60,
  },
  {
    country: 'Poland',
    city: 'Gdansk',
    rentShared: 380,
    rentSolo: 700,
    utilities: 88,
    groceries: 165,
    dining: 100,
    transport: 28,
    healthcare: 35,
    entertainment: 70,
  },
  {
    country: 'Poland',
    city: 'Lodz',
    rentShared: 300,
    rentSolo: 550,
    utilities: 78,
    groceries: 145,
    dining: 80,
    transport: 22,
    healthcare: 32,
    entertainment: 55,
  },
  {
    country: 'Poland',
    city: 'Katowice',
    rentShared: 320,
    rentSolo: 580,
    utilities: 80,
    groceries: 150,
    dining: 85,
    transport: 23,
    healthcare: 32,
    entertainment: 58,
  },
  {
    country: 'Poland',
    city: 'Lublin',
    rentShared: 280,
    rentSolo: 500,
    utilities: 72,
    groceries: 140,
    dining: 75,
    transport: 20,
    healthcare: 30,
    entertainment: 50,
  },
  {
    country: 'Poland',
    city: 'Szczecin',
    rentShared: 300,
    rentSolo: 550,
    utilities: 78,
    groceries: 148,
    dining: 82,
    transport: 22,
    healthcare: 32,
    entertainment: 55,
  },
  {
    country: 'Poland',
    city: 'Bialystok',
    rentShared: 260,
    rentSolo: 480,
    utilities: 70,
    groceries: 135,
    dining: 70,
    transport: 18,
    healthcare: 28,
    entertainment: 48,
  },
  {
    country: 'Poland',
    city: 'Olsztyn',
    rentShared: 280,
    rentSolo: 520,
    utilities: 75,
    groceries: 142,
    dining: 78,
    transport: 20,
    healthcare: 30,
    entertainment: 52,
  },
  {
    country: 'Poland',
    city: 'Gliwice',
    rentShared: 290,
    rentSolo: 530,
    utilities: 75,
    groceries: 145,
    dining: 80,
    transport: 22,
    healthcare: 30,
    entertainment: 55,
  },
  
  // Netherlands - Major Cities (2025 data based on student housing research)
  {
    country: 'Netherlands',
    city: 'Amsterdam',
    rentShared: 950,
    rentSolo: 1650,
    utilities: 180,
    groceries: 300,
    dining: 220,
    transport: 100,
    healthcare: 130,
    entertainment: 160,
  },
  {
    country: 'Netherlands',
    city: 'Rotterdam',
    rentShared: 700,
    rentSolo: 1300,
    utilities: 160,
    groceries: 280,
    dining: 190,
    transport: 95,
    healthcare: 130,
    entertainment: 140,
  },
  {
    country: 'Netherlands',
    city: 'The Hague',
    rentShared: 720,
    rentSolo: 1350,
    utilities: 165,
    groceries: 285,
    dining: 195,
    transport: 95,
    healthcare: 130,
    entertainment: 145,
  },
  {
    country: 'Netherlands',
    city: 'Utrecht',
    rentShared: 750,
    rentSolo: 1400,
    utilities: 165,
    groceries: 285,
    dining: 190,
    transport: 95,
    healthcare: 130,
    entertainment: 140,
  },
  {
    country: 'Netherlands',
    city: 'Eindhoven',
    rentShared: 600,
    rentSolo: 1100,
    utilities: 150,
    groceries: 260,
    dining: 170,
    transport: 85,
    healthcare: 130,
    entertainment: 120,
  },
  {
    country: 'Netherlands',
    city: 'Groningen',
    rentShared: 550,
    rentSolo: 950,
    utilities: 140,
    groceries: 250,
    dining: 160,
    transport: 80,
    healthcare: 130,
    entertainment: 110,
  },
  {
    country: 'Netherlands',
    city: 'Delft',
    rentShared: 680,
    rentSolo: 1250,
    utilities: 155,
    groceries: 270,
    dining: 180,
    transport: 90,
    healthcare: 130,
    entertainment: 125,
  },
  {
    country: 'Netherlands',
    city: 'Leiden',
    rentShared: 700,
    rentSolo: 1300,
    utilities: 158,
    groceries: 275,
    dining: 185,
    transport: 90,
    healthcare: 130,
    entertainment: 130,
  },
  {
    country: 'Netherlands',
    city: 'Maastricht',
    rentShared: 550,
    rentSolo: 1000,
    utilities: 145,
    groceries: 255,
    dining: 165,
    transport: 80,
    healthcare: 130,
    entertainment: 115,
  },
  {
    country: 'Netherlands',
    city: 'Nijmegen',
    rentShared: 530,
    rentSolo: 950,
    utilities: 140,
    groceries: 250,
    dining: 160,
    transport: 78,
    healthcare: 130,
    entertainment: 110,
  },
  {
    country: 'Netherlands',
    city: 'Enschede',
    rentShared: 480,
    rentSolo: 880,
    utilities: 135,
    groceries: 240,
    dining: 150,
    transport: 75,
    healthcare: 130,
    entertainment: 100,
  },
  {
    country: 'Netherlands',
    city: 'Tilburg',
    rentShared: 520,
    rentSolo: 950,
    utilities: 140,
    groceries: 245,
    dining: 155,
    transport: 78,
    healthcare: 130,
    entertainment: 110,
  },
  // Czech Republic - Major Cities
  {
    country: 'Czech Republic',
    city: 'Prague',
    rentShared: 400,
    rentSolo: 750,
    utilities: 100,
    groceries: 180,
    dining: 120,
    transport: 25,
    healthcare: 40,
    entertainment: 80,
  },
  {
    country: 'Czech Republic',
    city: 'Brno',
    rentShared: 320,
    rentSolo: 580,
    utilities: 90,
    groceries: 160,
    dining: 100,
    transport: 22,
    healthcare: 35,
    entertainment: 65,
  },
  {
    country: 'Czech Republic',
    city: 'Ostrava',
    rentShared: 280,
    rentSolo: 480,
    utilities: 85,
    groceries: 150,
    dining: 85,
    transport: 20,
    healthcare: 35,
    entertainment: 55,
  },
  {
    country: 'Czech Republic',
    city: 'Olomouc',
    rentShared: 260,
    rentSolo: 450,
    utilities: 80,
    groceries: 145,
    dining: 80,
    transport: 18,
    healthcare: 30,
    entertainment: 50,
  },
  {
    country: 'Czech Republic',
    city: 'Pilsen',
    rentShared: 300,
    rentSolo: 520,
    utilities: 85,
    groceries: 155,
    dining: 90,
    transport: 20,
    healthcare: 35,
    entertainment: 55,
  },
  {
    country: 'Czech Republic',
    city: 'Liberec',
    rentShared: 270,
    rentSolo: 470,
    utilities: 82,
    groceries: 150,
    dining: 85,
    transport: 18,
    healthcare: 32,
    entertainment: 50,
  },
  {
    country: 'Czech Republic',
    city: 'České Budějovice',
    rentShared: 280,
    rentSolo: 480,
    utilities: 80,
    groceries: 148,
    dining: 82,
    transport: 18,
    healthcare: 32,
    entertainment: 52,
  },
  {
    country: 'Czech Republic',
    city: 'Hradec Králové',
    rentShared: 290,
    rentSolo: 500,
    utilities: 82,
    groceries: 152,
    dining: 85,
    transport: 19,
    healthcare: 33,
    entertainment: 54,
  },
  // Finland - Major Cities
  {
    country: 'Finland',
    city: 'Helsinki',
    rentShared: 550,
    rentSolo: 1100,
    utilities: 120,
    groceries: 280,
    dining: 180,
    transport: 60,
    healthcare: 0,
    entertainment: 100,
  },
  {
    country: 'Finland',
    city: 'Espoo',
    rentShared: 520,
    rentSolo: 1000,
    utilities: 115,
    groceries: 270,
    dining: 170,
    transport: 60,
    healthcare: 0,
    entertainment: 90,
  },
  {
    country: 'Finland',
    city: 'Tampere',
    rentShared: 400,
    rentSolo: 750,
    utilities: 100,
    groceries: 250,
    dining: 150,
    transport: 50,
    healthcare: 0,
    entertainment: 80,
  },
  {
    country: 'Finland',
    city: 'Turku',
    rentShared: 380,
    rentSolo: 700,
    utilities: 95,
    groceries: 245,
    dining: 145,
    transport: 48,
    healthcare: 0,
    entertainment: 75,
  },
  {
    country: 'Finland',
    city: 'Oulu',
    rentShared: 350,
    rentSolo: 650,
    utilities: 90,
    groceries: 240,
    dining: 140,
    transport: 45,
    healthcare: 0,
    entertainment: 70,
  },
  {
    country: 'Finland',
    city: 'Jyväskylä',
    rentShared: 340,
    rentSolo: 620,
    utilities: 88,
    groceries: 235,
    dining: 135,
    transport: 42,
    healthcare: 0,
    entertainment: 68,
  },
  {
    country: 'Finland',
    city: 'Kuopio',
    rentShared: 320,
    rentSolo: 580,
    utilities: 85,
    groceries: 230,
    dining: 130,
    transport: 40,
    healthcare: 0,
    entertainment: 65,
  },
  {
    country: 'Finland',
    city: 'Rovaniemi',
    rentShared: 350,
    rentSolo: 620,
    utilities: 100,
    groceries: 260,
    dining: 150,
    transport: 45,
    healthcare: 0,
    entertainment: 70,
  },
  // Portugal - Major Cities
  {
    country: 'Portugal',
    city: 'Lisbon',
    rentShared: 450,
    rentSolo: 900,
    utilities: 80,
    groceries: 200,
    dining: 120,
    transport: 40,
    healthcare: 30,
    entertainment: 80,
  },
  {
    country: 'Portugal',
    city: 'Porto',
    rentShared: 380,
    rentSolo: 750,
    utilities: 75,
    groceries: 190,
    dining: 100,
    transport: 35,
    healthcare: 30,
    entertainment: 70,
  },
  {
    country: 'Portugal',
    city: 'Coimbra',
    rentShared: 280,
    rentSolo: 500,
    utilities: 65,
    groceries: 170,
    dining: 80,
    transport: 30,
    healthcare: 25,
    entertainment: 55,
  },
  {
    country: 'Portugal',
    city: 'Braga',
    rentShared: 300,
    rentSolo: 550,
    utilities: 68,
    groceries: 175,
    dining: 85,
    transport: 32,
    healthcare: 28,
    entertainment: 60,
  },
  {
    country: 'Portugal',
    city: 'Aveiro',
    rentShared: 280,
    rentSolo: 500,
    utilities: 65,
    groceries: 170,
    dining: 80,
    transport: 28,
    healthcare: 25,
    entertainment: 55,
  },
  {
    country: 'Portugal',
    city: 'Faro',
    rentShared: 350,
    rentSolo: 650,
    utilities: 70,
    groceries: 185,
    dining: 95,
    transport: 35,
    healthcare: 28,
    entertainment: 65,
  },
  {
    country: 'Portugal',
    city: 'Évora',
    rentShared: 260,
    rentSolo: 450,
    utilities: 60,
    groceries: 165,
    dining: 75,
    transport: 25,
    healthcare: 25,
    entertainment: 50,
  },
  {
    country: 'Portugal',
    city: 'Funchal',
    rentShared: 320,
    rentSolo: 600,
    utilities: 65,
    groceries: 195,
    dining: 90,
    transport: 35,
    healthcare: 30,
    entertainment: 60,
  },
  // Sweden - Major Cities
  {
    country: 'Sweden',
    city: 'Stockholm',
    rentShared: 650,
    rentSolo: 1200,
    utilities: 80,
    groceries: 280,
    dining: 200,
    transport: 95,
    healthcare: 25,
    entertainment: 150,
  },
  {
    country: 'Sweden',
    city: 'Gothenburg',
    rentShared: 550,
    rentSolo: 1000,
    utilities: 75,
    groceries: 260,
    dining: 180,
    transport: 85,
    healthcare: 25,
    entertainment: 130,
  },
  {
    country: 'Sweden',
    city: 'Malmö',
    rentShared: 500,
    rentSolo: 900,
    utilities: 70,
    groceries: 250,
    dining: 170,
    transport: 75,
    healthcare: 25,
    entertainment: 120,
  },
  {
    country: 'Sweden',
    city: 'Uppsala',
    rentShared: 550,
    rentSolo: 950,
    utilities: 75,
    groceries: 260,
    dining: 175,
    transport: 80,
    healthcare: 25,
    entertainment: 125,
  },
  {
    country: 'Sweden',
    city: 'Lund',
    rentShared: 500,
    rentSolo: 880,
    utilities: 70,
    groceries: 250,
    dining: 165,
    transport: 70,
    healthcare: 25,
    entertainment: 115,
  },
  {
    country: 'Sweden',
    city: 'Linköping',
    rentShared: 450,
    rentSolo: 800,
    utilities: 65,
    groceries: 240,
    dining: 155,
    transport: 65,
    healthcare: 25,
    entertainment: 100,
  },
  {
    country: 'Sweden',
    city: 'Umeå',
    rentShared: 420,
    rentSolo: 750,
    utilities: 80,
    groceries: 250,
    dining: 150,
    transport: 60,
    healthcare: 25,
    entertainment: 95,
  },
  {
    country: 'Sweden',
    city: 'Örebro',
    rentShared: 400,
    rentSolo: 720,
    utilities: 65,
    groceries: 235,
    dining: 145,
    transport: 60,
    healthcare: 25,
    entertainment: 90,
  },
];
