import type { InsertCountryProfile } from "@shared/schema";

export const countryProfilesData: InsertCountryProfile[] = [
  {
    country: 'Spain',
    visaType: 'Student Visa (Type D)',
    visaProcessingTime: '2-4 weeks',
    visaCost: '€80 (application fee)',
    visaSuccessRate: '97% approval rate',
    ieltsMinimum: '5.5',
    ieltsRecommended: '6.0-6.5',
    financialRequirement: '€600/month (IPREM) in bank account for duration of stay',
    workHoursAllowed: '20 hours/week during term, full-time during holidays',
    postStudyWorkVisa: '12 months job search visa after graduation',
    pathToResidency: 'After 3 years on student visa, can apply for work permit; 5 years for permanent residency',
    healthInsurance: 'Required - Public or private coverage mandatory',
    languageRequirement: 'Spanish B1 for most programs; English for international programs',
    immigrationPortal: 'https://sede.administracionespublicas.gob.es',
    graduateEmploymentRate: '78% within 1 year of graduation',
    averageSalaryEntry: '€22,000 - €28,000/year',
    averageSalaryMid: '€35,000 - €45,000/year',
    topSectors: ['Tourism & Hospitality', 'Technology', 'Renewable Energy', 'Healthcare', 'Automotive'],
    inDemandJobs: ['Software Developer', 'Data Analyst', 'Digital Marketing', 'Nurse', 'Engineer', 'Renewable Energy Technician'],
    languageForWork: 'Spanish essential for most jobs; English-only roles in tech and multinationals',
    jobSearchTimeline: '3-6 months average job search after graduation',
    workCulture: 'Relaxed pace, siesta culture in some regions, strong work-life balance, 40-hour work week',
    jobPortals: ['InfoJobs.net', 'LinkedIn Spain', 'Indeed.es', 'Tecnoempleo'],
    officialLanguage: 'Spanish (Catalan, Basque, Galician in regions)',
    currency: 'EUR',
    qualityOfLife: 'Excellent climate, rich culture, affordable compared to Northern Europe',
  },
  {
    country: 'Germany',
    visaType: 'Student Visa (Aufenthaltserlaubnis)',
    visaProcessingTime: '4-8 weeks',
    visaCost: '€75 (application fee)',
    visaSuccessRate: '92-95% approval rate',
    ieltsMinimum: '6.0',
    ieltsRecommended: '6.5-7.0',
    financialRequirement: '€11,208/year (€934/month) in blocked account',
    workHoursAllowed: '120 full days or 240 half days per year',
    postStudyWorkVisa: '18 months job search visa after graduation',
    pathToResidency: 'Blue Card available for skilled workers earning €45,300+; permanent residency after 33 months (21 with German B1)',
    healthInsurance: 'Mandatory - Public insurance ~€110/month for students',
    languageRequirement: 'German B2/C1 for German programs; English for international programs',
    immigrationPortal: 'https://www.make-it-in-germany.com',
    graduateEmploymentRate: '92% within 1 year of graduation',
    averageSalaryEntry: '€45,000 - €55,000/year',
    averageSalaryMid: '€60,000 - €80,000/year',
    topSectors: ['Automotive', 'Engineering', 'IT & Tech', 'Pharmaceutical', 'Finance', 'Manufacturing'],
    inDemandJobs: ['Software Engineer', 'Mechanical Engineer', 'Data Scientist', 'IT Security', 'Healthcare Professional', 'Electrical Engineer'],
    languageForWork: 'German required for most jobs; English sufficient in IT, startups, and multinationals',
    jobSearchTimeline: '2-4 months average for STEM graduates',
    workCulture: 'Punctual, efficient, clear hierarchy, strong work-life separation, 35-40 hour week, generous vacation (30 days)',
    jobPortals: ['StepStone.de', 'Indeed.de', 'XING', 'LinkedIn Germany', 'Arbeitsagentur.de'],
    officialLanguage: 'German',
    currency: 'EUR',
    qualityOfLife: 'High standard of living, excellent public transport, rich cultural scene',
  },
  {
    country: 'Hungary',
    visaType: 'Student Residence Permit',
    visaProcessingTime: '2-4 weeks',
    visaCost: '€60 (application fee)',
    visaSuccessRate: '~85% approval rate',
    ieltsMinimum: '5.5',
    ieltsRecommended: '6.0-6.5',
    financialRequirement: '€400-500/month proof of funds',
    workHoursAllowed: '24 hours/week during term, full-time during holidays',
    postStudyWorkVisa: '9 months job search permit after graduation',
    pathToResidency: 'After 3 years of legal stay can apply for permanent residence',
    healthInsurance: 'Required - EU students covered by EHIC; others need private insurance (~€50-80/month)',
    languageRequirement: 'Hungarian for Hungarian programs; English for international programs',
    immigrationPortal: 'https://oif.gov.hu',
    graduateEmploymentRate: '85% within 1 year of graduation',
    averageSalaryEntry: '€12,000 - €18,000/year',
    averageSalaryMid: '€20,000 - €35,000/year',
    topSectors: ['IT & Technology', 'Automotive', 'Pharmaceutical', 'Shared Services Centers', 'Healthcare'],
    inDemandJobs: ['Software Developer', 'IT Support', 'Accountant', 'Customer Service', 'Engineer', 'Medical Professional'],
    languageForWork: 'Hungarian for local companies; English for multinationals and IT',
    jobSearchTimeline: '2-4 months average job search',
    workCulture: 'Growing startup scene, many multinationals in Budapest, standard 40-hour week',
    jobPortals: ['Profession.hu', 'CVOnline.hu', 'LinkedIn Hungary', 'Indeed.hu'],
    officialLanguage: 'Hungarian',
    currency: 'HUF (Hungarian Forint)',
    qualityOfLife: 'Very affordable, vibrant nightlife in Budapest, thermal baths, rich history',
  },
  {
    country: 'Italy',
    visaType: 'Student Visa (Visto per Studio)',
    visaProcessingTime: '2-4 weeks',
    visaCost: '€50 (application fee)',
    visaSuccessRate: '~90% approval rate',
    ieltsMinimum: '5.5',
    ieltsRecommended: '6.0-6.5',
    financialRequirement: '€6,000-8,000/year proof of funds',
    workHoursAllowed: '20 hours/week during term, full-time during holidays',
    postStudyWorkVisa: '12 months job search visa ("attesa occupazione")',
    pathToResidency: 'After 5 years of legal residence; EU Blue Card available for skilled workers',
    healthInsurance: 'Required - Can enroll in National Health Service (SSN) or private insurance',
    languageRequirement: 'Italian B2 for most programs; English for international programs',
    immigrationPortal: 'https://vistoperitalia.esteri.it',
    graduateEmploymentRate: '72% within 1 year of graduation',
    averageSalaryEntry: '€24,000 - €32,000/year',
    averageSalaryMid: '€38,000 - €50,000/year',
    topSectors: ['Fashion & Luxury', 'Automotive', 'Tourism', 'Food & Agriculture', 'Manufacturing', 'Design'],
    inDemandJobs: ['Engineer', 'IT Professional', 'Designer', 'Marketing Specialist', 'Healthcare Worker', 'Hospitality Manager'],
    languageForWork: 'Italian essential for most jobs; English in fashion, tourism, and multinationals',
    jobSearchTimeline: '4-8 months average job search',
    workCulture: 'Relationship-focused, extended lunch breaks common, work-life balance varies by region',
    jobPortals: ['InfoJobs.it', 'Indeed.it', 'Monster.it', 'LinkedIn Italy', 'Subito.it'],
    officialLanguage: 'Italian',
    currency: 'EUR',
    qualityOfLife: 'World-class food and culture, beautiful landscapes, slower pace of life',
  },
  {
    country: 'Poland',
    visaType: 'Student Visa (National D Visa)',
    visaProcessingTime: '2-3 weeks',
    visaCost: '€80 (application fee)',
    visaSuccessRate: '~88% approval rate',
    ieltsMinimum: '5.5',
    ieltsRecommended: '6.0',
    financialRequirement: '€400-500/month proof of funds',
    workHoursAllowed: 'No restrictions for full-time students',
    postStudyWorkVisa: '12 months job search visa; work permit not needed during studies',
    pathToResidency: 'Temporary residence after graduation with job offer; permanent after 5 years',
    healthInsurance: 'Required - Students can use public healthcare (NFZ) or private insurance (~€30-50/month)',
    languageRequirement: 'Polish for Polish programs; English for international programs',
    immigrationPortal: 'https://www.gov.pl/web/udsc-en',
    graduateEmploymentRate: '88% within 1 year of graduation',
    averageSalaryEntry: '€14,000 - €22,000/year',
    averageSalaryMid: '€28,000 - €45,000/year',
    topSectors: ['IT & Technology', 'Business Services', 'Manufacturing', 'Finance', 'Gaming', 'E-commerce'],
    inDemandJobs: ['Software Developer', 'IT Support', 'Project Manager', 'Accountant', 'Game Developer', 'UX Designer'],
    languageForWork: 'Polish for local companies; English widely used in IT and international companies',
    jobSearchTimeline: '1-3 months average for IT graduates; 3-5 months for other fields',
    workCulture: 'Growing tech hub, many remote work options, startup friendly, 40-hour work week',
    jobPortals: ['Pracuj.pl', 'NoFluffJobs.com', 'JustJoinIT', 'LinkedIn Poland', 'Indeed.pl'],
    officialLanguage: 'Polish',
    currency: 'PLN (Polish Zloty)',
    qualityOfLife: 'Very affordable, rapidly developing cities, good internet, young and dynamic atmosphere',
  },
  {
    country: 'Netherlands',
    visaType: 'MVV + Residence Permit (VVR)',
    visaProcessingTime: '4-6 weeks',
    visaCost: '€210 (MVV + residence permit)',
    visaSuccessRate: '97-99% approval rate',
    ieltsMinimum: '6.0',
    ieltsRecommended: '6.5-7.0',
    financialRequirement: '€11,100-14,700/year proof of funds',
    workHoursAllowed: '16 hours/week during term, full-time June-August',
    postStudyWorkVisa: '1 year Orientation Year (Zoekjaar) visa after graduation',
    pathToResidency: 'After 5 years legal residence; Highly Skilled Migrant scheme available with job offer',
    healthInsurance: 'Required - Basic Dutch health insurance ~€130/month',
    languageRequirement: 'English sufficient for most programs; Dutch helpful for daily life',
    immigrationPortal: 'https://ind.nl/en',
    graduateEmploymentRate: '93% within 1 year of graduation',
    averageSalaryEntry: '€32,000 - €38,000/year',
    averageSalaryMid: '€45,000 - €60,000/year',
    topSectors: ['Technology', 'Logistics', 'Finance', 'Agriculture', 'Creative Industries', 'Sustainability'],
    inDemandJobs: ['Software Developer', 'Data Scientist', 'Engineer', 'Supply Chain Manager', 'UX Designer', 'Sustainability Consultant'],
    languageForWork: 'English widely used in business; Dutch helpful for some sectors',
    jobSearchTimeline: '2-4 months average for STEM graduates',
    workCulture: 'Direct communication, flat hierarchy, work-life balance priority, cycling culture, 36-40 hour week',
    jobPortals: ['LinkedIn Netherlands', 'Indeed.nl', 'Glassdoor.nl', 'Intermediair.nl', 'Nationalevacaturebank.nl'],
    officialLanguage: 'Dutch',
    currency: 'EUR',
    qualityOfLife: 'High quality of life, excellent cycling infrastructure, multicultural, English widely spoken',
  },
];
