import type { InsertUniversity } from "@shared/schema";

export const czechUniversities: InsertUniversity[] = [
  {
    name: "Charles University",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Medicine & Health", "Law & Politics", "Sciences", "Social Sciences & Humanities", "Arts & Design"],
    admissionPeriod: "February - April",
    website: "https://cuni.cz",
    description: "Founded in 1348, Charles University is the oldest and largest university in Czech Republic. It's a prestigious research university with 17 faculties and over 50,000 students.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€3,000 - €15,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 51000,
    globalRank: 246,
  },
  {
    name: "Czech Technical University in Prague",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Engineering & Technology", "Sciences", "Architecture"],
    admissionPeriod: "January - March",
    website: "https://cvut.cz",
    description: "One of the oldest technical universities in Europe, founded in 1707. CTU is a leading institution in engineering, IT, and architecture with strong industry connections.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€4,000 - €8,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 21000,
    globalRank: 403,
  },
  {
    name: "Masaryk University",
    country: "Czech Republic",
    region: "South Moravian",
    city: "Brno",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Medicine & Health", "Sciences", "Law & Politics", "Social Sciences & Humanities", "Business & Economics"],
    admissionPeriod: "February - April",
    website: "https://muni.cz",
    description: "The second largest university in Czech Republic, located in Brno. Known for research excellence and a vibrant international student community.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,500 - €12,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 35000,
    globalRank: 411,
  },
  {
    name: "Brno University of Technology",
    country: "Czech Republic",
    region: "South Moravian",
    city: "Brno",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Engineering & Technology", "Sciences", "Business & Economics", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://vutbr.cz",
    description: "A leading technical university in Central Europe with strong focus on engineering, IT, and applied sciences. Known for excellent industry partnerships.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€3,500 - €6,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 19000,
    globalRank: 650,
  },
  {
    name: "Palacký University Olomouc",
    country: "Czech Republic",
    region: "Olomouc",
    city: "Olomouc",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Medicine & Health", "Sciences", "Social Sciences & Humanities", "Law & Politics", "Sports & Tourism"],
    admissionPeriod: "February - April",
    website: "https://upol.cz",
    description: "The second oldest university in Czech Republic, founded in 1573. Offers a wide range of programs in a beautiful historic city.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,500 - €10,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 23000,
    globalRank: 651,
  },
  {
    name: "University of Chemistry and Technology Prague",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Sciences", "Engineering & Technology", "Agriculture & Environment"],
    admissionPeriod: "January - March",
    website: "https://vscht.cz",
    description: "The largest university of its kind in Central Europe, specializing in chemistry, chemical engineering, food science, and related fields.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€4,000 - €6,500/year",
    tuitionPeriod: "per year",
    totalEnrollment: 4500,
    globalRank: 501,
  },
  {
    name: "Czech University of Life Sciences Prague",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Agriculture & Environment", "Engineering & Technology", "Business & Economics", "Sciences"],
    admissionPeriod: "January - March",
    website: "https://czu.cz",
    description: "A specialized university focusing on agriculture, forestry, environmental sciences, and sustainable development. Beautiful campus in Prague suburbs.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 18000,
    globalRank: 750,
  },
  {
    name: "University of Economics Prague",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Media & Communication"],
    admissionPeriod: "February - April",
    website: "https://vse.cz",
    description: "The leading business school in Czech Republic with AACSB accreditation. Strong connections to the business community and excellent career prospects.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€4,000 - €6,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 15000,
    globalRank: 600,
  },
  {
    name: "Technical University of Ostrava",
    country: "Czech Republic",
    region: "Moravian-Silesian",
    city: "Ostrava",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Engineering & Technology", "Sciences", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://vsb.cz",
    description: "A major technical university in the industrial heart of Moravia. Strong focus on mining, metallurgy, IT, and modern engineering fields.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€3,000 - €5,500/year",
    tuitionPeriod: "per year",
    totalEnrollment: 16000,
    globalRank: 800,
  },
  {
    name: "University of Pardubice",
    country: "Czech Republic",
    region: "Pardubice",
    city: "Pardubice",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Sciences", "Engineering & Technology", "Business & Economics", "Social Sciences & Humanities"],
    admissionPeriod: "January - March",
    website: "https://upce.cz",
    description: "A young but dynamic university with strong programs in chemistry, transport, electrical engineering, and humanities.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,500 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
    globalRank: 900,
  },
  {
    name: "University of West Bohemia",
    country: "Czech Republic",
    region: "Pilsen",
    city: "Pilsen",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Engineering & Technology", "Sciences", "Arts & Design", "Law & Politics", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://zcu.cz",
    description: "A comprehensive university in Pilsen with strong engineering and design programs. Known for innovation and industry collaboration.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 12000,
    globalRank: 850,
  },
  {
    name: "Mendel University in Brno",
    country: "Czech Republic",
    region: "South Moravian",
    city: "Brno",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Agriculture & Environment", "Business & Economics", "Sciences"],
    admissionPeriod: "January - March",
    website: "https://mendelu.cz",
    description: "Named after Gregor Mendel, this university specializes in agriculture, forestry, horticulture, and regional development.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,500 - €4,500/year",
    tuitionPeriod: "per year",
    totalEnrollment: 10000,
    globalRank: 950,
  },
  {
    name: "Technical University of Liberec",
    country: "Czech Republic",
    region: "Liberec",
    city: "Liberec",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Engineering & Technology", "Sciences", "Arts & Design", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://tul.cz",
    description: "A technical university in beautiful North Bohemia, known for textile engineering, mechatronics, and nanotechnology research.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,500 - €4,500/year",
    tuitionPeriod: "per year",
    totalEnrollment: 7000,
    globalRank: 1000,
  },
  {
    name: "University of South Bohemia",
    country: "Czech Republic",
    region: "South Bohemian",
    city: "České Budějovice",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Sciences", "Agriculture & Environment", "Social Sciences & Humanities", "Medicine & Health"],
    admissionPeriod: "February - April",
    website: "https://jcu.cz",
    description: "Located in the picturesque South Bohemia region, offering programs in natural sciences, fisheries, and health sciences.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,500 - €8,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 11000,
    globalRank: 1050,
  },
  {
    name: "University of Hradec Králové",
    country: "Czech Republic",
    region: "Hradec Králové",
    city: "Hradec Králové",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Social Sciences & Humanities", "Sciences", "Business & Economics"],
    admissionPeriod: "February - April",
    website: "https://uhk.cz",
    description: "A growing university with focus on informatics, education, social sciences, and management.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€2,000 - €4,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 8000,
    globalRank: 1100,
  },
  {
    name: "Anglo-American University",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Private",
    languages: ["English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Law & Politics", "Media & Communication"],
    admissionPeriod: "Rolling admissions",
    website: "https://aauni.edu",
    description: "The first private university in Czech Republic, offering American-style liberal arts education entirely in English.",
    englishPrograms: true,
    tuitionFeeEU: "€6,000 - €8,000/year",
    tuitionFeeNonEU: "€6,000 - €8,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 1200,
    globalRank: null,
  },
  {
    name: "NEWTON University",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Private",
    languages: ["Czech", "English"],
    domains: ["Business & Economics", "Media & Communication"],
    admissionPeriod: "Rolling admissions",
    website: "https://newtoncollege.cz",
    description: "A private business school focusing on practical business education with strong emphasis on entrepreneurship.",
    englishPrograms: true,
    tuitionFeeEU: "€3,500 - €5,000/year",
    tuitionFeeNonEU: "€3,500 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 2000,
    globalRank: null,
  },
  {
    name: "University of New York in Prague",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Private",
    languages: ["English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Media & Communication", "Arts & Design"],
    admissionPeriod: "Rolling admissions",
    website: "https://unyp.cz",
    description: "Offers American-accredited degrees in partnership with US universities. Popular among international students seeking US education in Europe.",
    englishPrograms: true,
    tuitionFeeEU: "€7,000 - €9,000/year",
    tuitionFeeNonEU: "€7,000 - €9,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 800,
    globalRank: null,
  },
  {
    name: "Academy of Performing Arts in Prague (DAMU)",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Arts & Design", "Media & Communication"],
    admissionPeriod: "January - February",
    website: "https://amu.cz",
    description: "One of Europe's top performing arts schools, offering programs in theatre, film, music, and dance.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€5,000 - €12,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 1500,
    globalRank: null,
  },
  {
    name: "Academy of Fine Arts Prague",
    country: "Czech Republic",
    region: "Prague",
    city: "Prague",
    type: "Public",
    languages: ["Czech", "English"],
    domains: ["Arts & Design"],
    admissionPeriod: "November - January",
    website: "https://avu.cz",
    description: "The oldest art academy in Central Europe, founded in 1799. Prestigious institution for visual arts education.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Czech programs)",
    tuitionFeeNonEU: "€4,000 - €7,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 350,
    globalRank: null,
  },
];
