import type { InsertUniversity } from "@shared/schema";

export const dutchUniversities: InsertUniversity[] = [
  // Research Universities (WO)
  {
    name: "Delft University of Technology (TU Delft)",
    country: "Netherlands",
    region: "South Holland",
    city: "Delft",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Engineering", "Technology", "Architecture", "Applied Sciences"],
    admissionPeriod: "January 15 - May 1, 2026",
    website: "https://www.tudelft.nl",
    description: "Leading technical university ranked #49 globally. Known for aerospace, civil engineering, and design. Strong focus on innovation and sustainability.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€15,000-22,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "University of Amsterdam (UvA)",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Social Sciences", "Humanities", "Sciences", "Medicine"],
    admissionPeriod: "October 1 - April 1, 2026",
    website: "https://www.uva.nl",
    description: "Founded in 1632, one of Europe's largest research universities. Strong in social sciences, humanities, and communication. Located in vibrant Amsterdam.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€12,000-20,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Wageningen University & Research",
    country: "Netherlands",
    region: "Gelderland",
    city: "Wageningen",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Agriculture", "Food Science", "Life Sciences", "Environmental Sciences"],
    admissionPeriod: "October 1 - May 1, 2026",
    website: "https://www.wur.nl",
    description: "#1 worldwide for Agriculture & Forestry. World-leading research in food, health, and sustainability. Strong industry connections.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€19,200/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Leiden University",
    country: "Netherlands",
    region: "South Holland",
    city: "Leiden",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Humanities", "Law", "Social Sciences", "Sciences", "Medicine"],
    admissionPeriod: "October 1 - April 1, 2026",
    website: "https://www.universiteitleiden.nl",
    description: "Oldest university in the Netherlands (1575). Alma mater of Dutch royalty and Nobel laureates. Strong in humanities, law, and archaeology.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€13,000-18,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "University of Groningen",
    country: "Netherlands",
    region: "Groningen",
    city: "Groningen",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Sciences", "Economics", "Law", "Medicine", "Arts"],
    admissionPeriod: "October 1 - May 1, 2026",
    website: "https://www.rug.nl",
    description: "Top-100 university with 30,000 students. Known for energy research and healthy ageing. Located in the most affordable student city.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€11,500-16,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Utrecht University",
    country: "Netherlands",
    region: "Utrecht",
    city: "Utrecht",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Humanities", "Sciences", "Medicine", "Veterinary", "Law"],
    admissionPeriod: "October 1 - April 1, 2026",
    website: "https://www.uu.nl",
    description: "Largest university in Netherlands with widest range of English programs. Strong in geosciences, veterinary science, and public health.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€12,000-20,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Erasmus University Rotterdam",
    country: "Netherlands",
    region: "South Holland",
    city: "Rotterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Economics", "Medicine", "Social Sciences", "Law"],
    admissionPeriod: "October 1 - May 1, 2026",
    website: "https://www.eur.nl",
    description: "Named after Erasmus of Rotterdam. Rotterdam School of Management is top-ranked globally. Strong in economics, health policy, and urban studies.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€12,000-22,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Eindhoven University of Technology (TU/e)",
    country: "Netherlands",
    region: "North Brabant",
    city: "Eindhoven",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Engineering", "Technology", "Computer Science", "Design"],
    admissionPeriod: "October 1 - May 1, 2026",
    website: "https://www.tue.nl",
    description: "Leading technical university in the 'Brainport' tech region. Strong connections with Philips, ASML, and high-tech industry. Focus on innovation.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€15,000-18,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "University of Twente",
    country: "Netherlands",
    region: "Overijssel",
    city: "Enschede",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Technology", "Engineering", "Social Sciences", "Health"],
    admissionPeriod: "October 1 - May 1, 2026",
    website: "https://www.utwente.nl",
    description: "Entrepreneurial university with campus on 140 hectares. Known for nanotechnology, biomedical engineering, and tech startups. Affordable city location.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€12,750-17,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Radboud University",
    country: "Netherlands",
    region: "Gelderland",
    city: "Nijmegen",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Sciences", "Humanities", "Social Sciences", "Medicine", "Law"],
    admissionPeriod: "October 1 - May 1, 2026",
    website: "https://www.ru.nl",
    description: "Comprehensive research university focused on interdisciplinary research. Strong in cognitive neuroscience, molecular life sciences, and philosophy.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€11,500-16,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Tilburg University",
    country: "Netherlands",
    region: "North Brabant",
    city: "Tilburg",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Economics", "Law", "Social Sciences", "Humanities", "Theology"],
    admissionPeriod: "October 1 - June 1, 2026",
    website: "https://www.tilburguniversity.edu",
    description: "Specialized in social sciences, law, and economics. Top-ranked economics and law school. Known for research on society and behavior.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€14,000-18,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Maastricht University",
    country: "Netherlands",
    region: "Limburg",
    city: "Maastricht",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Law", "Medicine", "Psychology", "Arts"],
    admissionPeriod: "October 1 - June 1, 2026",
    website: "https://www.maastrichtuniversity.nl",
    description: "Most international university in Netherlands. Pioneer of Problem-Based Learning (PBL). Located in charming city near Belgium and Germany borders.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€11,500-32,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "VU Amsterdam (Vrije Universiteit)",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Sciences", "Medicine", "Business", "Humanities", "Law"],
    admissionPeriod: "October 1 - April 1, 2026",
    website: "https://vu.nl",
    description: "Research-intensive university with strong values focus. Known for earth sciences, neuroscience, and sustainability research. Modern campus in Zuidas.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€11,500-16,500/year",
    tuitionPeriod: "annual",
  },

  // Universities of Applied Sciences (HBO)
  {
    name: "Amsterdam University of Applied Sciences (HvA)",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Digital Media", "Health", "Technology", "Sports"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.amsterdamuas.com",
    description: "Largest university of applied sciences in Netherlands. Practice-oriented programs with strong industry connections in the capital city.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,500-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Rotterdam University of Applied Sciences",
    country: "Netherlands",
    region: "South Holland",
    city: "Rotterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Engineering", "Health", "Creative Industries"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.rotterdamuas.com",
    description: "Major applied sciences university in Europe's largest port city. Focus on urban innovation, logistics, and maritime industries.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "The Hague University of Applied Sciences",
    country: "Netherlands",
    region: "South Holland",
    city: "The Hague",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["International Studies", "Business", "Law", "Public Management"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.thehagueuniversity.com",
    description: "Located in the international city of peace and justice. Strong focus on international relations, European studies, and public administration.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,500-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Fontys University of Applied Sciences",
    country: "Netherlands",
    region: "North Brabant",
    city: "Eindhoven",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Engineering", "Business", "ICT", "Education", "Arts"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://fontys.edu",
    description: "One of the largest applied sciences universities with 200+ programs. Strong in technology and creative industries in the Brainport region.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,500-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "HAN University of Applied Sciences",
    country: "Netherlands",
    region: "Gelderland",
    city: "Arnhem",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Engineering", "Health", "Education", "Arts"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.han.nl",
    description: "Large university with campuses in Arnhem and Nijmegen. Known for automotive engineering, life sciences, and creative industries.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Saxion University of Applied Sciences",
    country: "Netherlands",
    region: "Overijssel",
    city: "Enschede",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Engineering", "Health", "Hospitality", "Creative"],
    admissionPeriod: "February 1 - July 1, 2026",
    website: "https://www.saxion.edu",
    description: "Three campuses in eastern Netherlands. Strong connections with German industry. Known for hospitality, mechatronics, and fashion programs.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,200-9,800/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Hanze University of Applied Sciences Groningen",
    country: "Netherlands",
    region: "Groningen",
    city: "Groningen",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Engineering", "Health", "Arts", "Energy"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.hanze.nl",
    description: "One of the oldest and largest applied sciences universities. Located in affordable, youthful Groningen. Focus on energy transition and healthy ageing.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Avans University of Applied Sciences",
    country: "Netherlands",
    region: "North Brabant",
    city: "Breda",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Technology", "Art & Design", "Health"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.avans.nl",
    description: "Well-ranked university with campuses in Breda, 's-Hertogenbosch, and Tilburg. Known for international business and game design programs.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Hogeschool Utrecht (HU)",
    country: "Netherlands",
    region: "Utrecht",
    city: "Utrecht",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Communication", "Health", "Education", "Technology"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.internationalhu.com",
    description: "Large university in the heart of Netherlands. Modern campus with excellent facilities. Strong focus on sustainability and innovation.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,500-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Inholland University of Applied Sciences",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Creative Industries", "Health", "Technology"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.inholland.nl",
    description: "Multiple campuses across Randstad region. Known for creative business, aviation, and media programs. Strong industry partnerships.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "NHL Stenden University of Applied Sciences",
    country: "Netherlands",
    region: "Friesland",
    city: "Leeuwarden",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Hospitality", "Tourism", "Business", "Education", "Media"],
    admissionPeriod: "February 1 - July 1, 2026",
    website: "https://www.nhlstenden.com",
    description: "International focus with Grand Tour concept (study at multiple locations). Renowned for hotel management and leisure & tourism programs.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,500-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Hotelschool The Hague",
    country: "Netherlands",
    region: "South Holland",
    city: "The Hague",
    type: "Public",
    languages: ["English"],
    domains: ["Hospitality Management", "Hotel Management", "Tourism"],
    admissionPeriod: "Rolling - until July 1, 2026",
    website: "https://www.hotelschool.nl",
    description: "World's leading hospitality management school. Unique teaching hotel concept. 100% English programs with guaranteed internships worldwide.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€14,850/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Zuyd University of Applied Sciences",
    country: "Netherlands",
    region: "Limburg",
    city: "Maastricht",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Arts", "Health", "Technology", "Hotel Management"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.zuyd.nl",
    description: "Located in the Euroregion near Belgium and Germany. Known for fine arts, hotel management, and international business. Affordable living costs.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Windesheim University of Applied Sciences",
    country: "Netherlands",
    region: "Overijssel",
    city: "Zwolle",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Business", "Engineering", "Health", "Education", "Media"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.windesheiminternational.nl",
    description: "Top-ranked applied sciences university in student satisfaction. Small-scale education in historic Hanseatic city. Strong coaching culture.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "HZ University of Applied Sciences",
    country: "Netherlands",
    region: "Zeeland",
    city: "Vlissingen",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Water Technology", "Delta Technology", "Business", "Health"],
    admissionPeriod: "February 1 - July 1, 2026",
    website: "https://hz.nl",
    description: "Specialized in water, energy, and delta technology. Small-scale university with personal attention. Very affordable coastal location.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€7,800-9,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Hogeschool Leiden",
    country: "Netherlands",
    region: "South Holland",
    city: "Leiden",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Health", "Business", "Education", "Technology", "Social Work"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.hsleiden.nl",
    description: "Located in historic university city. Focus on small-scale, personal education. Strong connections with local businesses and healthcare sector.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-9,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "HAS University of Applied Sciences",
    country: "Netherlands",
    region: "North Brabant",
    city: "'s-Hertogenbosch",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Agriculture", "Food Technology", "Agribusiness", "Environment"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.hasuniversity.nl",
    description: "Specialized in food, agriculture, and environment. Strong industry connections with Dutch agrifood sector. Practical, hands-on education.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,000-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Aeres University of Applied Sciences",
    country: "Netherlands",
    region: "Flevoland",
    city: "Almere",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Agriculture", "Animal Science", "Food", "Environment", "Education"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.aeresuas.nl",
    description: "Focus on green education: agriculture, food, and living environment. Campuses with working farms and labs. International food business programs.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,500-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Breda University of Applied Sciences",
    country: "Netherlands",
    region: "North Brabant",
    city: "Breda",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Game Development", "Tourism", "Logistics", "Media", "Built Environment"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.buas.nl",
    description: "Known for game development (IGAD) and tourism programs. Creative and innovative atmosphere. Strong focus on experiential learning.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,250-11,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Van Hall Larenstein University of Applied Sciences",
    country: "Netherlands",
    region: "Gelderland",
    city: "Velp",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Animal Management", "Food Technology", "Environmental Science", "Agriculture"],
    admissionPeriod: "February 1 - June 1, 2026",
    website: "https://www.vhluas.com",
    description: "Part of Wageningen University family. Specialized in applied life sciences, animal care, and sustainable development. Beautiful green campuses.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,000-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Wittenborg University of Applied Sciences",
    country: "Netherlands",
    region: "Gelderland",
    city: "Apeldoorn",
    type: "Private",
    languages: ["English"],
    domains: ["Business", "Hospitality", "Arts", "Health", "Technology"],
    admissionPeriod: "Rolling - multiple intakes 2026",
    website: "https://www.wittenborg.eu",
    description: "100% English instruction with diverse international student body. Multiple entry points throughout the year. Focus on entrepreneurship.",
    englishPrograms: true,
    tuitionFeeEU: "€9,500/year",
    tuitionFeeNonEU: "€9,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Webster University Netherlands",
    country: "Netherlands",
    region: "South Holland",
    city: "Leiden",
    type: "Private",
    languages: ["English"],
    domains: ["Business", "Media Communications", "International Relations", "Psychology"],
    admissionPeriod: "Rolling - until August 2026",
    website: "https://www.webster.nl",
    description: "American-style university with global network. Small class sizes and personal attention. Located in historic Leiden city center.",
    englishPrograms: true,
    tuitionFeeEU: "€11,500/year",
    tuitionFeeNonEU: "€11,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Nyenrode Business University",
    country: "Netherlands",
    region: "Utrecht",
    city: "Breukelen",
    type: "Private",
    languages: ["English", "Dutch"],
    domains: ["Business", "Management", "Accounting", "Entrepreneurship"],
    admissionPeriod: "Rolling - until July 2026",
    website: "https://www.nyenrode.nl",
    description: "Elite business school on historic castle estate. Strong corporate connections and network. Focus on leadership and entrepreneurship.",
    englishPrograms: true,
    tuitionFeeEU: "€15,000-25,000/year",
    tuitionFeeNonEU: "€15,000-25,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Amsterdam Fashion Institute (AMFI)",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Fashion Design", "Fashion Management", "Textile", "Branding"],
    admissionPeriod: "January 15 - May 1, 2026",
    website: "https://amfi.nl",
    description: "Part of Amsterdam University of Applied Sciences. One of Europe's leading fashion schools. Strong focus on sustainability and innovation.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,500-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Design Academy Eindhoven",
    country: "Netherlands",
    region: "North Brabant",
    city: "Eindhoven",
    type: "Public",
    languages: ["English"],
    domains: ["Design", "Art", "Creative Industries"],
    admissionPeriod: "January 1 - March 1, 2026",
    website: "https://www.designacademy.nl",
    description: "World-renowned design school ranked #1 in Netherlands. Focus on critical and social design. Strong alumni network in design industry.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€15,600/year",
    tuitionPeriod: "annual",
  },
  {
    name: "ArtEZ University of the Arts",
    country: "Netherlands",
    region: "Gelderland",
    city: "Arnhem",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Fine Arts", "Design", "Fashion", "Music", "Theatre"],
    admissionPeriod: "January 1 - April 1, 2026",
    website: "https://www.artez.nl",
    description: "One of the largest art universities in Netherlands. Campuses in Arnhem, Enschede, and Zwolle. Known for fashion, fine arts, and creative writing.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,000-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Willem de Kooning Academy",
    country: "Netherlands",
    region: "South Holland",
    city: "Rotterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Fine Arts", "Design", "Media", "Advertising", "Illustration"],
    admissionPeriod: "January 1 - April 1, 2026",
    website: "https://www.wdka.nl",
    description: "Part of Rotterdam University of Applied Sciences. Named after famous Dutch artist. Strong focus on contemporary art and social design.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€8,000-10,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Royal Academy of Art (KABK)",
    country: "Netherlands",
    region: "South Holland",
    city: "The Hague",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Fine Arts", "Design", "Photography", "Graphic Design"],
    admissionPeriod: "January 1 - April 1, 2026",
    website: "https://www.kabk.nl",
    description: "One of the oldest art academies in Europe (1682). Focus on visual arts and design. Located near Dutch art museums and galleries.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€10,000-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Gerrit Rietveld Academie",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Fine Arts", "Design", "Architecture", "Photography"],
    admissionPeriod: "January 1 - April 1, 2026",
    website: "https://rfrietveldacademie.nl",
    description: "Named after famous Dutch architect. Renowned for experimental and conceptual approach to art education. Located in creative Amsterdam district.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,500-11,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Codarts Rotterdam",
    country: "Netherlands",
    region: "South Holland",
    city: "Rotterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Music", "Dance", "Circus Arts", "Performing Arts"],
    admissionPeriod: "October 1 - April 1, 2026",
    website: "https://www.codarts.nl",
    description: "Leading performing arts university. Programs in classical music, jazz, dance, and circus. State-of-the-art facilities in Rotterdam creative district.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€10,000-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Conservatorium van Amsterdam",
    country: "Netherlands",
    region: "North Holland",
    city: "Amsterdam",
    type: "Public",
    languages: ["English", "Dutch"],
    domains: ["Music", "Opera", "Conducting", "Music Education"],
    admissionPeriod: "October 1 - December 1, 2025",
    website: "https://www.conservatoriumvanamsterdam.nl",
    description: "One of Europe's largest and most diverse conservatories. World-class faculty and facilities. Part of Amsterdam University of the Arts.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€10,000-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Stenden Hotel Management School",
    country: "Netherlands",
    region: "Friesland",
    city: "Leeuwarden",
    type: "Public",
    languages: ["English"],
    domains: ["Hotel Management", "Hospitality", "Tourism", "Event Management"],
    admissionPeriod: "February 1 - July 1, 2026",
    website: "https://www.nhlstenden.com/en/study-programmes/international-hotel-management",
    description: "Part of NHL Stenden. Operates real 4-star training hotel. International focus with campuses in Bali, South Africa, Qatar, and Thailand.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€9,500-12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "TIAS Business School",
    country: "Netherlands",
    region: "North Brabant",
    city: "Tilburg",
    type: "Private",
    languages: ["English"],
    domains: ["Business", "MBA", "Executive Education", "Finance"],
    admissionPeriod: "Rolling - until August 2026",
    website: "https://www.tias.edu",
    description: "Top-ranked business school affiliated with Tilburg University. Focus on responsible leadership and societal impact. Executive MBA programs.",
    englishPrograms: true,
    tuitionFeeEU: "€18,000-45,000/year",
    tuitionFeeNonEU: "€18,000-45,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Institute for Housing and Urban Development Studies (IHS)",
    country: "Netherlands",
    region: "South Holland",
    city: "Rotterdam",
    type: "Public",
    languages: ["English"],
    domains: ["Urban Development", "Housing", "Urban Management", "Planning"],
    admissionPeriod: "Rolling - until June 2026",
    website: "https://www.ihs.nl",
    description: "Part of Erasmus University. Specialized in urban studies and housing. Focus on developing countries and sustainable cities.",
    englishPrograms: true,
    tuitionFeeEU: "€2,530/year",
    tuitionFeeNonEU: "€15,000-18,000/year",
    tuitionPeriod: "annual",
  },
];
