import type { InsertUniversity } from "@shared/schema";

export const finnishUniversities: InsertUniversity[] = [
  {
    name: "University of Helsinki",
    country: "Finland",
    region: "Uusimaa",
    city: "Helsinki",
    type: "Public",
    languages: ["Finnish", "Swedish", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://helsinki.fi",
    description: "Finland's oldest and largest university, founded in 1640. A leading research university and member of the League of European Research Universities (LERU).",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€13,000 - €18,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 31000,
    globalRank: 115,
  },
  {
    name: "Aalto University",
    country: "Finland",
    region: "Uusimaa",
    city: "Espoo",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Arts & Design", "Sciences"],
    admissionPeriod: "December - January",
    website: "https://aalto.fi",
    description: "A multidisciplinary university formed by merging Helsinki University of Technology, Helsinki School of Economics, and University of Art and Design. Known for innovation and design.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€12,000 - €15,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 20000,
    globalRank: 116,
  },
  {
    name: "University of Turku",
    country: "Finland",
    region: "Southwest Finland",
    city: "Turku",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Medicine & Health", "Sciences", "Social Sciences & Humanities", "Law & Politics", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://utu.fi",
    description: "The second largest university in Finland, known for strong research in medicine, education, and humanities. Located in Finland's former capital.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€10,000 - €16,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 22000,
    globalRank: 287,
  },
  {
    name: "University of Oulu",
    country: "Finland",
    region: "North Ostrobothnia",
    city: "Oulu",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Sciences", "Medicine & Health", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://oulu.fi",
    description: "A leading research university in Northern Finland, known for wireless communications, biotechnology, and Arctic research.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€10,000 - €15,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 16000,
    globalRank: 350,
  },
  {
    name: "Tampere University",
    country: "Finland",
    region: "Pirkanmaa",
    city: "Tampere",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Medicine & Health", "Social Sciences & Humanities", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://tuni.fi",
    description: "One of Finland's largest universities, formed by the merger of University of Tampere and Tampere University of Technology. Strong in technology and health sciences.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€10,000 - €14,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 21000,
    globalRank: 401,
  },
  {
    name: "University of Jyväskylä",
    country: "Finland",
    region: "Central Finland",
    city: "Jyväskylä",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Social Sciences & Humanities", "Sciences", "Sports & Tourism", "Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://jyu.fi",
    description: "Known as the university of human sciences, with excellent programs in education, psychology, and sports sciences.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€10,000 - €14,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 14000,
    globalRank: 451,
  },
  {
    name: "University of Eastern Finland",
    country: "Finland",
    region: "North Savo",
    city: "Kuopio",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Sciences", "Medicine & Health", "Social Sciences & Humanities", "Agriculture & Environment"],
    admissionPeriod: "January - March",
    website: "https://uef.fi",
    description: "A multidisciplinary research university with campuses in Kuopio and Joensuu. Strong in forestry, pharmacy, and health sciences.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€8,000 - €15,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 15000,
    globalRank: 501,
  },
  {
    name: "Åbo Akademi University",
    country: "Finland",
    region: "Southwest Finland",
    city: "Turku",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Sciences", "Social Sciences & Humanities", "Engineering & Technology", "Medicine & Health"],
    admissionPeriod: "January - March",
    website: "https://abo.fi",
    description: "Finland's only Swedish-language multidisciplinary university. Offers unique programs in minority studies and combustion chemistry.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€8,000 - €12,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 5500,
    globalRank: 550,
  },
  {
    name: "LUT University",
    country: "Finland",
    region: "South Karelia",
    city: "Lappeenranta",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Sciences"],
    admissionPeriod: "January - March",
    website: "https://lut.fi",
    description: "A pioneering science university combining technology and business. Leader in clean energy research and sustainability.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€10,000 - €14,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 6000,
    globalRank: 600,
  },
  {
    name: "University of Vaasa",
    country: "Finland",
    region: "Ostrobothnia",
    city: "Vaasa",
    type: "Public",
    languages: ["Finnish", "Swedish", "English"],
    domains: ["Business & Economics", "Engineering & Technology", "Social Sciences & Humanities"],
    admissionPeriod: "January - March",
    website: "https://uwasa.fi",
    description: "A bilingual university known for energy business, finance, and management. Located in Finland's energy capital.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€9,000 - €12,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 5000,
    globalRank: 700,
  },
  {
    name: "University of Lapland",
    country: "Finland",
    region: "Lapland",
    city: "Rovaniemi",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Social Sciences & Humanities", "Arts & Design", "Law & Politics", "Sports & Tourism"],
    admissionPeriod: "January - March",
    website: "https://ulapland.fi",
    description: "The northernmost university in the EU. Specializes in Arctic research, tourism, and indigenous studies.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€8,000 - €12,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 4500,
    globalRank: 800,
  },
  {
    name: "Hanken School of Economics",
    country: "Finland",
    region: "Uusimaa",
    city: "Helsinki",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "January - March",
    website: "https://hanken.fi",
    description: "One of the oldest business schools in the Nordic countries with triple accreditation (AACSB, EQUIS, AMBA).",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€12,500/year",
    tuitionPeriod: "per year",
    totalEnrollment: 2500,
    globalRank: null,
  },
  {
    name: "Metropolia University of Applied Sciences",
    country: "Finland",
    region: "Uusimaa",
    city: "Helsinki",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Medicine & Health", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://metropolia.fi",
    description: "Finland's largest university of applied sciences, offering practical education with strong industry connections.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€8,000 - €12,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 16000,
    globalRank: null,
  },
  {
    name: "Haaga-Helia University of Applied Sciences",
    country: "Finland",
    region: "Uusimaa",
    city: "Helsinki",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Business & Economics", "Sports & Tourism", "Media & Communication"],
    admissionPeriod: "January - March",
    website: "https://haaga-helia.fi",
    description: "One of Finland's leading business-focused universities of applied sciences with strong international connections.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€9,000 - €11,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 10000,
    globalRank: null,
  },
  {
    name: "Laurea University of Applied Sciences",
    country: "Finland",
    region: "Uusimaa",
    city: "Vantaa",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Medicine & Health"],
    admissionPeriod: "January - March",
    website: "https://laurea.fi",
    description: "Known for its innovative Learning by Developing (LbD) model and strong focus on service innovation.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€8,500 - €10,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 8000,
    globalRank: null,
  },
  {
    name: "Tampere University of Applied Sciences",
    country: "Finland",
    region: "Pirkanmaa",
    city: "Tampere",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Arts & Design", "Medicine & Health"],
    admissionPeriod: "January - March",
    website: "https://tuni.fi/tamk",
    description: "A multidisciplinary UAS offering practical education in collaboration with Tampere University.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€9,000 - €11,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 10000,
    globalRank: null,
  },
  {
    name: "Oulu University of Applied Sciences",
    country: "Finland",
    region: "North Ostrobothnia",
    city: "Oulu",
    type: "Public",
    languages: ["Finnish", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Medicine & Health"],
    admissionPeriod: "January - March",
    website: "https://oamk.fi",
    description: "Northern Finland's largest UAS with strong connections to technology industry and Arctic expertise.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€8,000 - €10,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
    globalRank: null,
  },
  {
    name: "University of the Arts Helsinki",
    country: "Finland",
    region: "Uusimaa",
    city: "Helsinki",
    type: "Public",
    languages: ["Finnish", "Swedish", "English"],
    domains: ["Arts & Design", "Media & Communication"],
    admissionPeriod: "January - February",
    website: "https://uniarts.fi",
    description: "Finland's largest arts university, formed by merging Academy of Fine Arts, Sibelius Academy, and Theatre Academy.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "€5,000 - €15,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 2000,
    globalRank: null,
  },
];
