import type { InsertUniversity } from "@shared/schema";

export const frenchUniversities: InsertUniversity[] = [
  // Grandes Écoles and Elite Institutions
  {
    name: "Sorbonne University",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Humanities", "Medicine", "Law", "Engineering"],
    admissionPeriod: "January - March 2026",
    website: "https://www.sorbonne-universite.fr",
    description: "One of the world's most prestigious universities, formed from the merger of Paris-Sorbonne and Pierre and Marie Curie. Excellence in sciences and humanities.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Paris Sciences et Lettres (PSL)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Arts", "Humanities", "Engineering", "Business"],
    admissionPeriod: "January - April 2026",
    website: "https://psl.eu",
    description: "Top-ranked French university (#24 globally). Federation of elite institutions including ENS, Dauphine, Mines Paris, and ESPCI.",
    englishPrograms: true,
    tuitionFeeEU: "€243-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "École Polytechnique",
    country: "France",
    region: "Île-de-France",
    city: "Palaiseau",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Sciences", "Mathematics", "Physics", "Computer Science"],
    admissionPeriod: "November - January 2026",
    website: "https://www.polytechnique.edu",
    description: "France's most prestigious engineering school. Known for excellence in mathematics and sciences. Strong ties to industry and research.",
    englishPrograms: true,
    tuitionFeeEU: "€12,000/year",
    tuitionFeeNonEU: "€15,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Sciences Po Paris",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Political Science", "International Relations", "Economics", "Law", "Public Policy"],
    admissionPeriod: "October - February 2026",
    website: "https://www.sciencespo.fr",
    description: "World-leading institution for political science and international affairs. Educated many French presidents and global leaders.",
    englishPrograms: true,
    tuitionFeeEU: "€0-14,500/year (income-based)",
    tuitionFeeNonEU: "€14,500-24,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "HEC Paris",
    country: "France",
    region: "Île-de-France",
    city: "Jouy-en-Josas",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Management", "Finance", "Marketing", "Entrepreneurship"],
    admissionPeriod: "Rolling",
    website: "https://www.hec.edu",
    description: "#1 Business school in Europe. World-renowned MBA program. Strong network and career services.",
    englishPrograms: true,
    tuitionFeeEU: "€45,500-84,000/program",
    tuitionFeeNonEU: "€45,500-84,000/program",
    tuitionPeriod: "program",
  },
  {
    name: "INSEAD",
    country: "France",
    region: "Île-de-France",
    city: "Fontainebleau",
    type: "Private",
    languages: ["English"],
    domains: ["Business", "MBA", "Executive Education", "Finance"],
    admissionPeriod: "Rolling (4 intakes)",
    website: "https://www.insead.edu",
    description: "Top global business school with campuses in France, Singapore, and Abu Dhabi. #1 MBA worldwide (FT ranking).",
    englishPrograms: true,
    tuitionFeeEU: "€95,000/program",
    tuitionFeeNonEU: "€95,000/program",
    tuitionPeriod: "program",
  },
  {
    name: "École Normale Supérieure (ENS Paris)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Humanities", "Social Sciences", "Mathematics", "Philosophy"],
    admissionPeriod: "October - January 2026",
    website: "https://www.ens.psl.eu",
    description: "France's most selective institution for training researchers and academics. Has produced 14 Nobel laureates and 11 Fields Medalists.",
    englishPrograms: true,
    tuitionFeeEU: "€380/year",
    tuitionFeeNonEU: "€2,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "CentraleSupélec",
    country: "France",
    region: "Île-de-France",
    city: "Gif-sur-Yvette",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Computer Science", "Applied Mathematics", "Energy"],
    admissionPeriod: "December - March 2026",
    website: "https://www.centralesupelec.fr",
    description: "Top French engineering school formed from merger of École Centrale Paris and Supélec. Strong industry partnerships.",
    englishPrograms: true,
    tuitionFeeEU: "€3,000/year",
    tuitionFeeNonEU: "€12,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "ESSEC Business School",
    country: "France",
    region: "Île-de-France",
    city: "Cergy",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Management", "Finance", "Luxury", "Hospitality"],
    admissionPeriod: "Rolling",
    website: "https://www.essec.edu",
    description: "Top 5 European business school. Pioneer in hospitality management and luxury brand education.",
    englishPrograms: true,
    tuitionFeeEU: "€17,500-52,000/year",
    tuitionFeeNonEU: "€17,500-52,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "ESCP Business School",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Management", "Finance", "Marketing"],
    admissionPeriod: "Rolling",
    website: "https://escp.eu",
    description: "World's oldest business school (1819). Six European campuses. Strong international focus.",
    englishPrograms: true,
    tuitionFeeEU: "€17,800-35,000/year",
    tuitionFeeNonEU: "€17,800-35,000/year",
    tuitionPeriod: "annual",
  },
  // Major Public Universities
  {
    name: "Université Paris-Saclay",
    country: "France",
    region: "Île-de-France",
    city: "Gif-sur-Yvette",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering", "Medicine", "Economics", "Law"],
    admissionPeriod: "January - May 2026",
    website: "https://www.universite-paris-saclay.fr",
    description: "Ranked #15 globally. France's leading research university. Combines universities and grandes écoles on Europe's largest science cluster.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Paris (Paris Cité)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Medicine", "Sciences", "Humanities", "Law", "Psychology"],
    admissionPeriod: "January - April 2026",
    website: "https://u-paris.fr",
    description: "Major research university in Paris. Strong in health sciences and interdisciplinary research. One of France's largest universities.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Aix-Marseille Université",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Marseille",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Law", "Arts", "Economics"],
    admissionPeriod: "January - May 2026",
    website: "https://www.univ-amu.fr",
    description: "Largest French-speaking university by student enrollment. Located in sunny Mediterranean region. Strong research output.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Strasbourg",
    country: "France",
    region: "Grand Est",
    city: "Strasbourg",
    type: "Public",
    languages: ["French", "English", "German"],
    domains: ["Sciences", "Law", "Medicine", "Humanities", "Political Science"],
    admissionPeriod: "January - April 2026",
    website: "https://www.unistra.fr",
    description: "Located in European capital. Strong in law and political science. 3 Nobel Prize winners. Franco-German programs available.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Bordeaux",
    country: "France",
    region: "Nouvelle-Aquitaine",
    city: "Bordeaux",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Law", "Economics", "Oenology"],
    admissionPeriod: "January - April 2026",
    website: "https://www.u-bordeaux.fr",
    description: "Major research university in southwest France. World leader in wine science and oenology. Beautiful historic campus.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université Grenoble Alpes",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Grenoble",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering", "Medicine", "Humanities", "Sports"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-grenoble-alpes.fr",
    description: "Top research university in the Alps. Strong in physics, nanotechnology, and winter sports science. Beautiful mountain setting.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université Claude Bernard Lyon 1",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Lyon",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Engineering", "Sports"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-lyon1.fr",
    description: "Leading science and medical university in Lyon. Strong research in health and technology. Part of Lyon university system.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Montpellier",
    country: "France",
    region: "Occitanie",
    city: "Montpellier",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Law", "Economics", "Agriculture"],
    admissionPeriod: "January - April 2026",
    website: "https://www.umontpellier.fr",
    description: "One of the world's oldest universities (founded 1220). Excellence in medicine, law, and environmental sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Lille",
    country: "France",
    region: "Hauts-de-France",
    city: "Lille",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Humanities", "Medicine", "Law", "Engineering"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-lille.fr",
    description: "Major university in northern France. Strong in sciences and humanities. Close to Belgium, London, and Paris.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Nantes",
    country: "France",
    region: "Pays de la Loire",
    city: "Nantes",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Engineering", "Humanities", "Law"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-nantes.fr",
    description: "Dynamic university in France's 6th largest city. Known for quality of life and innovative programs.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Toulouse",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Aerospace", "Engineering", "Medicine", "Law"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-toulouse.fr",
    description: "Major research hub in aerospace capital of Europe. Strong ties to Airbus and CNES. Historic pink city setting.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Rennes",
    country: "France",
    region: "Brittany",
    city: "Rennes",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Law", "Medicine", "Economics", "Philosophy"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-rennes.fr",
    description: "Leading university in Brittany. Strong in digital technology and health. Vibrant student city.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Nice Sophia Antipolis (Côte d'Azur)",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Nice",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Law", "Economics", "Tourism"],
    admissionPeriod: "January - April 2026",
    website: "https://univ-cotedazur.fr",
    description: "Located in French Riviera. Access to Sophia Antipolis technology park. Mediterranean climate and beach access.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  // Engineering Schools
  {
    name: "École des Ponts ParisTech",
    country: "France",
    region: "Île-de-France",
    city: "Champs-sur-Marne",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Urban Planning", "Transport", "Environment"],
    admissionPeriod: "December - March 2026",
    website: "https://www.ecoledesponts.fr",
    description: "France's oldest engineering school (1747). World leader in civil engineering, urban planning, and sustainable development.",
    englishPrograms: true,
    tuitionFeeEU: "€2,500/year",
    tuitionFeeNonEU: "€8,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Mines Paris - PSL",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Energy", "Materials", "Robotics", "AI"],
    admissionPeriod: "December - February 2026",
    website: "https://www.minesparis.psl.eu",
    description: "Elite engineering school founded in 1783. Strong industry ties. Excellence in energy and materials science.",
    englishPrograms: true,
    tuitionFeeEU: "€2,500/year",
    tuitionFeeNonEU: "€8,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Télécom Paris",
    country: "France",
    region: "Île-de-France",
    city: "Palaiseau",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Computer Science", "Telecommunications", "AI", "Data Science"],
    admissionPeriod: "December - March 2026",
    website: "https://www.telecom-paris.fr",
    description: "France's top digital engineering school. Strong in AI, cybersecurity, and data science. Member of Institut Polytechnique de Paris.",
    englishPrograms: true,
    tuitionFeeEU: "€2,650/year",
    tuitionFeeNonEU: "€7,650/year",
    tuitionPeriod: "annual",
  },
  {
    name: "INSA Lyon",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Lyon",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Computer Science", "Biotechnology", "Energy"],
    admissionPeriod: "January - March 2026",
    website: "https://www.insa-lyon.fr",
    description: "Largest INSA school. 5-year integrated engineering program. Strong industry connections. Diverse and international.",
    englishPrograms: true,
    tuitionFeeEU: "€601/year",
    tuitionFeeNonEU: "€3,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "INSA Toulouse",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Aerospace", "Computer Science", "Chemistry"],
    admissionPeriod: "January - March 2026",
    website: "https://www.insa-toulouse.fr",
    description: "Leading engineering school in aerospace hub. Strong ties to Airbus and space industry.",
    englishPrograms: true,
    tuitionFeeEU: "€601/year",
    tuitionFeeNonEU: "€3,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Grenoble INP",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Grenoble",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Electronics", "Computer Science", "Energy"],
    admissionPeriod: "January - March 2026",
    website: "https://www.grenoble-inp.fr",
    description: "Group of 8 engineering schools. Excellence in microelectronics and sustainable energy. Mountain innovation hub.",
    englishPrograms: true,
    tuitionFeeEU: "€601/year",
    tuitionFeeNonEU: "€3,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Arts et Métiers ParisTech",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering", "Manufacturing", "Mechanical Engineering", "Design"],
    admissionPeriod: "December - March 2026",
    website: "https://artsetmetiers.fr",
    description: "Prestigious engineering school for industry. 8 campuses across France. Strong manufacturing and mechanical focus.",
    englishPrograms: true,
    tuitionFeeEU: "€601/year",
    tuitionFeeNonEU: "€3,500/year",
    tuitionPeriod: "annual",
  },
  {
    name: "ISAE-SUPAERO",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Aerospace", "Engineering", "Space", "Defense"],
    admissionPeriod: "November - February 2026",
    website: "https://www.isae-supaero.fr",
    description: "World's first aerospace engineering school. Train astronauts and aerospace leaders. Located in aerospace capital.",
    englishPrograms: true,
    tuitionFeeEU: "€2,800/year",
    tuitionFeeNonEU: "€8,000/year",
    tuitionPeriod: "annual",
  },
  // Business Schools
  {
    name: "EDHEC Business School",
    country: "France",
    region: "Hauts-de-France",
    city: "Lille",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Finance", "Marketing", "Data Analytics"],
    admissionPeriod: "Rolling",
    website: "https://www.edhec.edu",
    description: "Top 10 European business school. Campuses in Lille, Nice, Paris, London, and Singapore. Strong in finance.",
    englishPrograms: true,
    tuitionFeeEU: "€17,000-45,000/year",
    tuitionFeeNonEU: "€17,000-45,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "EM Lyon Business School",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Lyon",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Entrepreneurship", "Digital", "Management"],
    admissionPeriod: "Rolling",
    website: "https://em-lyon.com",
    description: "Pioneer in entrepreneurship education. Strong startup ecosystem. Campuses in Lyon, Paris, and Shanghai.",
    englishPrograms: true,
    tuitionFeeEU: "€18,000-42,000/year",
    tuitionFeeNonEU: "€18,000-42,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "NEOMA Business School",
    country: "France",
    region: "Grand Est",
    city: "Reims",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Marketing", "Wine & Spirits", "Luxury"],
    admissionPeriod: "Rolling",
    website: "https://neoma-bs.com",
    description: "Triple-accredited business school. Unique programs in champagne industry. Campuses in Reims, Rouen, and Paris.",
    englishPrograms: true,
    tuitionFeeEU: "€14,500-38,000/year",
    tuitionFeeNonEU: "€14,500-38,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "SKEMA Business School",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Nice",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "AI", "Sustainability", "Finance"],
    admissionPeriod: "Rolling",
    website: "https://www.skema.edu",
    description: "Global business school with 7 campuses worldwide. Strong focus on digital transformation and sustainability.",
    englishPrograms: true,
    tuitionFeeEU: "€13,000-35,000/year",
    tuitionFeeNonEU: "€13,000-35,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Audencia Business School",
    country: "France",
    region: "Pays de la Loire",
    city: "Nantes",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "CSR", "Management", "Finance"],
    admissionPeriod: "Rolling",
    website: "https://www.audencia.com",
    description: "Pioneer in CSR and responsible management education. Historic Nantes location. Strong ethics focus.",
    englishPrograms: true,
    tuitionFeeEU: "€14,500-36,000/year",
    tuitionFeeNonEU: "€14,500-36,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Toulouse Business School",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Aerospace Management", "Marketing", "Finance"],
    admissionPeriod: "Rolling",
    website: "https://www.tbs-education.com",
    description: "Strong aerospace business programs. Located in Airbus headquarters city. Growing international presence.",
    englishPrograms: true,
    tuitionFeeEU: "€12,000-32,000/year",
    tuitionFeeNonEU: "€12,000-32,000/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Kedge Business School",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Marseille",
    type: "Private",
    languages: ["English", "French"],
    domains: ["Business", "Maritime", "Supply Chain", "Wine & Spirits"],
    admissionPeriod: "Rolling",
    website: "https://kedge.edu",
    description: "France's largest business school by enrollment. Unique maritime and wine programs. Mediterranean location.",
    englishPrograms: true,
    tuitionFeeEU: "€12,500-33,000/year",
    tuitionFeeNonEU: "€12,500-33,000/year",
    tuitionPeriod: "annual",
  },
  // Art and Design Schools
  {
    name: "École des Beaux-Arts de Paris",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French"],
    domains: ["Fine Arts", "Sculpture", "Painting", "Video Art"],
    admissionPeriod: "January - March 2026",
    website: "https://www.beauxartsparis.fr",
    description: "France's most prestigious fine arts school. Historic institution that trained Delacroix, Renoir, and Monet.",
    englishPrograms: false,
    tuitionFeeEU: "€438/year",
    tuitionFeeNonEU: "€438/year",
    tuitionPeriod: "annual",
  },
  {
    name: "ENSAD (Arts Décoratifs)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Design", "Animation", "Fashion", "Interior Design", "Graphic Design"],
    admissionPeriod: "January - March 2026",
    website: "https://www.ensad.fr",
    description: "Top French design school. Produces world-class designers in fashion, animation, and product design.",
    englishPrograms: true,
    tuitionFeeEU: "€538/year",
    tuitionFeeNonEU: "€538/year",
    tuitionPeriod: "annual",
  },
  {
    name: "École Boulle",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French"],
    domains: ["Design", "Furniture", "Interior Architecture", "Crafts"],
    admissionPeriod: "January - April 2026",
    website: "https://www.ecole-boulle.org",
    description: "World-renowned for furniture design and luxury craftsmanship. Trains artisans for haute couture and luxury goods.",
    englishPrograms: false,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "Free",
    tuitionPeriod: "annual",
  },
  // Regional Universities
  {
    name: "Université de Lorraine",
    country: "France",
    region: "Grand Est",
    city: "Nancy",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering", "Medicine", "Humanities"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-lorraine.fr",
    description: "Major research university in eastern France. Strong in materials science and engineering. Beautiful Art Nouveau city.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Bourgogne",
    country: "France",
    region: "Bourgogne-Franche-Comté",
    city: "Dijon",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Law", "Wine Sciences", "Gastronomy"],
    admissionPeriod: "January - April 2026",
    website: "https://www.u-bourgogne.fr",
    description: "Located in wine capital. Unique programs in oenology and gastronomy. Historic Burgundy region.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Rouen Normandie",
    country: "France",
    region: "Normandy",
    city: "Rouen",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Humanities", "Law"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-rouen.fr",
    description: "Major university in Normandy. Strong research in chemistry and biotechnology. Historic city with Joan of Arc heritage.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Caen Normandie",
    country: "France",
    region: "Normandy",
    city: "Caen",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Humanities", "Medicine", "Law"],
    admissionPeriod: "January - April 2026",
    website: "https://www.unicaen.fr",
    description: "Historic Norman university rebuilt after WWII. Strong humanities programs. Close to D-Day beaches.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Poitiers",
    country: "France",
    region: "Nouvelle-Aquitaine",
    city: "Poitiers",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Law", "Humanities", "Sports"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-poitiers.fr",
    description: "One of France's oldest universities (1431). Strong in paleontology and medieval studies. Affordable student city.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université Clermont Auvergne",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Clermont-Ferrand",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Engineering", "Humanities"],
    admissionPeriod: "January - April 2026",
    website: "https://www.uca.fr",
    description: "Major university in volcanic Auvergne region. Strong in geology and sports medicine. Michelin headquarters city.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Perpignan",
    country: "France",
    region: "Occitanie",
    city: "Perpignan",
    type: "Public",
    languages: ["French", "English", "Catalan"],
    domains: ["Sciences", "Tourism", "Law", "Environment"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-perp.fr",
    description: "Mediterranean university near Spanish border. Unique Catalan studies. Sunny climate and beach access.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Bretagne Occidentale",
    country: "France",
    region: "Brittany",
    city: "Brest",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Marine Sciences", "Medicine", "Sciences", "Law"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-brest.fr",
    description: "Leading marine sciences research. Located in major naval port. Strong oceanography programs.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
  {
    name: "Université de Tours",
    country: "France",
    region: "Centre-Val de Loire",
    city: "Tours",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine", "Humanities", "Languages"],
    admissionPeriod: "January - April 2026",
    website: "https://www.univ-tours.fr",
    description: "Located in Loire Valley UNESCO region. Renowned French language programs for international students.",
    englishPrograms: true,
    tuitionFeeEU: "€170-380/year",
    tuitionFeeNonEU: "€2,770-3,770/year",
    tuitionPeriod: "annual",
  },
];
