export const germanUniversities = [
  // BADEN-WÜRTTEMBERG
  {
    name: 'Universität Heidelberg',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Heidelberg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Science', 'Humanities', 'Physics'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-heidelberg.de',
    description: 'Germany\'s oldest university (founded 1386) and one of Europe\'s leading research institutions.',
    englishPrograms: true,
  },
  {
    name: 'Karlsruher Institut für Technologie (KIT)',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Karlsruhe',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Physics', 'Chemistry', 'Economics'],
    admissionPeriod: 'April / October',
    website: 'https://www.kit.edu',
    description: 'One of the largest and most prestigious German technical universities, combining tradition with cutting-edge research.',
    englishPrograms: true,
  },
  {
    name: 'Universität Stuttgart',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Stuttgart',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Architecture', 'Computer Science', 'Aerospace'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-stuttgart.de',
    description: 'A leading technical university known for automotive engineering and architecture.',
    englishPrograms: true,
  },
  {
    name: 'Universität Freiburg',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Freiburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Biology', 'Humanities', 'Environmental Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-freiburg.de',
    description: 'A research university with strong interdisciplinary focus and beautiful Black Forest location.',
    englishPrograms: true,
  },
  {
    name: 'Universität Tübingen',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Tübingen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Theology', 'AI', 'Neuroscience', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-tuebingen.de',
    description: 'One of Europe\'s oldest universities, now a leader in AI and neuroscience research.',
    englishPrograms: true,
  },
  {
    name: 'Universität Mannheim',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Mannheim',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Economics', 'Social Sciences', 'Law'],
    admissionPeriod: 'February / August',
    website: 'https://www.uni-mannheim.de',
    description: 'Germany\'s leading university for business and economics, housed in a Baroque palace.',
    englishPrograms: true,
  },
  {
    name: 'Universität Konstanz',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Konstanz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Science', 'Politics', 'Economics', 'Biology'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-konstanz.de',
    description: 'A reform university known for innovative teaching and research excellence.',
    englishPrograms: true,
  },
  {
    name: 'Universität Ulm',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Ulm',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Science', 'Engineering', 'Computer Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-ulm.de',
    description: 'A young research university with strong focus on natural sciences and medicine.',
    englishPrograms: true,
  },
  {
    name: 'Universität Hohenheim',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Stuttgart',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Agriculture', 'Economics', 'Biology', 'Food Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-hohenheim.de',
    description: 'Germany\'s leading university for agricultural sciences and nutrition.',
    englishPrograms: true,
  },
  {
    name: 'Pädagogische Hochschule Heidelberg',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Heidelberg',
    type: 'Public',
    languages: ['German'],
    domains: ['Education', 'Psychology', 'Special Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.ph-heidelberg.de',
    description: 'A specialized university for teacher education and educational sciences.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule Karlsruhe',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Karlsruhe',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Business', 'Architecture'],
    admissionPeriod: 'March / September',
    website: 'https://www.h-ka.de',
    description: 'One of the largest universities of applied sciences in Baden-Württemberg.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Mannheim',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Mannheim',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Design', 'Social Work'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-mannheim.de',
    description: 'A university of applied sciences with strong industry connections.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Technik Stuttgart',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Stuttgart',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Architecture', 'Civil Engineering', 'Surveying', 'Mathematics'],
    admissionPeriod: 'March / September',
    website: 'https://www.hft-stuttgart.de',
    description: 'Specialized in construction, architecture, and geomatics.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Esslingen',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Esslingen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Automotive', 'Social Sciences', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-esslingen.de',
    description: 'Known for automotive engineering and strong industry partnerships.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Heilbronn',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Heilbronn',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Engineering', 'IT', 'Tourism'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-heilbronn.de',
    description: 'One of the largest universities of applied sciences in Baden-Württemberg.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Pforzheim',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Pforzheim',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Design', 'Engineering', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-pforzheim.de',
    description: 'Known for its renowned design and fashion programs.',
    englishPrograms: true,
  },
  {
    name: 'Staatliche Hochschule für Musik und Darstellende Kunst Stuttgart',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Stuttgart',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Performing Arts', 'Opera'],
    admissionPeriod: 'April / October',
    website: 'https://www.hmdk-stuttgart.de',
    description: 'One of Germany\'s leading conservatories for music and performing arts.',
    englishPrograms: false,
  },
  {
    name: 'Staatliche Akademie der Bildenden Künste Stuttgart',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Stuttgart',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Architecture', 'Design', 'Art Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.abk-stuttgart.de',
    description: 'One of the oldest and most significant art academies in Germany.',
    englishPrograms: false,
  },
  {
    name: 'Duale Hochschule Baden-Württemberg',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Stuttgart',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Engineering', 'Social Work', 'Health'],
    admissionPeriod: 'October',
    website: 'https://www.dhbw.de',
    description: 'Germany\'s first and largest dual university combining academic study with workplace training.',
    englishPrograms: true,
  },
  {
    name: 'SRH Hochschule Heidelberg',
    country: 'Germany',
    region: 'Baden-Württemberg',
    city: 'Heidelberg',
    type: 'Private',
    languages: ['German', 'English'],
    domains: ['Business', 'Psychology', 'Engineering', 'Therapy'],
    admissionPeriod: 'Rolling',
    website: 'https://www.srh-hochschule-heidelberg.de',
    description: 'A private university with innovative CORE teaching method.',
    englishPrograms: true,
  },

  // BAVARIA (Bayern)
  {
    name: 'Ludwig-Maximilians-Universität München',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Business', 'Physics', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://www.lmu.de',
    description: 'One of Europe\'s premier academic and research institutions, founded in 1472.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität München',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Physics', 'Medicine', 'Life Sciences'],
    admissionPeriod: 'April / October',
    website: 'https://www.tum.de',
    description: 'Germany\'s top-ranked technical university and a member of TU9 excellence network.',
    englishPrograms: true,
  },
  {
    name: 'Friedrich-Alexander-Universität Erlangen-Nürnberg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Erlangen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Medicine', 'Science', 'Humanities', 'Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.fau.de',
    description: 'Bavaria\'s second largest university with strong engineering and medical faculties.',
    englishPrograms: true,
  },
  {
    name: 'Julius-Maximilians-Universität Würzburg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Würzburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Physics', 'Biology', 'Law', 'Theology'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-wuerzburg.de',
    description: 'Historic university founded in 1402, known for X-ray discovery by Wilhelm Röntgen.',
    englishPrograms: true,
  },
  {
    name: 'Universität Regensburg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Regensburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Law', 'Medicine', 'Science', 'Philosophy', 'Economics'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-regensburg.de',
    description: 'A modern campus university in a UNESCO World Heritage city.',
    englishPrograms: true,
  },
  {
    name: 'Universität Augsburg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Augsburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Law', 'Business', 'Computer Science', 'Materials Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-augsburg.de',
    description: 'Known for its interdisciplinary research clusters and environmental studies.',
    englishPrograms: true,
  },
  {
    name: 'Otto-Friedrich-Universität Bamberg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Bamberg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Humanities', 'Social Sciences', 'Business', 'Psychology'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-bamberg.de',
    description: 'A humanities-focused university in the beautiful UNESCO heritage town of Bamberg.',
    englishPrograms: true,
  },
  {
    name: 'Universität Bayreuth',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Bayreuth',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['African Studies', 'Ecology', 'Polymer Science', 'Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-bayreuth.de',
    description: 'Known for its unique African studies program and polymer research.',
    englishPrograms: true,
  },
  {
    name: 'Universität Passau',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Passau',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Law', 'Business', 'Computer Science', 'Cultural Studies'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-passau.de',
    description: 'A campus university known for its international programs and beautiful location.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule München',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Business', 'Social Sciences'],
    admissionPeriod: 'March / September',
    website: 'https://www.hm.edu',
    description: 'Bavaria\'s largest university of applied sciences with strong industry connections.',
    englishPrograms: true,
  },
  {
    name: 'Technische Hochschule Nürnberg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Nuremberg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Design', 'Social Sciences'],
    admissionPeriod: 'March / September',
    website: 'https://www.th-nuernberg.de',
    description: 'One of the largest universities of applied sciences in Germany.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik und Theater München',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Theater', 'Dance', 'Musicology'],
    admissionPeriod: 'April / October',
    website: 'https://www.hmtm.de',
    description: 'One of Europe\'s most prestigious conservatories.',
    englishPrograms: false,
  },
  {
    name: 'Akademie der Bildenden Künste München',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Sculpture', 'Art Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.adbk.de',
    description: 'Historic art academy founded in 1808 with illustrious alumni.',
    englishPrograms: false,
  },
  {
    name: 'Technische Hochschule Ingolstadt',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Ingolstadt',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Automotive', 'Aerospace', 'Business', 'Computer Science'],
    admissionPeriod: 'March / September',
    website: 'https://www.thi.de',
    description: 'Located in the heart of the German automotive industry.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Augsburg',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Augsburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Business', 'Architecture'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-augsburg.de',
    description: 'Strong in engineering and design with modern campus facilities.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Würzburg-Schweinfurt',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Würzburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Social Work', 'Design'],
    admissionPeriod: 'March / September',
    website: 'https://www.fhws.de',
    description: 'A university of applied sciences with two campuses in Franconia.',
    englishPrograms: true,
  },
  {
    name: 'Munich Business School',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Private',
    languages: ['English', 'German'],
    domains: ['Business', 'Management', 'Finance', 'Entrepreneurship'],
    admissionPeriod: 'Rolling',
    website: 'https://www.munich-business-school.de',
    description: 'An internationally accredited private business school.',
    englishPrograms: true,
  },
  {
    name: 'Universität der Bundeswehr München',
    country: 'Germany',
    region: 'Bavaria',
    city: 'Munich',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Economics', 'Education', 'Computer Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.unibw.de',
    description: 'Federal armed forces university with intensive study programs.',
    englishPrograms: true,
  },

  // BERLIN
  {
    name: 'Freie Universität Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Humanities', 'Social Sciences', 'Medicine', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.fu-berlin.de',
    description: 'One of Berlin\'s elite universities, known for humanities and political science.',
    englishPrograms: true,
  },
  {
    name: 'Humboldt-Universität zu Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Humanities', 'Science', 'Medicine', 'Law', 'Theology'],
    admissionPeriod: 'April / October',
    website: 'https://www.hu-berlin.de',
    description: 'Historic university founded in 1810, pioneering the modern research university concept.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Architecture', 'Economics'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu.berlin',
    description: 'Berlin\'s technical university with strong international reputation.',
    englishPrograms: true,
  },
  {
    name: 'Charité - Universitätsmedizin Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Dentistry', 'Nursing', 'Health Sciences'],
    admissionPeriod: 'April / October',
    website: 'https://www.charite.de',
    description: 'One of Europe\'s largest and most prestigious university hospitals.',
    englishPrograms: true,
  },
  {
    name: 'Universität der Künste Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Fine Arts', 'Design', 'Music', 'Performing Arts'],
    admissionPeriod: 'April / October',
    website: 'https://www.udk-berlin.de',
    description: 'One of the largest art schools in Europe, combining all arts disciplines.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Technik und Wirtschaft Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Design', 'Computer Science'],
    admissionPeriod: 'March / September',
    website: 'https://www.htw-berlin.de',
    description: 'Berlin\'s largest university of applied sciences.',
    englishPrograms: true,
  },
  {
    name: 'Beuth Hochschule für Technik Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Life Sciences', 'Architecture'],
    admissionPeriod: 'March / September',
    website: 'https://www.bht-berlin.de',
    description: 'Technical university of applied sciences with practical focus.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Wirtschaft und Recht Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Law', 'Public Administration', 'Economics'],
    admissionPeriod: 'March / September',
    website: 'https://www.hwr-berlin.de',
    description: 'Leading university of applied sciences for business, law and public administration.',
    englishPrograms: true,
  },
  {
    name: 'Hertie School',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Private',
    languages: ['English'],
    domains: ['Public Policy', 'Governance', 'International Affairs'],
    admissionPeriod: 'Rolling',
    website: 'https://www.hertie-school.org',
    description: 'Germany\'s leading graduate school of public policy.',
    englishPrograms: true,
  },
  {
    name: 'ESMT Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Private',
    languages: ['English'],
    domains: ['Business', 'Management', 'Finance', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.esmt.org',
    description: 'Top-ranked international business school founded by 25 leading global companies.',
    englishPrograms: true,
  },
  {
    name: 'Berlin School of Economics and Law',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Economics', 'Law', 'Security'],
    admissionPeriod: 'March / September',
    website: 'https://www.hwr-berlin.de',
    description: 'Strong focus on applied business and law studies.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik Hanns Eisler Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Composition', 'Conducting', 'Instrumental Studies'],
    admissionPeriod: 'April',
    website: 'https://www.hfm-berlin.de',
    description: 'Elite conservatory known for orchestral and vocal training.',
    englishPrograms: false,
  },
  {
    name: 'Weissensee Kunsthochschule Berlin',
    country: 'Germany',
    region: 'Berlin',
    city: 'Berlin',
    type: 'Public',
    languages: ['German'],
    domains: ['Design', 'Fine Arts', 'Textile Design', 'Fashion'],
    admissionPeriod: 'April',
    website: 'https://www.kh-berlin.de',
    description: 'Leading design school with Bauhaus tradition.',
    englishPrograms: false,
  },

  // BRANDENBURG
  {
    name: 'Universität Potsdam',
    country: 'Germany',
    region: 'Brandenburg',
    city: 'Potsdam',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Humanities', 'Science', 'Law', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-potsdam.de',
    description: 'Brandenburg\'s largest university with beautiful historic campuses.',
    englishPrograms: true,
  },
  {
    name: 'Europa-Universität Viadrina Frankfurt (Oder)',
    country: 'Germany',
    region: 'Brandenburg',
    city: 'Frankfurt (Oder)',
    type: 'Public',
    languages: ['German', 'English', 'Polish'],
    domains: ['Law', 'Business', 'Cultural Studies'],
    admissionPeriod: 'April / October',
    website: 'https://www.europa-uni.de',
    description: 'International university on the German-Polish border.',
    englishPrograms: true,
  },
  {
    name: 'Brandenburgische Technische Universität Cottbus-Senftenberg',
    country: 'Germany',
    region: 'Brandenburg',
    city: 'Cottbus',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Architecture', 'Environmental Science', 'Computer Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.b-tu.de',
    description: 'Technical university focused on engineering and sustainability.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für nachhaltige Entwicklung Eberswalde',
    country: 'Germany',
    region: 'Brandenburg',
    city: 'Eberswalde',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Forestry', 'Sustainability', 'Tourism', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.hnee.de',
    description: 'Germany\'s greenest university focused on sustainable development.',
    englishPrograms: true,
  },
  {
    name: 'Fachhochschule Potsdam',
    country: 'Germany',
    region: 'Brandenburg',
    city: 'Potsdam',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Architecture', 'Design', 'Social Sciences', 'Information Science'],
    admissionPeriod: 'March / September',
    website: 'https://www.fh-potsdam.de',
    description: 'University of applied sciences with creative and social focus.',
    englishPrograms: true,
  },
  {
    name: 'Filmuniversität Babelsberg Konrad Wolf',
    country: 'Germany',
    region: 'Brandenburg',
    city: 'Potsdam',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Film', 'Television', 'Animation', 'Media Studies'],
    admissionPeriod: 'April',
    website: 'https://www.filmuniversitaet.de',
    description: 'Germany\'s largest and oldest film school.',
    englishPrograms: true,
  },

  // BREMEN
  {
    name: 'Universität Bremen',
    country: 'Germany',
    region: 'Bremen',
    city: 'Bremen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Marine Science', 'Materials Science', 'Social Sciences', 'Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-bremen.de',
    description: 'Excellence university known for marine and materials research.',
    englishPrograms: true,
  },
  {
    name: 'Jacobs University Bremen',
    country: 'Germany',
    region: 'Bremen',
    city: 'Bremen',
    type: 'Private',
    languages: ['English'],
    domains: ['Engineering', 'Science', 'Humanities', 'Business'],
    admissionPeriod: 'Rolling',
    website: 'https://www.jacobs-university.de',
    description: 'International private university with diverse student body from 110+ countries.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Bremen',
    country: 'Germany',
    region: 'Bremen',
    city: 'Bremen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Social Sciences', 'Architecture'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-bremen.de',
    description: 'International university of applied sciences with strong practice orientation.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Bremerhaven',
    country: 'Germany',
    region: 'Bremen',
    city: 'Bremerhaven',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Logistics', 'Food Technology', 'Engineering', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-bremerhaven.de',
    description: 'Specialized in maritime, logistics and food technology.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Künste Bremen',
    country: 'Germany',
    region: 'Bremen',
    city: 'Bremen',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Fine Arts', 'Design'],
    admissionPeriod: 'April',
    website: 'https://www.hfk-bremen.de',
    description: 'Art and music conservatory with interdisciplinary focus.',
    englishPrograms: false,
  },

  // HAMBURG
  {
    name: 'Universität Hamburg',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Law', 'Business', 'Medicine', 'Humanities', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-hamburg.de',
    description: 'Northern Germany\'s largest university and recent Excellence University.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Hamburg',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Aviation', 'Biotechnology'],
    admissionPeriod: 'April / October',
    website: 'https://www.tuhh.de',
    description: 'Technical university with strong focus on engineering and innovation.',
    englishPrograms: true,
  },
  {
    name: 'HafenCity Universität Hamburg',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Architecture', 'Urban Planning', 'Civil Engineering', 'Geomatics'],
    admissionPeriod: 'April / October',
    website: 'https://www.hcu-hamburg.de',
    description: 'Germany\'s only university focused exclusively on the built environment.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Angewandte Wissenschaften Hamburg',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Life Sciences', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.haw-hamburg.de',
    description: 'One of the largest universities of applied sciences in Germany.',
    englishPrograms: true,
  },
  {
    name: 'Hamburg School of Business Administration',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Private',
    languages: ['German', 'English'],
    domains: ['Business', 'Management', 'Marketing', 'Finance'],
    admissionPeriod: 'Rolling',
    website: 'https://www.hsba.de',
    description: 'Practice-oriented business school with dual study programs.',
    englishPrograms: true,
  },
  {
    name: 'Bucerius Law School',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Private',
    languages: ['German', 'English'],
    domains: ['Law', 'Business Law', 'International Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.law-school.de',
    description: 'Germany\'s first private law school with excellent reputation.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik und Theater Hamburg',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Theater', 'Music Education', 'Church Music'],
    admissionPeriod: 'April',
    website: 'https://www.hfmt-hamburg.de',
    description: 'Leading conservatory with strong connections to Hamburg\'s cultural scene.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für bildende Künste Hamburg',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Fine Arts', 'Design', 'Architecture', 'Film'],
    admissionPeriod: 'April',
    website: 'https://www.hfbk-hamburg.de',
    description: 'Art academy with reputation for innovative contemporary art.',
    englishPrograms: true,
  },
  {
    name: 'Kühne Logistics University',
    country: 'Germany',
    region: 'Hamburg',
    city: 'Hamburg',
    type: 'Private',
    languages: ['English'],
    domains: ['Logistics', 'Supply Chain', 'Management', 'Business'],
    admissionPeriod: 'Rolling',
    website: 'https://www.the-klu.org',
    description: 'Specialized private university for logistics and supply chain management.',
    englishPrograms: true,
  },

  // HESSE (Hessen)
  {
    name: 'Goethe-Universität Frankfurt am Main',
    country: 'Germany',
    region: 'Hesse',
    city: 'Frankfurt am Main',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Law', 'Medicine', 'Science', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-frankfurt.de',
    description: 'Major research university in Germany\'s financial capital.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Darmstadt',
    country: 'Germany',
    region: 'Hesse',
    city: 'Darmstadt',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Architecture', 'Physics'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu-darmstadt.de',
    description: 'One of Germany\'s leading technical universities and TU9 member.',
    englishPrograms: true,
  },
  {
    name: 'Justus-Liebig-Universität Gießen',
    country: 'Germany',
    region: 'Hesse',
    city: 'Gießen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Veterinary', 'Agriculture', 'Law', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-giessen.de',
    description: 'Full university with strong life sciences focus.',
    englishPrograms: true,
  },
  {
    name: 'Philipps-Universität Marburg',
    country: 'Germany',
    region: 'Hesse',
    city: 'Marburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Pharmacy', 'Medicine', 'Humanities', 'Psychology'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-marburg.de',
    description: 'The world\'s oldest Protestant university, founded in 1527.',
    englishPrograms: true,
  },
  {
    name: 'Universität Kassel',
    country: 'Germany',
    region: 'Hesse',
    city: 'Kassel',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Art', 'Engineering', 'Education', 'Organic Agriculture'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-kassel.de',
    description: 'Known for its documenta art exhibition connection and organic agriculture research.',
    englishPrograms: true,
  },
  {
    name: 'Frankfurt School of Finance & Management',
    country: 'Germany',
    region: 'Hesse',
    city: 'Frankfurt am Main',
    type: 'Private',
    languages: ['English', 'German'],
    domains: ['Finance', 'Business', 'Management', 'Economics'],
    admissionPeriod: 'Rolling',
    website: 'https://www.fs.de',
    description: 'Top-ranked private business school in Europe\'s financial center.',
    englishPrograms: true,
  },
  {
    name: 'EBS Universität für Wirtschaft und Recht',
    country: 'Germany',
    region: 'Hesse',
    city: 'Wiesbaden',
    type: 'Private',
    languages: ['German', 'English'],
    domains: ['Business', 'Law', 'Finance', 'Real Estate'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ebs.edu',
    description: 'Private university combining business and law education.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Darmstadt',
    country: 'Germany',
    region: 'Hesse',
    city: 'Darmstadt',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Design', 'Media'],
    admissionPeriod: 'March / September',
    website: 'https://www.h-da.de',
    description: 'One of the largest universities of applied sciences in Germany.',
    englishPrograms: true,
  },
  {
    name: 'Frankfurt University of Applied Sciences',
    country: 'Germany',
    region: 'Hesse',
    city: 'Frankfurt am Main',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Architecture', 'Business', 'Social Work'],
    admissionPeriod: 'March / September',
    website: 'https://www.frankfurt-university.de',
    description: 'University of applied sciences in Germany\'s banking capital.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Fulda',
    country: 'Germany',
    region: 'Hesse',
    city: 'Fulda',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Health Sciences', 'Food Technology', 'Social Sciences', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-fulda.de',
    description: 'Strong focus on health sciences and food technology.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Gestaltung Offenbach',
    country: 'Germany',
    region: 'Hesse',
    city: 'Offenbach',
    type: 'Public',
    languages: ['German'],
    domains: ['Design', 'Fine Arts', 'Media', 'Typography'],
    admissionPeriod: 'April',
    website: 'https://www.hfg-offenbach.de',
    description: 'Renowned design school with focus on visual communication.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für Musik und Darstellende Kunst Frankfurt',
    country: 'Germany',
    region: 'Hesse',
    city: 'Frankfurt am Main',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Dance', 'Theater', 'Musicology'],
    admissionPeriod: 'April',
    website: 'https://www.hfmdk-frankfurt.de',
    description: 'Comprehensive conservatory for music and performing arts.',
    englishPrograms: false,
  },

  // LOWER SAXONY (Niedersachsen)
  {
    name: 'Georg-August-Universität Göttingen',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Göttingen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Science', 'Humanities', 'Law', 'Medicine', 'Agriculture'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-goettingen.de',
    description: 'Historic university with 47 Nobel Prize laureates associated with it.',
    englishPrograms: true,
  },
  {
    name: 'Gottfried Wilhelm Leibniz Universität Hannover',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Hannover',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Science', 'Law', 'Architecture', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-hannover.de',
    description: 'One of the largest and oldest technical universities in Germany.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Braunschweig',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Braunschweig',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Pharmacy', 'Physics', 'Architecture'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu-braunschweig.de',
    description: 'Germany\'s oldest technical university with strong automotive research.',
    englishPrograms: true,
  },
  {
    name: 'Carl von Ossietzky Universität Oldenburg',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Oldenburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Marine Science', 'Hearing Research', 'Education', 'IT'],
    admissionPeriod: 'April / October',
    website: 'https://uol.de',
    description: 'Research university known for marine science and hearing research.',
    englishPrograms: true,
  },
  {
    name: 'Universität Osnabrück',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Osnabrück',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Cognitive Science', 'Law', 'Biology', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-osnabrueck.de',
    description: 'Strong in cognitive science and interdisciplinary research.',
    englishPrograms: true,
  },
  {
    name: 'Stiftung Tierärztliche Hochschule Hannover',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Hannover',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Veterinary Medicine', 'Animal Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.tiho-hannover.de',
    description: 'One of Europe\'s leading veterinary schools.',
    englishPrograms: true,
  },
  {
    name: 'Medizinische Hochschule Hannover',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Hannover',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Dentistry', 'Public Health', 'Biomedical Engineering'],
    admissionPeriod: 'April / October',
    website: 'https://www.mhh.de',
    description: 'One of Germany\'s leading medical schools and university hospitals.',
    englishPrograms: true,
  },
  {
    name: 'Leuphana Universität Lüneburg',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Lüneburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sustainability', 'Cultural Studies', 'Business', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.leuphana.de',
    description: 'Innovative university with unique interdisciplinary first-year program.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Clausthal',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Clausthal-Zellerfeld',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Mining', 'Materials Science', 'Energy', 'Chemistry'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu-clausthal.de',
    description: 'Technical university with focus on energy and resource engineering.',
    englishPrograms: true,
  },
  {
    name: 'Universität Hildesheim',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Hildesheim',
    type: 'Public',
    languages: ['German'],
    domains: ['Cultural Studies', 'Education', 'Psychology', 'IT'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-hildesheim.de',
    description: 'Strong in cultural studies and teacher education.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule Hannover',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Hannover',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Design', 'Media'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-hannover.de',
    description: 'University of applied sciences with diverse programs.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Osnabrück',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Osnabrück',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Agriculture', 'Engineering', 'Business', 'Health Sciences'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-osnabrueck.de',
    description: 'Strong focus on agriculture and sustainability.',
    englishPrograms: true,
  },
  {
    name: 'Jade Hochschule',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Wilhelmshaven',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Architecture', 'Business', 'Media'],
    admissionPeriod: 'March / September',
    website: 'https://www.jade-hs.de',
    description: 'University of applied sciences with campuses in three cities.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik, Theater und Medien Hannover',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Hannover',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Theater', 'Journalism', 'Media Management'],
    admissionPeriod: 'April',
    website: 'https://www.hmtm-hannover.de',
    description: 'Leading conservatory combining arts with media studies.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für Bildende Künste Braunschweig',
    country: 'Germany',
    region: 'Lower Saxony',
    city: 'Braunschweig',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Design', 'Art Education'],
    admissionPeriod: 'April',
    website: 'https://www.hbk-bs.de',
    description: 'Art academy with strong tradition in visual arts.',
    englishPrograms: false,
  },

  // MECKLENBURG-VORPOMMERN
  {
    name: 'Universität Rostock',
    country: 'Germany',
    region: 'Mecklenburg-Vorpommern',
    city: 'Rostock',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Marine Science', 'Medicine', 'Engineering', 'Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-rostock.de',
    description: 'One of the oldest universities in the Baltic Sea region, founded in 1419.',
    englishPrograms: true,
  },
  {
    name: 'Ernst-Moritz-Arndt-Universität Greifswald',
    country: 'Germany',
    region: 'Mecklenburg-Vorpommern',
    city: 'Greifswald',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Pharmacy', 'Law', 'Baltic Studies'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-greifswald.de',
    description: 'Historic university with strong focus on Baltic region studies.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Wismar',
    country: 'Germany',
    region: 'Mecklenburg-Vorpommern',
    city: 'Wismar',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Design', 'Architecture'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-wismar.de',
    description: 'University of applied sciences in a UNESCO World Heritage city.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Neubrandenburg',
    country: 'Germany',
    region: 'Mecklenburg-Vorpommern',
    city: 'Neubrandenburg',
    type: 'Public',
    languages: ['German'],
    domains: ['Agriculture', 'Food Technology', 'Social Work', 'Health'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-nb.de',
    description: 'Focused on agriculture, food technology, and social sciences.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule Stralsund',
    country: 'Germany',
    region: 'Mecklenburg-Vorpommern',
    city: 'Stralsund',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Tourism', 'Renewable Energy'],
    admissionPeriod: 'March / September',
    website: 'https://www.hochschule-stralsund.de',
    description: 'Known for renewable energy and tourism programs.',
    englishPrograms: true,
  },

  // NORTH RHINE-WESTPHALIA (Nordrhein-Westfalen)
  {
    name: 'RWTH Aachen',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Aachen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Physics', 'Medicine'],
    admissionPeriod: 'April / October',
    website: 'https://www.rwth-aachen.de',
    description: 'Germany\'s largest technical university and Excellence University.',
    englishPrograms: true,
  },
  {
    name: 'Universität zu Köln',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Cologne',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Business', 'Law', 'Humanities', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-koeln.de',
    description: 'One of Germany\'s oldest and largest universities.',
    englishPrograms: true,
  },
  {
    name: 'Universität Bonn',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Bonn',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Mathematics', 'Physics', 'Law', 'Medicine', 'Agriculture'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-bonn.de',
    description: 'Excellence University known for mathematics and natural sciences.',
    englishPrograms: true,
  },
  {
    name: 'Heinrich-Heine-Universität Düsseldorf',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Düsseldorf',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Business', 'Arts', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.hhu.de',
    description: 'Modern campus university with strong medical faculty.',
    englishPrograms: true,
  },
  {
    name: 'Universität Duisburg-Essen',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Essen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Medicine', 'Business', 'Nanotechnology'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-due.de',
    description: 'One of Germany\'s youngest universities with strong engineering programs.',
    englishPrograms: true,
  },
  {
    name: 'Ruhr-Universität Bochum',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Bochum',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Medicine', 'IT Security', 'Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.ruhr-uni-bochum.de',
    description: 'First new public university in Germany after WWII, known for IT security.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Dortmund',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Dortmund',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Physics', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu-dortmund.de',
    description: 'Technical university with strong research in automation and logistics.',
    englishPrograms: true,
  },
  {
    name: 'Westfälische Wilhelms-Universität Münster',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Münster',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Law', 'Medicine', 'Business', 'Theology', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-muenster.de',
    description: 'One of Germany\'s largest universities in a historic city.',
    englishPrograms: true,
  },
  {
    name: 'Universität Bielefeld',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Bielefeld',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sociology', 'History', 'Linguistics', 'Biology', 'Physics'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-bielefeld.de',
    description: 'Reform university known for interdisciplinary research.',
    englishPrograms: true,
  },
  {
    name: 'Universität Paderborn',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Paderborn',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Computer Science', 'Engineering', 'Business', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-paderborn.de',
    description: 'Known for its computer science and IT research.',
    englishPrograms: true,
  },
  {
    name: 'Bergische Universität Wuppertal',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Wuppertal',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Architecture', 'Safety Engineering'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-wuppertal.de',
    description: 'Strong in safety engineering and industrial design.',
    englishPrograms: true,
  },
  {
    name: 'Universität Siegen',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Siegen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Media Studies', 'Business', 'Education'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-siegen.de',
    description: 'Known for its media and communication studies.',
    englishPrograms: true,
  },
  {
    name: 'FernUniversität in Hagen',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Hagen',
    type: 'Public',
    languages: ['German'],
    domains: ['Law', 'Business', 'Psychology', 'Computer Science', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://www.fernuni-hagen.de',
    description: 'Germany\'s only state distance-learning university with 70,000+ students.',
    englishPrograms: false,
  },
  {
    name: 'Deutsche Sporthochschule Köln',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Cologne',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Sports Science', 'Sports Medicine', 'Sports Management'],
    admissionPeriod: 'April / October',
    website: 'https://www.dshs-koeln.de',
    description: 'Germany\'s only university entirely devoted to sport and exercise science.',
    englishPrograms: true,
  },
  {
    name: 'WHU – Otto Beisheim School of Management',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Vallendar',
    type: 'Private',
    languages: ['English', 'German'],
    domains: ['Business', 'Finance', 'Entrepreneurship', 'Management'],
    admissionPeriod: 'Rolling',
    website: 'https://www.whu.edu',
    description: 'One of Europe\'s leading business schools with top rankings.',
    englishPrograms: true,
  },
  {
    name: 'Fachhochschule Aachen',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Aachen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Business', 'Chemistry'],
    admissionPeriod: 'March / September',
    website: 'https://www.fh-aachen.de',
    description: 'One of Germany\'s largest universities of applied sciences.',
    englishPrograms: true,
  },
  {
    name: 'Technische Hochschule Köln',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Cologne',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Social Sciences', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.th-koeln.de',
    description: 'Germany\'s largest university of applied sciences.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Düsseldorf',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Düsseldorf',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Architecture', 'Design', 'Engineering', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-duesseldorf.de',
    description: 'University of applied sciences with modern campus.',
    englishPrograms: true,
  },
  {
    name: 'Kunstakademie Düsseldorf',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Düsseldorf',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Art Education', 'Sculpture'],
    admissionPeriod: 'April',
    website: 'https://www.kunstakademie-duesseldorf.de',
    description: 'One of the world\'s most prestigious art academies.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für Musik und Tanz Köln',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Cologne',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Dance', 'Music Education'],
    admissionPeriod: 'April',
    website: 'https://www.hfmt-koeln.de',
    description: 'One of Europe\'s largest conservatories for music and dance.',
    englishPrograms: false,
  },
  {
    name: 'Folkwang Universität der Künste',
    country: 'Germany',
    region: 'North Rhine-Westphalia',
    city: 'Essen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Music', 'Theater', 'Dance', 'Design', 'Photography'],
    admissionPeriod: 'April',
    website: 'https://www.folkwang-uni.de',
    description: 'Comprehensive arts university with interdisciplinary focus.',
    englishPrograms: true,
  },

  // RHINELAND-PALATINATE (Rheinland-Pfalz)
  {
    name: 'Johannes Gutenberg-Universität Mainz',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Mainz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Translation', 'Humanities', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-mainz.de',
    description: 'One of Germany\'s largest universities, known for its translation faculty.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Kaiserslautern',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Kaiserslautern',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Physics', 'Mathematics'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-kl.de',
    description: 'Technical university with strong research in AI and mathematics.',
    englishPrograms: true,
  },
  {
    name: 'Universität Trier',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Trier',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Law', 'Psychology', 'Humanities', 'Geography'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-trier.de',
    description: 'University in Germany\'s oldest city with strong humanities programs.',
    englishPrograms: true,
  },
  {
    name: 'Universität Koblenz-Landau',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Koblenz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Computer Science', 'Psychology', 'Education', 'Environmental Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-koblenz-landau.de',
    description: 'Two-campus university with focus on education and environmental studies.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Mainz',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Mainz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Business', 'Engineering', 'Design', 'Media'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-mainz.de',
    description: 'University of applied sciences in the Rhine-Main region.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Worms',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Worms',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Tourism', 'Business', 'IT', 'International Trade'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-worms.de',
    description: 'Known for tourism and international business programs.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Koblenz',
    country: 'Germany',
    region: 'Rhineland-Palatinate',
    city: 'Koblenz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Social Sciences', 'Art'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-koblenz.de',
    description: 'University of applied sciences with three campuses.',
    englishPrograms: true,
  },

  // SAARLAND
  {
    name: 'Universität des Saarlandes',
    country: 'Germany',
    region: 'Saarland',
    city: 'Saarbrücken',
    type: 'Public',
    languages: ['German', 'English', 'French'],
    domains: ['Computer Science', 'Law', 'Medicine', 'Nanotechnology'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-saarland.de',
    description: 'Leading European university for computer science and Franco-German studies.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Technik und Wirtschaft des Saarlandes',
    country: 'Germany',
    region: 'Saarland',
    city: 'Saarbrücken',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Architecture', 'Social Work'],
    admissionPeriod: 'March / September',
    website: 'https://www.htw-saarland.de',
    description: 'Saarland\'s university of applied sciences with practical focus.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik Saar',
    country: 'Germany',
    region: 'Saarland',
    city: 'Saarbrücken',
    type: 'Public',
    languages: ['German', 'French'],
    domains: ['Music', 'Music Education', 'Jazz'],
    admissionPeriod: 'April',
    website: 'https://www.hfm.saarland.de',
    description: 'Cross-border music conservatory with Franco-German profile.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule der Bildenden Künste Saar',
    country: 'Germany',
    region: 'Saarland',
    city: 'Saarbrücken',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Design', 'Art Education'],
    admissionPeriod: 'April',
    website: 'https://www.hbksaar.de',
    description: 'Art and design school with Franco-German orientation.',
    englishPrograms: false,
  },

  // SAXONY (Sachsen)
  {
    name: 'Technische Universität Dresden',
    country: 'Germany',
    region: 'Saxony',
    city: 'Dresden',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Medicine', 'Science', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://tu-dresden.de',
    description: 'One of Germany\'s largest technical universities and Excellence University.',
    englishPrograms: true,
  },
  {
    name: 'Universität Leipzig',
    country: 'Germany',
    region: 'Saxony',
    city: 'Leipzig',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Theology', 'Humanities', 'Science'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-leipzig.de',
    description: 'One of the world\'s oldest universities, founded in 1409.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Chemnitz',
    country: 'Germany',
    region: 'Saxony',
    city: 'Chemnitz',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Materials', 'Humanities'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu-chemnitz.de',
    description: 'Technical university with strong materials science research.',
    englishPrograms: true,
  },
  {
    name: 'TU Bergakademie Freiberg',
    country: 'Germany',
    region: 'Saxony',
    city: 'Freiberg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Mining', 'Materials', 'Energy', 'Geoscience'],
    admissionPeriod: 'April / October',
    website: 'https://tu-freiberg.de',
    description: 'The world\'s oldest mining academy, founded in 1765.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Technik, Wirtschaft und Kultur Leipzig',
    country: 'Germany',
    region: 'Saxony',
    city: 'Leipzig',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Media', 'Social Work'],
    admissionPeriod: 'March / September',
    website: 'https://www.htwk-leipzig.de',
    description: 'Saxony\'s largest university of applied sciences.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Technik und Wirtschaft Dresden',
    country: 'Germany',
    region: 'Saxony',
    city: 'Dresden',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Design', 'Business', 'Computer Science'],
    admissionPeriod: 'March / September',
    website: 'https://www.htw-dresden.de',
    description: 'University of applied sciences with strong industry connections.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Zittau/Görlitz',
    country: 'Germany',
    region: 'Saxony',
    city: 'Zittau',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Social Sciences', 'Energy'],
    admissionPeriod: 'March / September',
    website: 'https://www.hszg.de',
    description: 'International university at the border triangle of Germany, Poland and Czech Republic.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik Carl Maria von Weber Dresden',
    country: 'Germany',
    region: 'Saxony',
    city: 'Dresden',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Conducting', 'Composition'],
    admissionPeriod: 'April',
    website: 'https://www.hfmdd.de',
    description: 'Renowned conservatory in Saxony\'s capital.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für Grafik und Buchkunst Leipzig',
    country: 'Germany',
    region: 'Saxony',
    city: 'Leipzig',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Book Design', 'Photography', 'Media Art'],
    admissionPeriod: 'April',
    website: 'https://www.hgb-leipzig.de',
    description: 'Historic academy known for the Leipzig School of painting.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für Musik und Theater Felix Mendelssohn Bartholdy Leipzig',
    country: 'Germany',
    region: 'Saxony',
    city: 'Leipzig',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Theater', 'Dramaturgy'],
    admissionPeriod: 'April',
    website: 'https://www.hmt-leipzig.de',
    description: 'One of Germany\'s oldest conservatories, founded in 1843.',
    englishPrograms: false,
  },
  {
    name: 'Hochschule für Bildende Künste Dresden',
    country: 'Germany',
    region: 'Saxony',
    city: 'Dresden',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Restoration', 'Stage Design', 'Sculpture'],
    admissionPeriod: 'April',
    website: 'https://www.hfbk-dresden.de',
    description: 'Art academy with strong tradition in painting and restoration.',
    englishPrograms: false,
  },

  // SAXONY-ANHALT (Sachsen-Anhalt)
  {
    name: 'Martin-Luther-Universität Halle-Wittenberg',
    country: 'Germany',
    region: 'Saxony-Anhalt',
    city: 'Halle',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Law', 'Science', 'Theology', 'Agriculture'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-halle.de',
    description: 'Historic university where Martin Luther taught.',
    englishPrograms: true,
  },
  {
    name: 'Otto-von-Guericke-Universität Magdeburg',
    country: 'Germany',
    region: 'Saxony-Anhalt',
    city: 'Magdeburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Medicine', 'Computer Science', 'Economics'],
    admissionPeriod: 'April / October',
    website: 'https://www.ovgu.de',
    description: 'Technical university known for engineering and medical research.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Anhalt',
    country: 'Germany',
    region: 'Saxony-Anhalt',
    city: 'Köthen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Design', 'Agriculture', 'Engineering', 'Architecture'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-anhalt.de',
    description: 'University of applied sciences with three campuses.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Magdeburg-Stendal',
    country: 'Germany',
    region: 'Saxony-Anhalt',
    city: 'Magdeburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Social Sciences', 'Business', 'Health'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-magdeburg.de',
    description: 'Modern university of applied sciences with practical orientation.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Merseburg',
    country: 'Germany',
    region: 'Saxony-Anhalt',
    city: 'Merseburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Chemistry', 'Business', 'Social Work'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-merseburg.de',
    description: 'Strong in chemistry and engineering.',
    englishPrograms: true,
  },
  {
    name: 'Burg Giebichenstein Kunsthochschule Halle',
    country: 'Germany',
    region: 'Saxony-Anhalt',
    city: 'Halle',
    type: 'Public',
    languages: ['German'],
    domains: ['Design', 'Fine Arts', 'Fashion'],
    admissionPeriod: 'April',
    website: 'https://www.burg-halle.de',
    description: 'Renowned art and design school with Bauhaus tradition.',
    englishPrograms: false,
  },

  // SCHLESWIG-HOLSTEIN
  {
    name: 'Christian-Albrechts-Universität zu Kiel',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Kiel',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Marine Science', 'Medicine', 'Law', 'Economics', 'Agriculture'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-kiel.de',
    description: 'Excellence University known for marine and life sciences research.',
    englishPrograms: true,
  },
  {
    name: 'Universität zu Lübeck',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Lübeck',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Medicine', 'Computer Science', 'Health Sciences', 'Life Sciences'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-luebeck.de',
    description: 'Specialized university focusing on medicine and life sciences.',
    englishPrograms: true,
  },
  {
    name: 'Europa-Universität Flensburg',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Flensburg',
    type: 'Public',
    languages: ['German', 'English', 'Danish'],
    domains: ['Education', 'European Studies', 'Energy', 'Business'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-flensburg.de',
    description: 'Border university with strong Danish connections and European focus.',
    englishPrograms: true,
  },
  {
    name: 'Fachhochschule Kiel',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Kiel',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Media', 'Agriculture'],
    admissionPeriod: 'March / September',
    website: 'https://www.fh-kiel.de',
    description: 'Schleswig-Holstein\'s largest university of applied sciences.',
    englishPrograms: true,
  },
  {
    name: 'Technische Hochschule Lübeck',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Lübeck',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Architecture', 'Business'],
    admissionPeriod: 'March / September',
    website: 'https://www.th-luebeck.de',
    description: 'Technical university of applied sciences with strong engineering programs.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Flensburg',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Flensburg',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'IT', 'Maritime Technology'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-flensburg.de',
    description: 'University of applied sciences near the Danish border.',
    englishPrograms: true,
  },
  {
    name: 'Muthesius Kunsthochschule',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Kiel',
    type: 'Public',
    languages: ['German'],
    domains: ['Fine Arts', 'Industrial Design', 'Communication Design'],
    admissionPeriod: 'April',
    website: 'https://www.muthesius-kunsthochschule.de',
    description: 'Art and design school in Germany\'s north.',
    englishPrograms: false,
  },
  {
    name: 'Musikhochschule Lübeck',
    country: 'Germany',
    region: 'Schleswig-Holstein',
    city: 'Lübeck',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Music Education', 'Church Music'],
    admissionPeriod: 'April',
    website: 'https://www.mh-luebeck.de',
    description: 'Conservatory in a UNESCO World Heritage city.',
    englishPrograms: false,
  },

  // THURINGIA (Thüringen)
  {
    name: 'Friedrich-Schiller-Universität Jena',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Jena',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Physics', 'Medicine', 'Law', 'Humanities', 'Chemistry'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-jena.de',
    description: 'Historic university known for optics and photonics research.',
    englishPrograms: true,
  },
  {
    name: 'Technische Universität Ilmenau',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Ilmenau',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Computer Science', 'Mathematics', 'Economics'],
    admissionPeriod: 'April / October',
    website: 'https://www.tu-ilmenau.de',
    description: 'Technical university known for electrical engineering and media technology.',
    englishPrograms: true,
  },
  {
    name: 'Bauhaus-Universität Weimar',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Weimar',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Architecture', 'Design', 'Media', 'Civil Engineering', 'Art'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-weimar.de',
    description: 'Successor to the legendary Bauhaus school, leading in architecture and design.',
    englishPrograms: true,
  },
  {
    name: 'Universität Erfurt',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Erfurt',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Education', 'Philosophy', 'Communication', 'Law'],
    admissionPeriod: 'April / October',
    website: 'https://www.uni-erfurt.de',
    description: 'One of the oldest universities in Germany, refounded in 1994.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Schmalkalden',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Schmalkalden',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Law', 'Computer Science'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-schmalkalden.de',
    description: 'Small university with high ranking for student satisfaction.',
    englishPrograms: true,
  },
  {
    name: 'Ernst-Abbe-Hochschule Jena',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Jena',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Social Work', 'Health'],
    admissionPeriod: 'March / September',
    website: 'https://www.eah-jena.de',
    description: 'Named after the optical pioneer Ernst Abbe.',
    englishPrograms: true,
  },
  {
    name: 'Fachhochschule Erfurt',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Erfurt',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Architecture', 'Engineering', 'Landscape Architecture', 'Social Work'],
    admissionPeriod: 'March / September',
    website: 'https://www.fh-erfurt.de',
    description: 'University of applied sciences in Thuringia\'s capital.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule Nordhausen',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Nordhausen',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['Engineering', 'Business', 'Health', 'Renewable Energy'],
    admissionPeriod: 'March / September',
    website: 'https://www.hs-nordhausen.de',
    description: 'Young university with focus on sustainability.',
    englishPrograms: true,
  },
  {
    name: 'Hochschule für Musik Franz Liszt Weimar',
    country: 'Germany',
    region: 'Thuringia',
    city: 'Weimar',
    type: 'Public',
    languages: ['German'],
    domains: ['Music', 'Musicology', 'Jazz', 'Conducting'],
    admissionPeriod: 'April',
    website: 'https://www.hfm-weimar.de',
    description: 'One of Germany\'s most prestigious conservatories.',
    englishPrograms: false,
  },
];
