import type { InsertUniversity } from '@shared/schema';

export const hungarianUniversities: Omit<InsertUniversity, 'id' | 'ranking'>[] = [
  // BUDAPEST - Major Research Universities
  {
    name: 'Eötvös Loránd University (ELTE)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Humanities', 'Sciences', 'Law', 'Education', 'Social Sciences', 'IT'],
    admissionPeriod: 'February / September',
    website: 'https://www.elte.hu',
    description: 'Hungary\'s largest and oldest university, founded in 1635. Leading in humanities and natural sciences.',
    englishPrograms: true,
  },
  {
    name: 'Budapest University of Technology and Economics (BME)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'Architecture', 'IT', 'Economics', 'Natural Sciences'],
    admissionPeriod: 'February / September',
    website: 'https://www.bme.hu',
    description: 'Central Europe\'s oldest technical university, founded in 1782. World-renowned for engineering.',
    englishPrograms: true,
  },
  {
    name: 'Semmelweis University',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English', 'German'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Health Sciences', 'Nursing'],
    admissionPeriod: 'September',
    website: 'https://semmelweis.hu',
    description: 'Hungary\'s premier medical university, named after Ignaz Semmelweis. Top-ranked in medicine.',
    englishPrograms: true,
  },
  {
    name: 'Corvinus University of Budapest',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Economics', 'Business', 'Social Sciences', 'Public Administration', 'Horticulture'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-corvinus.hu',
    description: 'Leading business and economics university in Central Europe.',
    englishPrograms: true,
  },
  {
    name: 'Budapest Business School (BGE)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Business', 'Finance', 'Tourism', 'International Business', 'Commerce'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-bge.hu',
    description: 'Hungary\'s largest business school, known for practical education.',
    englishPrograms: true,
  },
  {
    name: 'Óbuda University',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'IT', 'Light Industry', 'Safety Engineering', 'Mechatronics'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-obuda.hu',
    description: 'Technical university with strong industry connections.',
    englishPrograms: true,
  },
  {
    name: 'University of Veterinary Medicine Budapest',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English', 'German'],
    domains: ['Veterinary Medicine', 'Animal Science', 'Food Safety'],
    admissionPeriod: 'September',
    website: 'https://univet.hu',
    description: 'One of the oldest veterinary schools in the world, founded in 1787.',
    englishPrograms: true,
  },
  {
    name: 'Hungarian University of Agriculture and Life Sciences (MATE)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Agriculture', 'Food Science', 'Landscape Architecture', 'Environmental Science'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-mate.hu',
    description: 'Hungary\'s largest agricultural university with multiple campuses.',
    englishPrograms: true,
  },
  {
    name: 'University of Physical Education',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Sports Science', 'Physical Education', 'Recreation', 'Sports Management'],
    admissionPeriod: 'February / September',
    website: 'https://tf.hu',
    description: 'Central Europe\'s leading sports university.',
    englishPrograms: true,
  },
  {
    name: 'University of Public Service',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Public Administration', 'Law Enforcement', 'Military Science', 'International Relations'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-nke.hu',
    description: 'Training institution for public servants, police, and military officers.',
    englishPrograms: true,
  },
  {
    name: 'Hungarian University of Fine Arts',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Fine Arts', 'Painting', 'Sculpture', 'Graphic Design', 'Restoration'],
    admissionPeriod: 'January',
    website: 'https://www.mke.hu',
    description: 'Hungary\'s premier art academy, founded in 1871.',
    englishPrograms: true,
  },
  {
    name: 'Liszt Ferenc Academy of Music',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Music', 'Composition', 'Conducting', 'Music Education'],
    admissionPeriod: 'January',
    website: 'https://zeneakademia.hu',
    description: 'World-renowned conservatory founded by Franz Liszt in 1875.',
    englishPrograms: true,
  },
  {
    name: 'University of Theatre and Film Arts',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Film', 'Theater', 'Acting', 'Directing', 'Screenwriting'],
    admissionPeriod: 'January',
    website: 'https://www.szfe.hu',
    description: 'One of Europe\'s oldest film and theater schools.',
    englishPrograms: true,
  },
  {
    name: 'Moholy-Nagy University of Art and Design (MOME)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Design', 'Architecture', 'Media', 'Animation', 'Photography'],
    admissionPeriod: 'January',
    website: 'https://www.mome.hu',
    description: 'Leading design university named after the famous Bauhaus artist.',
    englishPrograms: true,
  },
  {
    name: 'Central European University (CEU)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['English'],
    domains: ['Social Sciences', 'Humanities', 'Law', 'Public Policy', 'Economics', 'Environmental Science'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ceu.edu',
    description: 'International graduate university accredited in the US and Austria.',
    englishPrograms: true,
  },
  {
    name: 'Andrássy University Budapest',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['German', 'English'],
    domains: ['International Relations', 'European Studies', 'Economics', 'Law'],
    admissionPeriod: 'September',
    website: 'https://www.andrassyuni.eu',
    description: 'German-language university focusing on Central European studies.',
    englishPrograms: true,
  },
  {
    name: 'Károli Gáspár University of the Reformed Church',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Theology', 'Law', 'Humanities', 'Social Sciences', 'Education'],
    admissionPeriod: 'February / September',
    website: 'https://www.kre.hu',
    description: 'Reformed Church university with strong humanities programs.',
    englishPrograms: true,
  },
  {
    name: 'Pázmány Péter Catholic University',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Theology', 'Law', 'Humanities', 'IT', 'Social Sciences'],
    admissionPeriod: 'February / September',
    website: 'https://www.ppke.hu',
    description: 'Leading Catholic university with faculties across Hungary.',
    englishPrograms: true,
  },
  {
    name: 'Milton Friedman University',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Business', 'Communication', 'Media', 'Tourism', 'IT'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-milton.hu',
    description: 'Private university focusing on communication and business.',
    englishPrograms: true,
  },
  {
    name: 'IBS International Business School',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['English'],
    domains: ['Business', 'Management', 'Marketing', 'Finance', 'Tourism'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ibs-b.hu',
    description: 'International business school with British university partnerships.',
    englishPrograms: true,
  },
  {
    name: 'Metropolitan University',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Communication', 'Tourism', 'Business', 'Art', 'Media'],
    admissionPeriod: 'February / September',
    website: 'https://www.metropolitan.hu',
    description: 'Creative industries university with modern campus.',
    englishPrograms: true,
  },
  {
    name: 'Wekerle Sándor Business School',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Business', 'Economics', 'Finance'],
    admissionPeriod: 'February / September',
    website: 'https://www.wsuf.hu',
    description: 'Private business college with practical focus.',
    englishPrograms: true,
  },

  // DEBRECEN REGION
  {
    name: 'University of Debrecen',
    country: 'Hungary',
    region: 'Northern Great Plain',
    city: 'Debrecen',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Medicine', 'Sciences', 'Agriculture', 'Engineering', 'Humanities', 'Law'],
    admissionPeriod: 'February / September',
    website: 'https://www.unideb.hu',
    description: 'Hungary\'s second-largest university with renowned medical school.',
    englishPrograms: true,
  },
  {
    name: 'Debrecen Reformed Theological University',
    country: 'Hungary',
    region: 'Northern Great Plain',
    city: 'Debrecen',
    type: 'Private',
    languages: ['Hungarian'],
    domains: ['Theology', 'Religious Studies', 'Education'],
    admissionPeriod: 'February / September',
    website: 'https://www.drhe.hu',
    description: 'Historic Reformed theology institution in the "Calvinist Rome".',
    englishPrograms: false,
  },

  // SZEGED REGION
  {
    name: 'University of Szeged',
    country: 'Hungary',
    region: 'Southern Great Plain',
    city: 'Szeged',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Medicine', 'Sciences', 'Law', 'Humanities', 'Engineering', 'Music'],
    admissionPeriod: 'February / September',
    website: 'https://www.u-szeged.hu',
    description: 'One of Hungary\'s most distinguished universities, strong in research.',
    englishPrograms: true,
  },
  {
    name: 'Gál Ferenc University',
    country: 'Hungary',
    region: 'Southern Great Plain',
    city: 'Szeged',
    type: 'Private',
    languages: ['Hungarian'],
    domains: ['Theology', 'Education', 'Social Work', 'Agriculture'],
    admissionPeriod: 'February / September',
    website: 'https://www.gff.hu',
    description: 'Catholic university with multiple campuses in Southern Hungary.',
    englishPrograms: false,
  },

  // PÉCS REGION
  {
    name: 'University of Pécs',
    country: 'Hungary',
    region: 'Southern Transdanubia',
    city: 'Pécs',
    type: 'Public',
    languages: ['Hungarian', 'English', 'German'],
    domains: ['Medicine', 'Law', 'Humanities', 'Sciences', 'Engineering', 'Music', 'Art'],
    admissionPeriod: 'February / September',
    website: 'https://www.pte.hu',
    description: 'Hungary\'s first university (1367), strong medical and humanities programs.',
    englishPrograms: true,
  },

  // GYŐR REGION
  {
    name: 'Széchenyi István University',
    country: 'Hungary',
    region: 'Western Transdanubia',
    city: 'Győr',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'Law', 'Business', 'Music', 'Health Sciences'],
    admissionPeriod: 'February / September',
    website: 'https://www.sze.hu',
    description: 'Leading technical university in Western Hungary, strong Audi partnership.',
    englishPrograms: true,
  },

  // MISKOLC REGION
  {
    name: 'University of Miskolc',
    country: 'Hungary',
    region: 'Northern Hungary',
    city: 'Miskolc',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'Law', 'Economics', 'Humanities', 'Music', 'Health Sciences'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-miskolc.hu',
    description: 'Major university in Northern Hungary with strong engineering tradition.',
    englishPrograms: true,
  },

  // VESZPRÉM REGION
  {
    name: 'University of Pannonia',
    country: 'Hungary',
    region: 'Central Transdanubia',
    city: 'Veszprém',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'IT', 'Economics', 'Humanities', 'Modern Languages'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-pannon.hu',
    description: 'Technical university near Lake Balaton with strong chemical engineering.',
    englishPrograms: true,
  },

  // SOPRON REGION
  {
    name: 'University of Sopron',
    country: 'Hungary',
    region: 'Western Transdanubia',
    city: 'Sopron',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Forestry', 'Wood Science', 'Economics', 'Education', 'Art'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-sopron.hu',
    description: 'Specialized in forestry and wood sciences, historic border town location.',
    englishPrograms: true,
  },

  // KAPOSVÁR REGION (now part of MATE)
  {
    name: 'MATE Kaposvár Campus',
    country: 'Hungary',
    region: 'Southern Transdanubia',
    city: 'Kaposvár',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Agriculture', 'Animal Science', 'Economics', 'Education', 'Art'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-mate.hu',
    description: 'Agricultural campus with strong animal husbandry programs.',
    englishPrograms: true,
  },

  // NYÍREGYHÁZA REGION
  {
    name: 'University of Nyíregyháza',
    country: 'Hungary',
    region: 'Northern Great Plain',
    city: 'Nyíregyháza',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Education', 'Engineering', 'Agriculture', 'Economics', 'Music'],
    admissionPeriod: 'February / September',
    website: 'https://www.nye.hu',
    description: 'Regional university in Eastern Hungary with teacher training focus.',
    englishPrograms: true,
  },

  // EGER REGION
  {
    name: 'Eszterházy Károly Catholic University',
    country: 'Hungary',
    region: 'Northern Hungary',
    city: 'Eger',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Education', 'Sciences', 'IT', 'Economics', 'Sports'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-eszterhazy.hu',
    description: 'Catholic university in historic wine region, strong in teacher education.',
    englishPrograms: true,
  },

  // SZÉKESFEHÉRVÁR REGION
  {
    name: 'Óbuda University Alba Regia Campus',
    country: 'Hungary',
    region: 'Central Transdanubia',
    city: 'Székesfehérvár',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'IT', 'Business'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-obuda.hu',
    description: 'Technical campus in Hungary\'s former royal capital.',
    englishPrograms: true,
  },

  // KECSKEMÉT REGION
  {
    name: 'Neumann János University',
    country: 'Hungary',
    region: 'Southern Great Plain',
    city: 'Kecskemét',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'IT', 'Economics', 'Education', 'Horticulture'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-neumann.hu',
    description: 'Named after computer pioneer John von Neumann, Mercedes partnership.',
    englishPrograms: true,
  },

  // DUNAÚJVÁROS REGION
  {
    name: 'University of Dunaújváros',
    country: 'Hungary',
    region: 'Central Transdanubia',
    city: 'Dunaújváros',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Engineering', 'IT', 'Business', 'Communication'],
    admissionPeriod: 'February / September',
    website: 'https://www.uniduna.hu',
    description: 'Technical university in Hungary\'s steel city.',
    englishPrograms: true,
  },

  // SZOLNOK REGION
  {
    name: 'MATE Szolnok Campus',
    country: 'Hungary',
    region: 'Northern Great Plain',
    city: 'Szolnok',
    type: 'Public',
    languages: ['Hungarian'],
    domains: ['Business', 'Tourism', 'Finance'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-mate.hu',
    description: 'Business-focused campus in central Hungary.',
    englishPrograms: false,
  },

  // BÉKÉSCSABA REGION
  {
    name: 'University of Szeged Békéscsaba Campus',
    country: 'Hungary',
    region: 'Southern Great Plain',
    city: 'Békéscsaba',
    type: 'Public',
    languages: ['Hungarian'],
    domains: ['Engineering', 'Agriculture', 'Education'],
    admissionPeriod: 'February / September',
    website: 'https://www.u-szeged.hu',
    description: 'Regional campus serving the southeastern border region.',
    englishPrograms: false,
  },

  // ADDITIONAL PRIVATE UNIVERSITIES
  {
    name: 'Kodolányi János University',
    country: 'Hungary',
    region: 'Central Transdanubia',
    city: 'Székesfehérvár',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Tourism', 'Communication', 'International Studies', 'Business'],
    admissionPeriod: 'February / September',
    website: 'https://www.kodolanyi.hu',
    description: 'Private university with campuses in Székesfehérvár and Budapest.',
    englishPrograms: true,
  },
  {
    name: 'Edutus University',
    country: 'Hungary',
    region: 'Central Hungary',
    city: 'Tatabánya',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Business', 'Engineering', 'IT', 'Tourism'],
    admissionPeriod: 'February / September',
    website: 'https://www.edutus.hu',
    description: 'Private university with practical business education.',
    englishPrograms: true,
  },
  {
    name: 'Tomori Pál College',
    country: 'Hungary',
    region: 'Southern Great Plain',
    city: 'Kalocsa',
    type: 'Private',
    languages: ['Hungarian'],
    domains: ['Business', 'Finance', 'Agriculture'],
    admissionPeriod: 'February / September',
    website: 'https://www.tfrk.hu',
    description: 'Small private college in historic archbishop city.',
    englishPrograms: false,
  },
  {
    name: 'Budapest Metropolitan University (METU)',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Design', 'Business', 'Tourism', 'Communication', 'IT'],
    admissionPeriod: 'February / September',
    website: 'https://www.metropolitan.hu',
    description: 'One of Hungary\'s largest private universities with creative focus.',
    englishPrograms: true,
  },

  // THEOLOGICAL INSTITUTIONS
  {
    name: 'Evangélikus Hittudományi Egyetem',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Theology', 'Religious Studies', 'Social Work'],
    admissionPeriod: 'February / September',
    website: 'https://www.lutheran.hu',
    description: 'Lutheran theological university.',
    englishPrograms: true,
  },
  {
    name: 'Országos Rabbiképző-Zsidó Egyetem',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Private',
    languages: ['Hungarian', 'English', 'Hebrew'],
    domains: ['Jewish Studies', 'Theology', 'History'],
    admissionPeriod: 'September',
    website: 'https://www.or-zse.hu',
    description: 'The only rabbinical seminary in Central Europe, founded in 1877.',
    englishPrograms: true,
  },
  {
    name: 'Adventist Theological College',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Pécel',
    type: 'Private',
    languages: ['Hungarian', 'English'],
    domains: ['Theology', 'Religious Education', 'Pastoral Studies'],
    admissionPeriod: 'September',
    website: 'https://www.ahf.hu',
    description: 'Seventh-day Adventist theological institution.',
    englishPrograms: true,
  },
  {
    name: 'Sárospatak Reformed Theological Academy',
    country: 'Hungary',
    region: 'Northern Hungary',
    city: 'Sárospatak',
    type: 'Private',
    languages: ['Hungarian'],
    domains: ['Theology', 'Religious Education'],
    admissionPeriod: 'September',
    website: 'https://www.srta.hu',
    description: 'Historic Reformed academy in the famous college town.',
    englishPrograms: false,
  },
  {
    name: 'Pápai Reformed Theological Seminary',
    country: 'Hungary',
    region: 'Central Transdanubia',
    city: 'Pápa',
    type: 'Private',
    languages: ['Hungarian'],
    domains: ['Theology', 'Religious Education'],
    admissionPeriod: 'September',
    website: 'https://www.prta.hu',
    description: 'Reformed theological academy with 500-year tradition.',
    englishPrograms: false,
  },

  // SPECIALIZED INSTITUTIONS
  {
    name: 'National University of Public Service',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Public Administration', 'Military Science', 'Law Enforcement', 'National Security'],
    admissionPeriod: 'February / September',
    website: 'https://www.uni-nke.hu',
    description: 'Central institution for public service education.',
    englishPrograms: true,
  },
  {
    name: 'Hungarian Dance Academy',
    country: 'Hungary',
    region: 'Budapest',
    city: 'Budapest',
    type: 'Public',
    languages: ['Hungarian', 'English'],
    domains: ['Dance', 'Ballet', 'Folk Dance', 'Contemporary Dance'],
    admissionPeriod: 'January',
    website: 'https://www.mtf.hu',
    description: 'National dance academy with renowned ballet program.',
    englishPrograms: true,
  },
];
