import type { InsertUniversity } from '@shared/schema';

export const italianUniversities: Omit<InsertUniversity, 'id' | 'ranking'>[] = [
  // LOMBARDY - Milan and surroundings
  {
    name: 'Politecnico di Milano',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Milan',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Architecture', 'Design', 'Computer Science'],
    admissionPeriod: 'March - July',
    website: 'https://www.polimi.it',
    description: 'Italy\'s largest technical university and one of Europe\'s top engineering schools. Ranked among the world\'s best for engineering and design.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €3,898',
    tuitionFeeNonEU: '€3,898 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Milano',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Milan',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Law', 'Humanities', 'Sciences', 'Political Science'],
    admissionPeriod: 'April - August',
    website: 'https://www.unimi.it',
    description: 'Milan\'s largest public university with a comprehensive range of programs. Known for research excellence.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,900',
    tuitionFeeNonEU: '€2,900 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università Commerciale Luigi Bocconi',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Milan',
    type: 'Private',
    languages: ['Italian', 'English'],
    domains: ['Business', 'Economics', 'Finance', 'Law', 'Political Science'],
    admissionPeriod: 'January - May',
    website: 'https://www.unibocconi.eu',
    description: 'Italy\'s most prestigious business school, consistently ranked among the world\'s best. Strong alumni network.',
    englishPrograms: true,
    tuitionFeeEU: '€12,500 - €14,000',
    tuitionFeeNonEU: '€12,500 - €14,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università Cattolica del Sacro Cuore',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Milan',
    type: 'Private',
    languages: ['Italian', 'English'],
    domains: ['Economics', 'Medicine', 'Psychology', 'Humanities', 'Education'],
    admissionPeriod: 'February - July',
    website: 'https://www.unicatt.it',
    description: 'The largest private university in Europe. Multiple campuses across Italy with strong Catholic traditions.',
    englishPrograms: true,
    tuitionFeeEU: '€4,500 - €9,500',
    tuitionFeeNonEU: '€4,500 - €9,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università Vita-Salute San Raffaele',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Milan',
    type: 'Private',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Psychology', 'Philosophy', 'Biotechnology'],
    admissionPeriod: 'February - April',
    website: 'https://www.unisr.it',
    description: 'Research-intensive medical university connected to San Raffaele Hospital. Known for innovative medical programs.',
    englishPrograms: true,
    tuitionFeeEU: '€8,000 - €15,000',
    tuitionFeeNonEU: '€8,000 - €20,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Milano-Bicocca',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Milan',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Sciences', 'Medicine', 'Economics', 'Psychology', 'Sociology'],
    admissionPeriod: 'April - July',
    website: 'https://www.unimib.it',
    description: 'Modern research university with excellent facilities. Strong focus on interdisciplinary studies.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Bergamo',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Bergamo',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Economics', 'Languages', 'Humanities', 'Law'],
    admissionPeriod: 'May - September',
    website: 'https://www.unibg.it',
    description: 'Growing university with strong ties to the local industrial district. Known for practical, career-oriented programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,500',
    tuitionFeeNonEU: '€2,500 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Brescia',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Brescia',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Economics', 'Law'],
    admissionPeriod: 'May - August',
    website: 'https://www.unibs.it',
    description: 'Strong technical university with excellent engineering and medical programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Pavia',
    country: 'Italy',
    region: 'Lombardy',
    city: 'Pavia',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Sciences', 'Engineering', 'Law', 'Political Science'],
    admissionPeriod: 'April - August',
    website: 'https://www.unipv.it',
    description: 'One of the world\'s oldest universities (founded 1361). Historic campus with prestigious collegiate system.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,200',
    tuitionPeriod: 'per year',
  },

  // LAZIO - Rome
  {
    name: 'Sapienza Università di Roma',
    country: 'Italy',
    region: 'Lazio',
    city: 'Rome',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Architecture', 'Engineering', 'Humanities', 'Law', 'Sciences'],
    admissionPeriod: 'April - September',
    website: 'https://www.uniroma1.it',
    description: 'Europe\'s largest university by enrollment and one of the oldest (founded 1303). Comprehensive research institution.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,900',
    tuitionFeeNonEU: '€2,900 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Roma Tor Vergata',
    country: 'Italy',
    region: 'Lazio',
    city: 'Rome',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Sciences', 'Economics', 'Law'],
    admissionPeriod: 'April - August',
    website: 'https://www.uniroma2.it',
    description: 'Research-focused university with modern campus. Strong in engineering and life sciences.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi Roma Tre',
    country: 'Italy',
    region: 'Lazio',
    city: 'Rome',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Architecture', 'Economics', 'Engineering', 'Humanities', 'Political Science'],
    admissionPeriod: 'May - September',
    website: 'https://www.uniroma3.it',
    description: 'Rome\'s youngest public university with a dynamic, innovative approach to education.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'LUISS Guido Carli',
    country: 'Italy',
    region: 'Lazio',
    city: 'Rome',
    type: 'Private',
    languages: ['Italian', 'English'],
    domains: ['Economics', 'Political Science', 'Law', 'Business'],
    admissionPeriod: 'January - May',
    website: 'https://www.luiss.it',
    description: 'Elite private university focused on social sciences. Strong connections to Italian business and politics.',
    englishPrograms: true,
    tuitionFeeEU: '€10,000 - €14,000',
    tuitionFeeNonEU: '€10,000 - €14,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università Campus Bio-Medico di Roma',
    country: 'Italy',
    region: 'Lazio',
    city: 'Rome',
    type: 'Private',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Engineering', 'Nutrition', 'Nursing'],
    admissionPeriod: 'February - May',
    website: 'https://www.unicampus.it',
    description: 'Specialized biomedical university with excellent medical training and research facilities.',
    englishPrograms: true,
    tuitionFeeEU: '€8,000 - €12,000',
    tuitionFeeNonEU: '€12,000 - €18,000',
    tuitionPeriod: 'per year',
  },

  // EMILIA-ROMAGNA
  {
    name: 'Università di Bologna',
    country: 'Italy',
    region: 'Emilia-Romagna',
    city: 'Bologna',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Law', 'Medicine', 'Sciences', 'Engineering', 'Arts', 'Economics'],
    admissionPeriod: 'March - August',
    website: 'https://www.unibo.it',
    description: 'The world\'s oldest university in continuous operation (founded 1088). Historic prestige with modern research facilities.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Modena e Reggio Emilia',
    country: 'Italy',
    region: 'Emilia-Romagna',
    city: 'Modena',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Economics', 'Sciences', 'Law'],
    admissionPeriod: 'May - September',
    website: 'https://www.unimore.it',
    description: 'Strong ties to the automotive and ceramics industries. Known for applied research.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Parma',
    country: 'Italy',
    region: 'Emilia-Romagna',
    city: 'Parma',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Food Science', 'Medicine', 'Veterinary', 'Law', 'Economics'],
    admissionPeriod: 'May - August',
    website: 'https://www.unipr.it',
    description: 'Renowned for food science programs. Located in Italy\'s "Food Valley" with strong industry connections.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Ferrara',
    country: 'Italy',
    region: 'Emilia-Romagna',
    city: 'Ferrara',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Architecture', 'Sciences', 'Engineering', 'Humanities'],
    admissionPeriod: 'May - September',
    website: 'https://www.unife.it',
    description: 'Historic university founded in 1391. Beautiful Renaissance campus in a UNESCO World Heritage city.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,500',
    tuitionFeeNonEU: '€2,500 - €3,500',
    tuitionPeriod: 'per year',
  },

  // TUSCANY
  {
    name: 'Università di Pisa',
    country: 'Italy',
    region: 'Tuscany',
    city: 'Pisa',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Sciences', 'Engineering', 'Medicine', 'Humanities', 'Economics'],
    admissionPeriod: 'April - August',
    website: 'https://www.unipi.it',
    description: 'Historic research university (founded 1343). Home to several prestigious research institutes and Scuola Normale.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,200',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Scuola Normale Superiore di Pisa',
    country: 'Italy',
    region: 'Tuscany',
    city: 'Pisa',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Humanities', 'Sciences', 'Mathematics', 'Physics'],
    admissionPeriod: 'August - September',
    website: 'https://www.sns.it',
    description: 'Elite research institution with highly selective admission. Tuition-free with stipends for all students.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free)',
    tuitionFeeNonEU: '€0 (Free)',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Scuola Superiore Sant\'Anna',
    country: 'Italy',
    region: 'Tuscany',
    city: 'Pisa',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Economics', 'Law', 'Medicine', 'Political Science'],
    admissionPeriod: 'August - September',
    website: 'https://www.santannapisa.it',
    description: 'Prestigious school for applied sciences with free tuition and monthly stipends.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free)',
    tuitionFeeNonEU: '€0 (Free)',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Firenze',
    country: 'Italy',
    region: 'Tuscany',
    city: 'Florence',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Architecture', 'Arts', 'Medicine', 'Engineering', 'Agriculture', 'Law'],
    admissionPeriod: 'April - August',
    website: 'https://www.unifi.it',
    description: 'Major Tuscan university in the Renaissance capital. Strong in arts, architecture, and humanities.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,200',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Siena',
    country: 'Italy',
    region: 'Tuscany',
    city: 'Siena',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Law', 'Economics', 'Sciences', 'Humanities'],
    admissionPeriod: 'May - September',
    website: 'https://www.unisi.it',
    description: 'Historic university (founded 1240) in a beautiful medieval city. Strong in banking and biotechnology.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },

  // VENETO
  {
    name: 'Università degli Studi di Padova',
    country: 'Italy',
    region: 'Veneto',
    city: 'Padua',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Engineering', 'Law', 'Psychology', 'Sciences', 'Agriculture'],
    admissionPeriod: 'April - August',
    website: 'https://www.unipd.it',
    description: 'One of the oldest universities (founded 1222). Where Galileo taught. Top-ranked in Italy.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università Ca\' Foscari Venezia',
    country: 'Italy',
    region: 'Veneto',
    city: 'Venice',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Economics', 'Languages', 'Humanities', 'Sciences', 'Management'],
    admissionPeriod: 'May - September',
    website: 'https://www.unive.it',
    description: 'First Italian business school (founded 1868). Unique location in Venice\'s historic center.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università IUAV di Venezia',
    country: 'Italy',
    region: 'Veneto',
    city: 'Venice',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Architecture', 'Urban Planning', 'Design', 'Arts', 'Fashion'],
    admissionPeriod: 'March - July',
    website: 'https://www.iuav.it',
    description: 'Italy\'s premier architecture school. Unique setting in Venice for design and planning studies.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Verona',
    country: 'Italy',
    region: 'Veneto',
    city: 'Verona',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Law', 'Economics', 'Humanities', 'Sciences'],
    admissionPeriod: 'May - August',
    website: 'https://www.univr.it',
    description: 'Dynamic university with modern facilities. Strong in wine studies and tourism.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },

  // PIEDMONT
  {
    name: 'Politecnico di Torino',
    country: 'Italy',
    region: 'Piedmont',
    city: 'Turin',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Architecture', 'Design', 'Computer Science'],
    admissionPeriod: 'March - July',
    website: 'https://www.polito.it',
    description: 'Italy\'s oldest technical university. Strong automotive engineering ties with Fiat and aerospace industry.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,800',
    tuitionFeeNonEU: '€2,800 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Torino',
    country: 'Italy',
    region: 'Piedmont',
    city: 'Turin',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Sciences', 'Law', 'Economics', 'Humanities', 'Agriculture'],
    admissionPeriod: 'April - August',
    website: 'https://www.unito.it',
    description: 'Major research university in Piedmont. Among Italy\'s top universities for research output.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,200',
    tuitionPeriod: 'per year',
  },

  // CAMPANIA - Naples
  {
    name: 'Università degli Studi di Napoli Federico II',
    country: 'Italy',
    region: 'Campania',
    city: 'Naples',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Law', 'Sciences', 'Agriculture', 'Architecture'],
    admissionPeriod: 'April - September',
    website: 'https://www.unina.it',
    description: 'One of the oldest public universities (founded 1224 by Frederick II). Southern Italy\'s largest university.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,500',
    tuitionFeeNonEU: '€2,500 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi della Campania Luigi Vanvitelli',
    country: 'Italy',
    region: 'Campania',
    city: 'Naples',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Engineering', 'Architecture', 'Law', 'Economics'],
    admissionPeriod: 'May - September',
    website: 'https://www.unicampania.it',
    description: 'Major research university with multiple campuses in Campania region.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,400',
    tuitionFeeNonEU: '€2,400 - €3,500',
    tuitionPeriod: 'per year',
  },

  // LIGURIA
  {
    name: 'Università degli Studi di Genova',
    country: 'Italy',
    region: 'Liguria',
    city: 'Genoa',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Architecture', 'Sciences', 'Economics'],
    admissionPeriod: 'May - August',
    website: 'https://www.unige.it',
    description: 'Major maritime university with strong engineering and naval architecture programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,000',
    tuitionPeriod: 'per year',
  },

  // FRIULI-VENEZIA GIULIA
  {
    name: 'Università degli Studi di Trieste',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    city: 'Trieste',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Physics', 'Engineering', 'Medicine', 'Law', 'Economics'],
    admissionPeriod: 'May - September',
    website: 'https://www.units.it',
    description: 'Gateway to Central Europe with excellent physics research. Home to international scientific institutions.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Udine',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    city: 'Udine',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Agriculture', 'Languages', 'Economics'],
    admissionPeriod: 'May - September',
    website: 'https://www.uniud.it',
    description: 'Young, dynamic university with strong international orientation. Located near Austria and Slovenia.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,500',
    tuitionFeeNonEU: '€2,500 - €3,600',
    tuitionPeriod: 'per year',
  },
  {
    name: 'SISSA - Scuola Internazionale Superiore di Studi Avanzati',
    country: 'Italy',
    region: 'Friuli-Venezia Giulia',
    city: 'Trieste',
    type: 'Public',
    languages: ['English'],
    domains: ['Physics', 'Mathematics', 'Neuroscience'],
    admissionPeriod: 'March - May',
    website: 'https://www.sissa.it',
    description: 'Elite graduate school for physics and mathematics. Fully taught in English with international faculty.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free)',
    tuitionFeeNonEU: '€0 (Free)',
    tuitionPeriod: 'per year',
  },

  // TRENTINO-ALTO ADIGE
  {
    name: 'Università degli Studi di Trento',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    city: 'Trento',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Law', 'Sciences', 'Engineering', 'Social Sciences', 'Economics'],
    admissionPeriod: 'May - August',
    website: 'https://www.unitn.it',
    description: 'One of Italy\'s top-ranked universities. Excellent research facilities in a beautiful Alpine setting.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,700',
    tuitionFeeNonEU: '€2,700 - €4,200',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Libera Università di Bolzano',
    country: 'Italy',
    region: 'Trentino-Alto Adige',
    city: 'Bolzano',
    type: 'Public',
    languages: ['Italian', 'German', 'English'],
    domains: ['Education', 'Computer Science', 'Economics', 'Engineering', 'Design'],
    admissionPeriod: 'May - August',
    website: 'https://www.unibz.it',
    description: 'Trilingual university at the crossroads of Italian and German culture. Unique multilingual programs.',
    englishPrograms: true,
    tuitionFeeEU: '€1,350 - €1,950',
    tuitionFeeNonEU: '€1,350 - €1,950',
    tuitionPeriod: 'per year',
  },

  // SICILY
  {
    name: 'Università degli Studi di Palermo',
    country: 'Italy',
    region: 'Sicily',
    city: 'Palermo',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Engineering', 'Law', 'Architecture', 'Agriculture'],
    admissionPeriod: 'May - September',
    website: 'https://www.unipa.it',
    description: 'Sicily\'s largest university with a rich academic tradition. Strong in Mediterranean studies.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,400',
    tuitionFeeNonEU: '€2,400 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Catania',
    country: 'Italy',
    region: 'Sicily',
    city: 'Catania',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Sciences', 'Engineering', 'Agriculture', 'Humanities'],
    admissionPeriod: 'May - September',
    website: 'https://www.unict.it',
    description: 'Historic Sicilian university (founded 1434). Strong science programs with volcano research.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,400',
    tuitionFeeNonEU: '€2,400 - €3,500',
    tuitionPeriod: 'per year',
  },

  // SARDINIA
  {
    name: 'Università degli Studi di Cagliari',
    country: 'Italy',
    region: 'Sardinia',
    city: 'Cagliari',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Engineering', 'Sciences', 'Law', 'Economics'],
    admissionPeriod: 'May - September',
    website: 'https://www.unica.it',
    description: 'Sardinia\'s main university with Mediterranean research focus. Unique island campus experience.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,400',
    tuitionFeeNonEU: '€2,400 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi di Sassari',
    country: 'Italy',
    region: 'Sardinia',
    city: 'Sassari',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Veterinary', 'Agriculture', 'Law', 'Sciences'],
    admissionPeriod: 'May - September',
    website: 'https://www.uniss.it',
    description: 'Northern Sardinia\'s university with strong agricultural and veterinary programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,300',
    tuitionFeeNonEU: '€2,300 - €3,200',
    tuitionPeriod: 'per year',
  },

  // PUGLIA
  {
    name: 'Università degli Studi di Bari Aldo Moro',
    country: 'Italy',
    region: 'Puglia',
    city: 'Bari',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Law', 'Sciences', 'Economics', 'Agriculture'],
    admissionPeriod: 'May - September',
    website: 'https://www.uniba.it',
    description: 'Southern Italy\'s largest university outside Naples. Strong research in Mediterranean agriculture.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,500',
    tuitionFeeNonEU: '€2,500 - €3,600',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Politecnico di Bari',
    country: 'Italy',
    region: 'Puglia',
    city: 'Bari',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Architecture', 'Industrial Design'],
    admissionPeriod: 'May - August',
    website: 'https://www.poliba.it',
    description: 'Technical university focused on engineering and architecture. Growing international programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università del Salento',
    country: 'Italy',
    region: 'Puglia',
    city: 'Lecce',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Humanities', 'Sciences', 'Engineering', 'Economics', 'Law'],
    admissionPeriod: 'May - September',
    website: 'https://www.unisalento.it',
    description: 'Dynamic university in the beautiful Salento region. Growing international student community.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,400',
    tuitionFeeNonEU: '€2,400 - €3,400',
    tuitionPeriod: 'per year',
  },

  // CALABRIA
  {
    name: 'Università della Calabria',
    country: 'Italy',
    region: 'Calabria',
    city: 'Cosenza',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Sciences', 'Economics', 'Humanities', 'Pharmacy'],
    admissionPeriod: 'May - September',
    website: 'https://www.unical.it',
    description: 'Modern campus university with residential facilities. Italy\'s largest residential campus.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,300',
    tuitionFeeNonEU: '€2,300 - €3,200',
    tuitionPeriod: 'per year',
  },

  // MARCHE
  {
    name: 'Università Politecnica delle Marche',
    country: 'Italy',
    region: 'Marche',
    city: 'Ancona',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Sciences', 'Economics', 'Agriculture'],
    admissionPeriod: 'May - August',
    website: 'https://www.univpm.it',
    description: 'Technical university on the Adriatic coast. Strong marine engineering and medical programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },

  // UMBRIA
  {
    name: 'Università degli Studi di Perugia',
    country: 'Italy',
    region: 'Umbria',
    city: 'Perugia',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Agriculture', 'Veterinary', 'Law', 'Sciences'],
    admissionPeriod: 'May - September',
    website: 'https://www.unipg.it',
    description: 'Historic university (founded 1308) in beautiful Umbria. Famous for its Italian language school.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,600',
    tuitionFeeNonEU: '€2,600 - €3,800',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università per Stranieri di Perugia',
    country: 'Italy',
    region: 'Umbria',
    city: 'Perugia',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Italian Language', 'Humanities', 'Communications', 'International Relations'],
    admissionPeriod: 'Rolling Admissions',
    website: 'https://www.unistrapg.it',
    description: 'Specialized in Italian language and culture for international students. Flexible enrollment.',
    englishPrograms: true,
    tuitionFeeEU: '€1,200 - €2,500',
    tuitionFeeNonEU: '€1,200 - €2,500',
    tuitionPeriod: 'per year',
  },

  // ABRUZZO
  {
    name: 'Università degli Studi dell\'Aquila',
    country: 'Italy',
    region: 'Abruzzo',
    city: 'L\'Aquila',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Engineering', 'Medicine', 'Sciences', 'Humanities', 'Economics'],
    admissionPeriod: 'May - September',
    website: 'https://www.univaq.it',
    description: 'Research university in the Apennine mountains. Rebuilt after 2009 earthquake with modern facilities.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,400',
    tuitionFeeNonEU: '€2,400 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Università degli Studi "G. d\'Annunzio" Chieti-Pescara',
    country: 'Italy',
    region: 'Abruzzo',
    city: 'Chieti',
    type: 'Public',
    languages: ['Italian', 'English'],
    domains: ['Medicine', 'Psychology', 'Architecture', 'Sciences', 'Economics'],
    admissionPeriod: 'May - September',
    website: 'https://www.unich.it',
    description: 'Dual-campus university on the Adriatic coast. Strong neuroscience and sports science programs.',
    englishPrograms: true,
    tuitionFeeEU: '€156 - €2,500',
    tuitionFeeNonEU: '€2,500 - €3,600',
    tuitionPeriod: 'per year',
  },
];
