import type { InsertUniversity } from '@shared/schema';

export const polishUniversities: Omit<InsertUniversity, 'id' | 'ranking'>[] = [
  // MASOVIA (Warsaw Region)
  {
    name: 'University of Warsaw',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Humanities', 'Sciences', 'Law', 'Economics', 'Social Sciences'],
    admissionPeriod: 'June - August',
    website: 'https://www.uw.edu.pl',
    description: 'Poland\'s largest and most prestigious university. Founded in 1816, consistently ranked #1 in Poland.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Warsaw University of Technology',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Architecture', 'Computer Science', 'Physics', 'Chemistry'],
    admissionPeriod: 'June - July',
    website: 'https://www.pw.edu.pl',
    description: 'Poland\'s leading technical university. Top-ranked for engineering and technology in Central Europe.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€3,000 - €5,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'SGH Warsaw School of Economics',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Economics', 'Business', 'Finance', 'Management', 'International Trade'],
    admissionPeriod: 'June - August',
    website: 'https://www.sgh.waw.pl',
    description: 'Poland\'s top business school. Strong connections to Polish government and business leaders.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€3,500 - €5,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Medical University of Warsaw',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Nursing', 'Health Sciences'],
    admissionPeriod: 'May - July',
    website: 'https://www.wum.edu.pl',
    description: 'Poland\'s largest and oldest medical university. Internationally recognized medical programs in English.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€11,000 - €14,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'SWPS University',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Private',
    languages: ['Polish', 'English'],
    domains: ['Psychology', 'Law', 'Communications', 'Design', 'IT'],
    admissionPeriod: 'Rolling - July',
    website: 'https://www.swps.pl',
    description: 'Leading private university focused on social sciences and psychology. Multiple campuses across Poland.',
    englishPrograms: true,
    tuitionFeeEU: '€3,000 - €5,000',
    tuitionFeeNonEU: '€4,000 - €6,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Kozminski University',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Private',
    languages: ['Polish', 'English'],
    domains: ['Business', 'Finance', 'Law', 'Management', 'Economics'],
    admissionPeriod: 'Rolling - August',
    website: 'https://www.kozminski.edu.pl',
    description: 'Triple-accredited business school (AACSB, EQUIS, AMBA). Best private university in Central Europe.',
    englishPrograms: true,
    tuitionFeeEU: '€4,500 - €8,000',
    tuitionFeeNonEU: '€5,500 - €10,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Warsaw University of Life Sciences',
    country: 'Poland',
    region: 'Masovia',
    city: 'Warsaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Agriculture', 'Veterinary', 'Food Science', 'Environment', 'Biology'],
    admissionPeriod: 'June - August',
    website: 'https://www.sggw.edu.pl',
    description: 'Leading agricultural and life sciences university. Beautiful campus with research farms.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,500',
    tuitionPeriod: 'per year',
  },

  // LESSER POLAND (Krakow Region)
  {
    name: 'Jagiellonian University',
    country: 'Poland',
    region: 'Lesser Poland',
    city: 'Krakow',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Humanities', 'Law', 'Medicine', 'Sciences', 'Philosophy'],
    admissionPeriod: 'June - August',
    website: 'https://www.uj.edu.pl',
    description: 'Poland\'s oldest university (founded 1364) and among the oldest in Europe. Alma mater of Pope John Paul II and Copernicus.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €5,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'AGH University of Science and Technology',
    country: 'Poland',
    region: 'Lesser Poland',
    city: 'Krakow',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Mining', 'Computer Science', 'Physics', 'Materials Science'],
    admissionPeriod: 'June - July',
    website: 'https://www.agh.edu.pl',
    description: 'Top technical university with strong research in mining, metallurgy, and energy. Modern facilities.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Krakow University of Economics',
    country: 'Poland',
    region: 'Lesser Poland',
    city: 'Krakow',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Economics', 'Business', 'Finance', 'Public Administration', 'Commodity Science'],
    admissionPeriod: 'June - August',
    website: 'https://www.uek.krakow.pl',
    description: 'One of Poland\'s top economics universities. Strong focus on practical business education.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Krakow University of Technology',
    country: 'Poland',
    region: 'Lesser Poland',
    city: 'Krakow',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Architecture', 'Computer Science', 'Civil Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.pk.edu.pl',
    description: 'Technical university with excellent architecture and civil engineering programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,000',
    tuitionPeriod: 'per year',
  },

  // GREATER POLAND (Poznan Region)
  {
    name: 'Adam Mickiewicz University',
    country: 'Poland',
    region: 'Greater Poland',
    city: 'Poznan',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Humanities', 'Sciences', 'Law', 'Social Sciences', 'Geography'],
    admissionPeriod: 'June - August',
    website: 'https://www.amu.edu.pl',
    description: 'One of Poland\'s largest universities. Strong in humanities and natural sciences.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Poznan University of Technology',
    country: 'Poland',
    region: 'Greater Poland',
    city: 'Poznan',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Computer Science', 'Architecture', 'Management'],
    admissionPeriod: 'June - July',
    website: 'https://www.put.poznan.pl',
    description: 'Leading technical university in western Poland. Strong industry connections.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Poznan University of Medical Sciences',
    country: 'Poland',
    region: 'Greater Poland',
    city: 'Poznan',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Health Sciences'],
    admissionPeriod: 'May - July',
    website: 'https://www.ump.edu.pl',
    description: 'One of Poland\'s best medical universities. English-taught medicine program for international students.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€11,000 - €13,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Poznan University of Economics and Business',
    country: 'Poland',
    region: 'Greater Poland',
    city: 'Poznan',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Economics', 'Business', 'International Relations', 'Commodity Science'],
    admissionPeriod: 'June - August',
    website: 'https://www.ue.poznan.pl',
    description: 'Leading economics university with strong international exchange programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },

  // SILESIA (Katowice/Gliwice Region)
  {
    name: 'University of Silesia',
    country: 'Poland',
    region: 'Silesia',
    city: 'Katowice',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Sciences', 'Humanities', 'Law', 'Education', 'Arts'],
    admissionPeriod: 'June - August',
    website: 'https://www.us.edu.pl',
    description: 'Largest university in Silesia. Strong in sciences and humanities.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Silesian University of Technology',
    country: 'Poland',
    region: 'Silesia',
    city: 'Gliwice',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Mining', 'Computer Science', 'Architecture', 'Chemistry'],
    admissionPeriod: 'June - July',
    website: 'https://www.polsl.pl',
    description: 'Leading technical university in southern Poland. Strong connections to the industrial sector.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Medical University of Silesia',
    country: 'Poland',
    region: 'Silesia',
    city: 'Katowice',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Public Health'],
    admissionPeriod: 'May - July',
    website: 'https://www.sum.edu.pl',
    description: 'Major medical university serving the Silesian industrial region.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€10,000 - €12,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'University of Economics in Katowice',
    country: 'Poland',
    region: 'Silesia',
    city: 'Katowice',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Economics', 'Business', 'Informatics', 'Finance'],
    admissionPeriod: 'June - August',
    website: 'https://www.ue.katowice.pl',
    description: 'Top economics university in southern Poland with modern campus.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },

  // LOWER SILESIA (Wroclaw Region)
  {
    name: 'University of Wroclaw',
    country: 'Poland',
    region: 'Lower Silesia',
    city: 'Wroclaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Humanities', 'Sciences', 'Law', 'Social Sciences', 'Chemistry'],
    admissionPeriod: 'June - August',
    website: 'https://www.uni.wroc.pl',
    description: 'Historic university founded in 1702. Beautiful baroque campus in the heart of Wroclaw.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Wroclaw University of Science and Technology',
    country: 'Poland',
    region: 'Lower Silesia',
    city: 'Wroclaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Computer Science', 'Architecture', 'Chemistry', 'Electronics'],
    admissionPeriod: 'June - July',
    website: 'https://www.pwr.edu.pl',
    description: 'Leading technical university in western Poland. Strong in IT and electronics.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Wroclaw Medical University',
    country: 'Poland',
    region: 'Lower Silesia',
    city: 'Wroclaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Health Sciences'],
    admissionPeriod: 'May - July',
    website: 'https://www.umw.edu.pl',
    description: 'Major medical university with English-taught programs for international students.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€11,000 - €13,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Wroclaw University of Economics and Business',
    country: 'Poland',
    region: 'Lower Silesia',
    city: 'Wroclaw',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Economics', 'Business', 'Management', 'IT'],
    admissionPeriod: 'June - August',
    website: 'https://www.ue.wroc.pl',
    description: 'One of Poland\'s largest economics universities with modern facilities.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },

  // POMERANIA (Gdansk/Gdynia Region)
  {
    name: 'University of Gdansk',
    country: 'Poland',
    region: 'Pomerania',
    city: 'Gdansk',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Sciences', 'Humanities', 'Law', 'Economics', 'Oceanography'],
    admissionPeriod: 'June - August',
    website: 'https://www.ug.edu.pl',
    description: 'Major Baltic university with unique marine and oceanography programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Gdansk University of Technology',
    country: 'Poland',
    region: 'Pomerania',
    city: 'Gdansk',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Naval Architecture', 'Computer Science', 'Electronics'],
    admissionPeriod: 'June - July',
    website: 'https://www.pg.edu.pl',
    description: 'Top technical university with excellent shipbuilding and marine engineering programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Medical University of Gdansk',
    country: 'Poland',
    region: 'Pomerania',
    city: 'Gdansk',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Nursing', 'Biotechnology'],
    admissionPeriod: 'May - July',
    website: 'https://www.gumed.edu.pl',
    description: 'Leading medical university on the Baltic coast with English-taught programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€11,000 - €13,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Gdynia Maritime University',
    country: 'Poland',
    region: 'Pomerania',
    city: 'Gdynia',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Maritime Studies', 'Navigation', 'Marine Engineering', 'Transport'],
    admissionPeriod: 'June - August',
    website: 'https://www.umg.edu.pl',
    description: 'Specialized maritime academy training officers for the merchant marine.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€3,000 - €5,000',
    tuitionPeriod: 'per year',
  },

  // LODZ Region
  {
    name: 'University of Lodz',
    country: 'Poland',
    region: 'Lodz',
    city: 'Lodz',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Humanities', 'Sciences', 'Economics', 'Law', 'Management'],
    admissionPeriod: 'June - August',
    website: 'https://www.uni.lodz.pl',
    description: 'One of Poland\'s largest universities with strong international programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Lodz University of Technology',
    country: 'Poland',
    region: 'Lodz',
    city: 'Lodz',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Textiles', 'Architecture', 'Chemistry', 'IT'],
    admissionPeriod: 'June - July',
    website: 'https://www.p.lodz.pl',
    description: 'Technical university with unique textile engineering programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Medical University of Lodz',
    country: 'Poland',
    region: 'Lodz',
    city: 'Lodz',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Health Sciences'],
    admissionPeriod: 'May - July',
    website: 'https://www.umed.lodz.pl',
    description: 'Major medical university with comprehensive English-taught programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€10,500 - €12,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Film School in Lodz',
    country: 'Poland',
    region: 'Lodz',
    city: 'Lodz',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Film', 'Television', 'Photography', 'Acting', 'Animation'],
    admissionPeriod: 'April - June',
    website: 'https://www.filmschool.lodz.pl',
    description: 'One of the world\'s top film schools. Alumni include Roman Polanski and Andrzej Wajda.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€8,000 - €12,000',
    tuitionPeriod: 'per year',
  },

  // LUBLIN Region
  {
    name: 'Maria Curie-Sklodowska University',
    country: 'Poland',
    region: 'Lublin',
    city: 'Lublin',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Sciences', 'Humanities', 'Law', 'Economics', 'Earth Sciences'],
    admissionPeriod: 'June - August',
    website: 'https://www.umcs.pl',
    description: 'Named after Nobel Prize winner Marie Curie. Strong in natural sciences.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Lublin University of Technology',
    country: 'Poland',
    region: 'Lublin',
    city: 'Lublin',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Computer Science', 'Architecture', 'Environmental Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.pollub.pl',
    description: 'Growing technical university with modern facilities and research centers.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Medical University of Lublin',
    country: 'Poland',
    region: 'Lublin',
    city: 'Lublin',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Pharmacy', 'Nursing'],
    admissionPeriod: 'May - July',
    website: 'https://www.umlub.pl',
    description: 'Well-established medical university with English-taught programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€10,000 - €12,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'John Paul II Catholic University of Lublin',
    country: 'Poland',
    region: 'Lublin',
    city: 'Lublin',
    type: 'Private',
    languages: ['Polish', 'English'],
    domains: ['Theology', 'Philosophy', 'Law', 'Humanities', 'Social Sciences'],
    admissionPeriod: 'June - August',
    website: 'https://www.kul.pl',
    description: 'Historic Catholic university where Pope John Paul II was a professor.',
    englishPrograms: true,
    tuitionFeeEU: '€1,500 - €3,000',
    tuitionFeeNonEU: '€2,000 - €4,000',
    tuitionPeriod: 'per year',
  },

  // WEST POMERANIA (Szczecin Region)
  {
    name: 'University of Szczecin',
    country: 'Poland',
    region: 'West Pomerania',
    city: 'Szczecin',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Sciences', 'Humanities', 'Economics', 'Law', 'Theology'],
    admissionPeriod: 'June - August',
    website: 'https://www.usz.edu.pl',
    description: 'Major university near the German border with growing international programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'West Pomeranian University of Technology',
    country: 'Poland',
    region: 'West Pomerania',
    city: 'Szczecin',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Computer Science', 'Food Science', 'Maritime Studies'],
    admissionPeriod: 'June - July',
    website: 'https://www.zut.edu.pl',
    description: 'Technical university with strong maritime and engineering programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,500 - €4,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Pomeranian Medical University',
    country: 'Poland',
    region: 'West Pomerania',
    city: 'Szczecin',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Dentistry', 'Health Sciences', 'Biotechnology'],
    admissionPeriod: 'May - July',
    website: 'https://www.pum.edu.pl',
    description: 'Medical university serving northwest Poland with English-taught programs.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€10,000 - €12,000',
    tuitionPeriod: 'per year',
  },

  // WARMIA-MASURIA (Olsztyn Region)
  {
    name: 'University of Warmia and Mazury',
    country: 'Poland',
    region: 'Warmia-Masuria',
    city: 'Olsztyn',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Agriculture', 'Veterinary', 'Sciences', 'Humanities', 'Law'],
    admissionPeriod: 'June - August',
    website: 'https://www.uwm.edu.pl',
    description: 'Largest university in northeastern Poland. Strong in agriculture and veterinary medicine.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €4,000',
    tuitionPeriod: 'per year',
  },

  // PODLASIE (Bialystok Region)
  {
    name: 'University of Bialystok',
    country: 'Poland',
    region: 'Podlasie',
    city: 'Bialystok',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Law', 'Sciences', 'Humanities', 'Economics', 'Education'],
    admissionPeriod: 'June - August',
    website: 'https://www.uwb.edu.pl',
    description: 'Growing university in Poland\'s green northeast, close to Belarus.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Medical University of Bialystok',
    country: 'Poland',
    region: 'Podlasie',
    city: 'Bialystok',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Medicine', 'Pharmacy', 'Health Sciences'],
    admissionPeriod: 'May - July',
    website: 'https://www.umb.edu.pl',
    description: 'Medical university with English-taught programs in northeastern Poland.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU in Polish)',
    tuitionFeeNonEU: '€10,000 - €12,000',
    tuitionPeriod: 'per year',
  },
  {
    name: 'Bialystok University of Technology',
    country: 'Poland',
    region: 'Podlasie',
    city: 'Bialystok',
    type: 'Public',
    languages: ['Polish', 'English'],
    domains: ['Engineering', 'Architecture', 'Computer Science', 'Management'],
    admissionPeriod: 'June - July',
    website: 'https://www.pb.edu.pl',
    description: 'Technical university with strong connections to the local IT industry.',
    englishPrograms: true,
    tuitionFeeEU: '€0 (Free for EU)',
    tuitionFeeNonEU: '€2,000 - €3,500',
    tuitionPeriod: 'per year',
  },
];
