import type { InsertUniversity } from "@shared/schema";

export const portugueseUniversities: InsertUniversity[] = [
  {
    name: "University of Lisbon",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://ulisboa.pt",
    description: "Portugal's largest and most prestigious university, formed by the merger of the historic University of Lisbon and Technical University of Lisbon.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €7,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 50000,
    globalRank: 265,
  },
  {
    name: "University of Porto",
    country: "Portugal",
    region: "Porto",
    city: "Porto",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Engineering & Technology", "Medicine & Health", "Sciences", "Business & Economics", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://up.pt",
    description: "One of Portugal's top research universities, known for engineering, medicine, and sciences. Located in the beautiful city of Porto.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €7,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 32000,
    globalRank: 287,
  },
  {
    name: "University of Coimbra",
    country: "Portugal",
    region: "Coimbra",
    city: "Coimbra",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Law & Politics", "Medicine & Health", "Sciences", "Social Sciences & Humanities", "Engineering & Technology"],
    admissionPeriod: "January - March",
    website: "https://uc.pt",
    description: "One of the oldest universities in continuous operation in the world (founded 1290). UNESCO World Heritage Site with stunning baroque library.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €7,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 24000,
    globalRank: 382,
  },
  {
    name: "NOVA University Lisbon",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Sciences", "Medicine & Health", "Law & Politics"],
    admissionPeriod: "January - March",
    website: "https://unl.pt",
    description: "A young and dynamic university known for its business school (Nova SBE) and strong international focus.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €3,000/year",
    tuitionFeeNonEU: "€4,000 - €10,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 20000,
    globalRank: 350,
  },
  {
    name: "University of Minho",
    country: "Portugal",
    region: "Braga",
    city: "Braga",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Engineering & Technology", "Sciences", "Social Sciences & Humanities", "Medicine & Health"],
    admissionPeriod: "January - March",
    website: "https://uminho.pt",
    description: "A leading research university in Northern Portugal with campuses in Braga and Guimarães. Strong in engineering and sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €6,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 20000,
    globalRank: 451,
  },
  {
    name: "University of Aveiro",
    country: "Portugal",
    region: "Aveiro",
    city: "Aveiro",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Engineering & Technology", "Sciences", "Business & Economics", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://ua.pt",
    description: "Known for innovative teaching methods and strong industry partnerships. Beautiful modern campus in the 'Venice of Portugal'.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €6,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 15000,
    globalRank: 401,
  },
  {
    name: "ISCTE - University Institute of Lisbon",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Engineering & Technology"],
    admissionPeriod: "January - March",
    website: "https://iscte-iul.pt",
    description: "A specialized university focused on business, social sciences, and technology. Strong international network and career services.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €2,500/year",
    tuitionFeeNonEU: "€4,000 - €8,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
    globalRank: 500,
  },
  {
    name: "University of Algarve",
    country: "Portugal",
    region: "Algarve",
    city: "Faro",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Sciences", "Medicine & Health", "Business & Economics", "Sports & Tourism"],
    admissionPeriod: "January - March",
    website: "https://ualg.pt",
    description: "Located in Portugal's sunny Algarve region. Strong programs in marine sciences, tourism, and biomedical sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 8000,
    globalRank: 750,
  },
  {
    name: "University of Évora",
    country: "Portugal",
    region: "Alentejo",
    city: "Évora",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Social Sciences & Humanities", "Sciences", "Agriculture & Environment", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://uevora.pt",
    description: "Historic university in a UNESCO World Heritage city. Strong in humanities, archaeology, and agriculture.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 8000,
    globalRank: 800,
  },
  {
    name: "University of Beira Interior",
    country: "Portugal",
    region: "Castelo Branco",
    city: "Covilhã",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Engineering & Technology", "Sciences", "Medicine & Health", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://ubi.pt",
    description: "Located in the Serra da Estrela mountains. Known for aerospace engineering, textile technology, and health sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,500/year",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 7000,
    globalRank: 900,
  },
  {
    name: "Polytechnic Institute of Porto",
    country: "Portugal",
    region: "Porto",
    city: "Porto",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Arts & Design", "Medicine & Health"],
    admissionPeriod: "January - March",
    website: "https://ipp.pt",
    description: "Portugal's largest polytechnic, offering practical and professionally-oriented education with strong industry links.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,100/year",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 18000,
    globalRank: null,
  },
  {
    name: "Polytechnic Institute of Lisbon",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Public",
    languages: ["Portuguese", "English"],
    domains: ["Engineering & Technology", "Business & Economics", "Media & Communication", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://ipl.pt",
    description: "A major polytechnic in Lisbon with diverse programs and strong focus on practical skills and employability.",
    englishPrograms: true,
    tuitionFeeEU: "€697 - €1,100/year",
    tuitionFeeNonEU: "€3,000 - €5,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 12000,
    globalRank: null,
  },
  {
    name: "Católica Lisbon School of Business & Economics",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Private",
    languages: ["English", "Portuguese"],
    domains: ["Business & Economics"],
    admissionPeriod: "Rolling admissions",
    website: "https://clsbe.lisboa.ucp.pt",
    description: "Portugal's top-ranked business school with triple accreditation (AACSB, EQUIS, AMBA). Part of Universidade Católica Portuguesa.",
    englishPrograms: true,
    tuitionFeeEU: "€8,000 - €15,000/year",
    tuitionFeeNonEU: "€10,000 - €18,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 3000,
    globalRank: null,
  },
  {
    name: "Universidade Católica Portuguesa",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Private",
    languages: ["Portuguese", "English"],
    domains: ["Business & Economics", "Law & Politics", "Social Sciences & Humanities", "Medicine & Health", "Arts & Design"],
    admissionPeriod: "January - July",
    website: "https://ucp.pt",
    description: "Portugal's leading private university with campuses in Lisbon, Porto, and Braga. Known for law, business, and theology.",
    englishPrograms: true,
    tuitionFeeEU: "€5,000 - €12,000/year",
    tuitionFeeNonEU: "€7,000 - €15,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 12000,
    globalRank: 550,
  },
  {
    name: "Universidade Europeia",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Private",
    languages: ["Portuguese", "English"],
    domains: ["Business & Economics", "Law & Politics", "Sports & Tourism", "Engineering & Technology"],
    admissionPeriod: "Rolling admissions",
    website: "https://europeia.pt",
    description: "Part of Laureate International Universities network. Offers innovative and career-focused programs.",
    englishPrograms: true,
    tuitionFeeEU: "€5,000 - €9,000/year",
    tuitionFeeNonEU: "€6,000 - €10,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 6000,
    globalRank: null,
  },
  {
    name: "Universidade Lusófona",
    country: "Portugal",
    region: "Lisbon",
    city: "Lisbon",
    type: "Private",
    languages: ["Portuguese", "English"],
    domains: ["Media & Communication", "Arts & Design", "Engineering & Technology", "Social Sciences & Humanities"],
    admissionPeriod: "Rolling admissions",
    website: "https://ulusofona.pt",
    description: "One of Portugal's largest private universities with strong programs in film, media, and communication studies.",
    englishPrograms: true,
    tuitionFeeEU: "€4,000 - €7,000/year",
    tuitionFeeNonEU: "€5,000 - €8,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
    globalRank: null,
  },
];
