import { db } from "./db";
import { universities } from "@shared/schema";

const seedUniversities = [
  // PUBLIC UNIVERSITIES - ANDALUSIA
  {
    name: 'Universidad de Almería',
    region: 'Andalusia',
    city: 'Almería',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Science', 'Agriculture', 'Engineering', 'Humanities'],
    admissionPeriod: 'June - July',
    website: 'https://www.ual.es',
    description: 'A young and dynamic university focused on research in agriculture, environment, and renewable energies.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Cádiz',
    region: 'Andalusia',
    city: 'Cádiz',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Marine Science', 'Engineering', 'Medicine', 'Business'],
    admissionPeriod: 'June - July',
    website: 'https://www.uca.es',
    description: 'Known for its marine sciences programs and strategic location on the Atlantic coast.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Córdoba',
    region: 'Andalusia',
    city: 'Córdoba',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Veterinary', 'Agriculture', 'Science', 'Law'],
    admissionPeriod: 'June - July',
    website: 'https://www.uco.es',
    description: 'Excellence in agricultural sciences, veterinary medicine, and food technology.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Granada',
    region: 'Andalusia',
    city: 'Granada',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Translation', 'Computer Science', 'Psychology', 'Science', 'Medicine'],
    admissionPeriod: 'June - July',
    website: 'https://www.ugr.es',
    description: 'A major intellectual center in southern Spain with a rich history and a large international student population. One of Spain\'s largest universities.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Huelva',
    region: 'Andalusia',
    city: 'Huelva',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Education', 'Business', 'Engineering', 'Social Work'],
    admissionPeriod: 'June - July',
    website: 'https://www.uhu.es',
    description: 'A growing university with strong connections to the mining and energy sectors.',
    englishPrograms: false,
  },
  {
    name: 'Universidad de Jaén',
    region: 'Andalusia',
    city: 'Jaén',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Olive Oil Research', 'Engineering', 'Social Sciences', 'Health'],
    admissionPeriod: 'June - July',
    website: 'https://www.ujaen.es',
    description: 'World leader in olive oil research and technology, serving the agricultural heartland of Andalusia.',
    englishPrograms: false,
  },
  {
    name: 'Universidad de Málaga',
    region: 'Andalusia',
    city: 'Málaga',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Tourism', 'Technology', 'Medicine', 'Arts', 'Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.uma.es',
    description: 'A leading university in tourism studies and technology, located in the Costa del Sol.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Pablo de Olavide',
    region: 'Andalusia',
    city: 'Seville',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Sports Science', 'Social Sciences', 'Biotechnology', 'Law'],
    admissionPeriod: 'June - July',
    website: 'https://www.upo.es',
    description: 'A modern campus university known for its sports science and biotechnology programs.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Sevilla',
    region: 'Andalusia',
    city: 'Seville',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Medicine', 'Law', 'Arts', 'Architecture'],
    admissionPeriod: 'June - July',
    website: 'https://www.us.es',
    description: 'One of Spain\'s largest and oldest universities, with a historic campus in the heart of Seville.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Internacional de Andalucía',
    region: 'Andalusia',
    city: 'Seville',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Postgraduate Studies', 'International Relations', 'Environment'],
    admissionPeriod: 'Rolling',
    website: 'https://www.unia.es',
    description: 'Specialized in postgraduate education with multiple campuses across Andalusia.',
    englishPrograms: true,
  },
  // ARAGON
  {
    name: 'Universidad de Zaragoza',
    region: 'Aragon',
    city: 'Zaragoza',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Science', 'Medicine', 'Humanities', 'Veterinary'],
    admissionPeriod: 'June - July',
    website: 'https://www.unizar.es',
    description: 'The main university in Aragon, with campuses in Zaragoza, Huesca, and Teruel.',
    englishPrograms: true,
  },
  {
    name: 'Universidad San Jorge',
    region: 'Aragon',
    city: 'Zaragoza',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Communication', 'Architecture', 'Health Sciences', 'Business'],
    admissionPeriod: 'Rolling',
    website: 'https://www.usj.es',
    description: 'A private Catholic university focused on communication and health sciences.',
    englishPrograms: true,
  },
  // ASTURIAS
  {
    name: 'Universidad de Oviedo',
    region: 'Asturias',
    city: 'Oviedo',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Mining', 'Engineering', 'Medicine', 'Law', 'Economics'],
    admissionPeriod: 'June - July',
    website: 'https://www.uniovi.es',
    description: 'One of Spain\'s oldest universities, founded in 1608, with strong engineering programs.',
    englishPrograms: true,
  },
  // BALEARIC ISLANDS
  {
    name: 'Universitat de les Illes Balears',
    region: 'Balearic Islands',
    city: 'Palma de Mallorca',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Tourism', 'Marine Biology', 'Education', 'Economics'],
    admissionPeriod: 'June - July',
    website: 'https://www.uib.es',
    description: 'The only public university in the Balearic Islands, specializing in tourism and Mediterranean studies.',
    englishPrograms: true,
  },
  // BASQUE COUNTRY
  {
    name: 'Universidad del País Vasco / Euskal Herriko Unibertsitatea',
    region: 'Basque Country',
    city: 'Bilbao',
    type: 'Public',
    languages: ['Basque', 'Spanish', 'English'],
    domains: ['Engineering', 'Medicine', 'Science', 'Business', 'Arts'],
    admissionPeriod: 'June - July',
    website: 'https://www.ehu.eus',
    description: 'The main public university in the Basque Country with campuses in Bilbao, San Sebastián, and Vitoria.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Deusto',
    region: 'Basque Country',
    city: 'Bilbao',
    type: 'Private',
    languages: ['Spanish', 'Basque', 'English'],
    domains: ['Law', 'Business', 'Engineering', 'Psychology', 'Social Sciences'],
    admissionPeriod: 'January - May',
    website: 'https://www.deusto.es',
    description: 'A prestigious Jesuit university known for its law school and social commitment.',
    englishPrograms: true,
  },
  {
    name: 'Mondragon Unibertsitatea',
    region: 'Basque Country',
    city: 'Mondragón',
    type: 'Private',
    languages: ['Basque', 'Spanish', 'English'],
    domains: ['Engineering', 'Business', 'Education', 'Gastronomy'],
    admissionPeriod: 'Rolling',
    website: 'https://www.mondragon.edu',
    description: 'A cooperative university linked to the Mondragon Corporation, focused on practical education.',
    englishPrograms: true,
  },
  // CANARY ISLANDS
  {
    name: 'Universidad de La Laguna',
    region: 'Canary Islands',
    city: 'San Cristóbal de La Laguna',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Astrophysics', 'Medicine', 'Tourism', 'Marine Sciences'],
    admissionPeriod: 'June - July',
    website: 'https://www.ull.es',
    description: 'The oldest university in the Canary Islands, known for its astrophysics research.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Las Palmas de Gran Canaria',
    region: 'Canary Islands',
    city: 'Las Palmas de Gran Canaria',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Veterinary', 'Tourism', 'Marine Science', 'Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.ulpgc.es',
    description: 'Focused on marine sciences and tourism, serving the eastern Canary Islands.',
    englishPrograms: true,
  },
  // CANTABRIA
  {
    name: 'Universidad de Cantabria',
    region: 'Cantabria',
    city: 'Santander',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Physics', 'Engineering', 'Medicine', 'Economics'],
    admissionPeriod: 'June - July',
    website: 'https://www.unican.es',
    description: 'Strong in physics and engineering, home to important research institutes.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Europea del Atlántico',
    region: 'Cantabria',
    city: 'Santander',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Business', 'Psychology', 'Translation', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uneatlantico.es',
    description: 'A private university with international focus and modern facilities.',
    englishPrograms: true,
  },
  // CASTILE AND LEÓN
  {
    name: 'Universidad de Burgos',
    region: 'Castile and León',
    city: 'Burgos',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Food Technology', 'Engineering', 'Law', 'Education'],
    admissionPeriod: 'June - July',
    website: 'https://www.ubu.es',
    description: 'Known for its food technology and human evolution research programs.',
    englishPrograms: false,
  },
  {
    name: 'Universidad de León',
    region: 'Castile and León',
    city: 'León',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Veterinary', 'Agriculture', 'Mining', 'Biology'],
    admissionPeriod: 'June - July',
    website: 'https://www.unileon.es',
    description: 'Excellence in veterinary medicine and agricultural sciences.',
    englishPrograms: false,
  },
  {
    name: 'Universidad de Salamanca',
    region: 'Castile and León',
    city: 'Salamanca',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Humanities', 'Law', 'Languages', 'History', 'Medicine'],
    admissionPeriod: 'June - July',
    website: 'https://www.usal.es',
    description: 'The oldest university in Spain (founded 1218) and one of the oldest in Europe, famous for teaching Spanish as a foreign language.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Valladolid',
    region: 'Castile and León',
    city: 'Valladolid',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Medicine', 'Architecture', 'Law', 'Science'],
    admissionPeriod: 'June - July',
    website: 'https://www.uva.es',
    description: 'One of Spain\'s oldest universities with campuses in four cities of Castile and León.',
    englishPrograms: true,
  },
  {
    name: 'IE University',
    region: 'Castile and León',
    city: 'Segovia',
    type: 'Private',
    languages: ['English', 'Spanish'],
    domains: ['Business', 'Law', 'International Relations', 'Architecture', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ie.edu',
    description: 'A top-ranked international university with a focus on business, innovation, and entrepreneurship. Most programs taught in English.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Pontificia de Salamanca',
    region: 'Castile and León',
    city: 'Salamanca',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Theology', 'Psychology', 'Communication', 'Education'],
    admissionPeriod: 'June - September',
    website: 'https://www.upsa.es',
    description: 'A Catholic university with strong programs in theology and communication.',
    englishPrograms: false,
  },
  {
    name: 'Universidad Católica de Ávila',
    region: 'Castile and León',
    city: 'Ávila',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Education', 'Psychology', 'Law', 'Business'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ucavila.es',
    description: 'A small Catholic university focused on personalized education.',
    englishPrograms: false,
  },
  {
    name: 'Universidad Europea Miguel de Cervantes',
    region: 'Castile and León',
    city: 'Valladolid',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Health Sciences', 'Law', 'Business', 'Communication'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uemc.es',
    description: 'A private university offering practical, employment-focused education.',
    englishPrograms: false,
  },
  {
    name: 'Universidad Isabel I',
    region: 'Castile and León',
    city: 'Burgos',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Criminology', 'Psychology', 'Law', 'Education'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ui1.es',
    description: 'A primarily online university offering flexible degree programs.',
    englishPrograms: false,
  },
  // CASTILLA-LA MANCHA
  {
    name: 'Universidad de Castilla-La Mancha',
    region: 'Castilla-La Mancha',
    city: 'Ciudad Real',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Chemistry', 'Engineering', 'Medicine', 'Law', 'Education'],
    admissionPeriod: 'June - July',
    website: 'https://www.uclm.es',
    description: 'A multi-campus university serving the entire Castilla-La Mancha region with campuses in Albacete, Ciudad Real, Cuenca, and Toledo.',
    englishPrograms: true,
  },
  // CATALONIA
  {
    name: 'Universitat de Barcelona',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Medicine', 'Science', 'Business', 'Arts', 'Law', 'Psychology'],
    admissionPeriod: 'June - July',
    website: 'https://web.ub.edu',
    description: 'The top-ranked university in Spain and one of the oldest, offering comprehensive programs in the heart of Barcelona.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Autònoma de Barcelona',
    region: 'Catalonia',
    city: 'Bellaterra',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Communication', 'Veterinary', 'Science', 'Medicine', 'Translation'],
    admissionPeriod: 'June - July',
    website: 'https://www.uab.cat',
    description: 'A leading research university with a large campus outside Barcelona, known for its journalism and communication programs.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Politècnica de Catalunya',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Engineering', 'Architecture', 'Technology', 'Mathematics', 'Science'],
    admissionPeriod: 'June - July',
    website: 'https://www.upc.edu',
    description: 'Spain\'s top technical university, specializing in engineering, architecture, and technology.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Pompeu Fabra',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Economics', 'Communication', 'Law', 'Political Science', 'Health Sciences'],
    admissionPeriod: 'May - June',
    website: 'https://www.upf.edu',
    description: 'A modern, high-performance public university known for excellence in teaching and research, particularly in social sciences.',
    englishPrograms: true,
  },
  {
    name: 'Universitat de Girona',
    region: 'Catalonia',
    city: 'Girona',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Tourism', 'Education', 'Science', 'Law'],
    admissionPeriod: 'June - July',
    website: 'https://www.udg.edu',
    description: 'A compact university in a historic city, strong in tourism and water research.',
    englishPrograms: true,
  },
  {
    name: 'Universitat de Lleida',
    region: 'Catalonia',
    city: 'Lleida',
    type: 'Public',
    languages: ['Catalan', 'Spanish'],
    domains: ['Agriculture', 'Medicine', 'Education', 'Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.udl.cat',
    description: 'Known for its agricultural and food science programs, serving western Catalonia.',
    englishPrograms: false,
  },
  {
    name: 'Universitat Rovira i Virgili',
    region: 'Catalonia',
    city: 'Tarragona',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Chemistry', 'Tourism', 'Wine Studies', 'Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.urv.cat',
    description: 'Strong in chemistry and oenology, located in the historic city of Tarragona.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Oberta de Catalunya',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Public',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Computer Science', 'Business', 'Law', 'Psychology', 'Arts'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uoc.edu',
    description: 'A pioneering online university offering flexible degree programs globally.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Ramon Llull',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Private',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Business', 'Engineering', 'Psychology', 'Communication', 'Philosophy'],
    admissionPeriod: 'Rolling',
    website: 'https://www.url.edu',
    description: 'A federation of prestigious schools including ESADE and IQS, known for business and engineering.',
    englishPrograms: true,
  },
  {
    name: 'Universitat de Vic - Universitat Central de Catalunya',
    region: 'Catalonia',
    city: 'Vic',
    type: 'Private',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Education', 'Health Sciences', 'Business', 'Translation'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uvic.cat',
    description: 'A private university focused on personalized education in central Catalonia.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Internacional de Catalunya',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Private',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Dentistry', 'Architecture', 'Medicine', 'Business', 'Law'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uic.es',
    description: 'A private Catholic university known for its dentistry and architecture programs.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Abat Oliba CEU',
    region: 'Catalonia',
    city: 'Barcelona',
    type: 'Private',
    languages: ['Catalan', 'Spanish', 'English'],
    domains: ['Law', 'Business', 'Communication', 'Psychology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uaoceu.es',
    description: 'Part of the CEU network, offering personalized education in a small campus environment.',
    englishPrograms: true,
  },
  // EXTREMADURA
  {
    name: 'Universidad de Extremadura',
    region: 'Extremadura',
    city: 'Badajoz',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Veterinary', 'Agriculture', 'Engineering', 'Education', 'Science'],
    admissionPeriod: 'June - July',
    website: 'https://www.unex.es',
    description: 'The main university in Extremadura with campuses in Badajoz, Cáceres, Mérida, and Plasencia.',
    englishPrograms: false,
  },
  // GALICIA
  {
    name: 'Universidade da Coruña',
    region: 'Galicia',
    city: 'A Coruña',
    type: 'Public',
    languages: ['Galician', 'Spanish', 'English'],
    domains: ['Architecture', 'Computer Science', 'Engineering', 'Education'],
    admissionPeriod: 'June - July',
    website: 'https://www.udc.es',
    description: 'Known for its architecture school and technological research.',
    englishPrograms: true,
  },
  {
    name: 'Universidade de Santiago de Compostela',
    region: 'Galicia',
    city: 'Santiago de Compostela',
    type: 'Public',
    languages: ['Galician', 'Spanish', 'English'],
    domains: ['Pharmacy', 'Medicine', 'Humanities', 'Law', 'Science'],
    admissionPeriod: 'June - July',
    website: 'https://www.usc.es',
    description: 'One of Spain\'s oldest and most prestigious universities, founded in 1495, in a UNESCO World Heritage city.',
    englishPrograms: true,
  },
  {
    name: 'Universidade de Vigo',
    region: 'Galicia',
    city: 'Vigo',
    type: 'Public',
    languages: ['Galician', 'Spanish', 'English'],
    domains: ['Marine Science', 'Engineering', 'Economics', 'Biology'],
    admissionPeriod: 'June - July',
    website: 'https://www.uvigo.gal',
    description: 'Strong in marine sciences and engineering, with campuses in Vigo, Ourense, and Pontevedra.',
    englishPrograms: true,
  },
  // LA RIOJA
  {
    name: 'Universidad de La Rioja',
    region: 'La Rioja',
    city: 'Logroño',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Oenology', 'Engineering', 'Law', 'Business'],
    admissionPeriod: 'June - July',
    website: 'https://www.unirioja.es',
    description: 'Known for its wine science programs in Spain\'s premier wine region.',
    englishPrograms: false,
  },
  {
    name: 'Universidad Internacional de La Rioja',
    region: 'La Rioja',
    city: 'Logroño',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Education', 'Business', 'Law', 'Technology', 'Health'],
    admissionPeriod: 'Rolling',
    website: 'https://www.unir.net',
    description: 'One of Spain\'s largest online universities, offering flexible programs worldwide.',
    englishPrograms: false,
  },
  // MADRID
  {
    name: 'Universidad Complutense de Madrid',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Medicine', 'Law', 'Arts', 'Science', 'Psychology', 'Pharmacy'],
    admissionPeriod: 'June - July',
    website: 'https://www.ucm.es',
    description: 'One of the oldest and largest universities in Europe, with a sprawling campus in Madrid\'s university district.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Autónoma de Madrid',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Science', 'Law', 'Medicine', 'Engineering', 'Philosophy'],
    admissionPeriod: 'June - July',
    website: 'https://www.uam.es',
    description: 'A leading research university located on the Cantoblanco campus, known for its strong science programs.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Politécnica de Madrid',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Architecture', 'Aerospace', 'Agriculture', 'Computer Science'],
    admissionPeriod: 'June - July',
    website: 'https://www.upm.es',
    description: 'Spain\'s largest and most prestigious technical university, training top engineers and architects.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Carlos III de Madrid',
    region: 'Madrid',
    city: 'Getafe',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Economics', 'Law', 'Social Sciences', 'Journalism'],
    admissionPeriod: 'June - July',
    website: 'https://www.uc3m.es',
    description: 'A modern, innovative university known for its bilingual programs and strong international orientation.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Alcalá',
    region: 'Madrid',
    city: 'Alcalá de Henares',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Pharmacy', 'Medicine', 'Architecture', 'Humanities', 'Education'],
    admissionPeriod: 'June - July',
    website: 'https://www.uah.es',
    description: 'Founded in 1499, located in a UNESCO World Heritage city, birthplace of Cervantes.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Rey Juan Carlos',
    region: 'Madrid',
    city: 'Móstoles',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Health Sciences', 'Communication', 'Law', 'Tourism', 'Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.urjc.es',
    description: 'Madrid\'s youngest public university, with multiple campuses and strong growth.',
    englishPrograms: true,
  },
  {
    name: 'UNED - Universidad Nacional de Educación a Distancia',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Public',
    languages: ['Spanish'],
    domains: ['Law', 'Psychology', 'Economics', 'Education', 'Science', 'Engineering'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uned.es',
    description: 'Spain\'s largest university by enrollment, offering distance learning programs nationwide with study centers across Spain.',
    englishPrograms: false,
  },
  {
    name: 'Universidad Pontificia Comillas',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Law', 'Business', 'Theology', 'Psychology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.comillas.edu',
    description: 'A prestigious Jesuit university known for its ICADE business school and ICAI engineering school.',
    englishPrograms: true,
  },
  {
    name: 'Universidad CEU San Pablo',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Pharmacy', 'Medicine', 'Architecture', 'Communication', 'Law'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uspceu.com',
    description: 'Part of the CEU educational foundation, offering comprehensive programs in health sciences and humanities.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Francisco de Vitoria',
    region: 'Madrid',
    city: 'Pozuelo de Alarcón',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Business', 'Law', 'Communication', 'Education', 'Health Sciences'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ufv.es',
    description: 'A Catholic university focused on integral education and professional development.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Europea de Madrid',
    region: 'Madrid',
    city: 'Villaviciosa de Odón',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Health Sciences', 'Sports', 'Architecture', 'Business', 'Engineering'],
    admissionPeriod: 'Rolling',
    website: 'https://www.universidadeuropea.com',
    description: 'A large private university known for its health sciences and sports programs, with a Real Madrid partnership.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Nebrija',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Languages', 'Communication', 'Business', 'Arts', 'Engineering'],
    admissionPeriod: 'Rolling',
    website: 'https://www.nebrija.com',
    description: 'Named after the father of Spanish grammar, strong in languages and communication.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Alfonso X el Sabio',
    region: 'Madrid',
    city: 'Villanueva de la Cañada',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Dentistry', 'Medicine', 'Engineering', 'Architecture', 'Business'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uax.es',
    description: 'One of Spain\'s largest private universities with strong health sciences programs.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Camilo José Cela',
    region: 'Madrid',
    city: 'Villanueva de la Cañada',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Education', 'Communication', 'Health Sciences', 'Sports', 'Business'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ucjc.edu',
    description: 'Named after the Nobel Prize-winning author, focused on innovation in education.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Antonio de Nebrija',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Communication', 'Design', 'Business', 'Languages', 'Engineering'],
    admissionPeriod: 'Rolling',
    website: 'https://www.nebrija.com',
    description: 'A private university known for its international programs and language education.',
    englishPrograms: true,
  },
  // MURCIA
  {
    name: 'Universidad de Murcia',
    region: 'Murcia',
    city: 'Murcia',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Medicine', 'Veterinary', 'Law', 'Biology', 'Education'],
    admissionPeriod: 'June - July',
    website: 'https://www.um.es',
    description: 'Founded in 1915, the main public university in the Murcia region.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Politécnica de Cartagena',
    region: 'Murcia',
    city: 'Cartagena',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Naval Architecture', 'Agriculture', 'Business'],
    admissionPeriod: 'June - July',
    website: 'https://www.upct.es',
    description: 'A technical university specializing in engineering and naval architecture.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Católica San Antonio',
    region: 'Murcia',
    city: 'Murcia',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Sports Science', 'Health Sciences', 'Business', 'Communication'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ucam.edu',
    description: 'Known for its sports science programs and partnerships with elite athletes.',
    englishPrograms: true,
  },
  // NAVARRE
  {
    name: 'Universidad Pública de Navarra',
    region: 'Navarre',
    city: 'Pamplona',
    type: 'Public',
    languages: ['Spanish', 'Basque', 'English'],
    domains: ['Engineering', 'Economics', 'Agriculture', 'Health Sciences'],
    admissionPeriod: 'June - July',
    website: 'https://www.unavarra.es',
    description: 'A modern public university focused on technology and business.',
    englishPrograms: true,
  },
  {
    name: 'Universidad de Navarra',
    region: 'Navarre',
    city: 'Pamplona',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Medicine', 'Business', 'Communication', 'Architecture', 'Pharmacy'],
    admissionPeriod: 'October - April',
    website: 'https://www.unav.edu',
    description: 'One of Spain\'s most prestigious private universities, run by Opus Dei, with a world-renowned cancer research center.',
    englishPrograms: true,
  },
  // VALENCIA
  {
    name: 'Universitat de València',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Public',
    languages: ['Valencian', 'Spanish', 'English'],
    domains: ['Medicine', 'Science', 'Law', 'Economics', 'Humanities'],
    admissionPeriod: 'June - July',
    website: 'https://www.uv.es',
    description: 'One of Spain\'s oldest and largest universities, founded in 1499, with a strong research profile.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Politècnica de València',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Public',
    languages: ['Valencian', 'Spanish', 'English'],
    domains: ['Engineering', 'Technology', 'Architecture', 'Art', 'Agriculture'],
    admissionPeriod: 'June - July',
    website: 'https://www.upv.es',
    description: 'A leading technological university with excellent engineering and architecture programs.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Jaume I',
    region: 'Valencia',
    city: 'Castellón de la Plana',
    type: 'Public',
    languages: ['Valencian', 'Spanish', 'English'],
    domains: ['Translation', 'Technology', 'Ceramics', 'Tourism', 'Psychology'],
    admissionPeriod: 'June - July',
    website: 'https://www.uji.es',
    description: 'Known for its translation studies and ceramic technology programs.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Miguel Hernández de Elche',
    region: 'Valencia',
    city: 'Elche',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Medicine', 'Statistics', 'Sports Science', 'Agriculture'],
    admissionPeriod: 'June - July',
    website: 'https://www.umh.es',
    description: 'A young university known for its health sciences and sports programs.',
    englishPrograms: true,
  },
  {
    name: 'Universitat d\'Alacant',
    region: 'Valencia',
    city: 'Alicante',
    type: 'Public',
    languages: ['Valencian', 'Spanish', 'English'],
    domains: ['Tourism', 'Law', 'Science', 'Economics', 'Engineering'],
    admissionPeriod: 'June - July',
    website: 'https://www.ua.es',
    description: 'Known for its tourism and language programs, with a modern campus.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Cardenal Herrera-CEU',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Veterinary', 'Pharmacy', 'Dentistry', 'Communication', 'Architecture'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uchceu.es',
    description: 'Part of the CEU network, strong in health sciences and veterinary medicine.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Católica de Valencia San Vicente Mártir',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Education', 'Psychology', 'Marine Sciences', 'Health Sciences'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ucv.es',
    description: 'A Catholic university with strong education and health sciences programs.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Europea de Valencia',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Health Sciences', 'Business', 'Sports', 'Design'],
    admissionPeriod: 'Rolling',
    website: 'https://www.universidadeuropea.com/valencia',
    description: 'Part of the Universidad Europea network, focused on health sciences and business.',
    englishPrograms: true,
  },
  // ADDITIONAL UNIVERSITIES
  {
    name: 'VIU - Universidad Internacional de Valencia',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Education', 'Health Sciences', 'Business', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.universidadviu.com',
    description: 'An online university offering flexible programs in education and health.',
    englishPrograms: false,
  },
  {
    name: 'Universidad a Distancia de Madrid',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Law', 'Business', 'Psychology', 'Education', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.udima.es',
    description: 'A private online university offering flexible degree programs.',
    englishPrograms: false,
  },
  // Additional universities to complete the list
  {
    name: 'Universidad Loyola Andalucía',
    region: 'Andalusia',
    city: 'Seville',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Business', 'Law', 'Psychology', 'Communication', 'Engineering'],
    admissionPeriod: 'Rolling',
    website: 'https://www.uloyola.es',
    description: 'A Jesuit university focused on business, social sciences, and ethical leadership.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Fernando Pessoa-Canarias',
    region: 'Canary Islands',
    city: 'Las Palmas de Gran Canaria',
    type: 'Private',
    languages: ['Spanish'],
    domains: ['Health Sciences', 'Dentistry', 'Psychology', 'Criminology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.ufpcanarias.es',
    description: 'A private university focused on health sciences and professional programs.',
    englishPrograms: false,
  },
  {
    name: 'Universidad Europea de Canarias',
    region: 'Canary Islands',
    city: 'La Orotava',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Health Sciences', 'Sports', 'Business', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.universidadeuropea.com/canarias',
    description: 'Part of the Universidad Europea network, serving the Canary Islands.',
    englishPrograms: true,
  },
  {
    name: 'Universitat Internacional Valenciana',
    region: 'Valencia',
    city: 'Valencia',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Education', 'Health Sciences', 'Business', 'Technology'],
    admissionPeriod: 'Rolling',
    website: 'https://www.universidadviu.com',
    description: 'An innovative online university offering flexible programs in education and health.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Villanueva',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Law', 'Communication', 'Business', 'Education'],
    admissionPeriod: 'Rolling',
    website: 'https://www.villanueva.edu',
    description: 'Affiliated with Complutense, focused on law, communication, and business.',
    englishPrograms: true,
  },
  {
    name: 'Universidad Tecnología y Empresa',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Private',
    languages: ['Spanish', 'English'],
    domains: ['Technology', 'Business', 'Design', 'Digital Marketing'],
    admissionPeriod: 'Rolling',
    website: 'https://www.u-tad.com',
    description: 'Specialized in digital technology, animation, and video game development.',
    englishPrograms: true,
  },
  {
    name: 'Centro Universitario de la Defensa',
    region: 'Galicia',
    city: 'Marín',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Defense Studies', 'Technology'],
    admissionPeriod: 'Competitive Exam',
    website: 'https://cud.uvigo.es',
    description: 'Military academy affiliated with Universidad de Vigo, training naval officers.',
    englishPrograms: true,
  },
  {
    name: 'Centro Universitario de la Defensa - Zaragoza',
    region: 'Aragon',
    city: 'Zaragoza',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Engineering', 'Defense Studies', 'Industrial Organization'],
    admissionPeriod: 'Competitive Exam',
    website: 'https://cud.unizar.es',
    description: 'Military academy affiliated with Universidad de Zaragoza, training army officers.',
    englishPrograms: true,
  },
  {
    name: 'Centro Universitario de la Defensa - San Javier',
    region: 'Murcia',
    city: 'San Javier',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Aerospace Engineering', 'Defense Studies', 'Industrial Organization'],
    admissionPeriod: 'Competitive Exam',
    website: 'https://www.cud.upct.es',
    description: 'Military academy affiliated with Universidad Politécnica de Cartagena, training air force officers.',
    englishPrograms: true,
  },
  {
    name: 'Escuela de Organización Industrial',
    region: 'Madrid',
    city: 'Madrid',
    type: 'Public',
    languages: ['Spanish', 'English'],
    domains: ['Business', 'Sustainability', 'Innovation', 'Technology Management'],
    admissionPeriod: 'Rolling',
    website: 'https://www.eoi.es',
    description: 'Spain\'s oldest business school, focused on sustainability and innovation.',
    englishPrograms: true,
  },
];

async function seed() {
  try {
    console.log("Seeding database with complete Spanish university data...");
    
    // Clear existing data
    await db.delete(universities);
    
    // Insert seed data
    await db.insert(universities).values(seedUniversities);
    
    console.log(`✅ Database seeded successfully with ${seedUniversities.length} universities!`);
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seed();
