import type { InsertUniversity } from "@shared/schema";

export const swedishUniversities: InsertUniversity[] = [
  {
    name: "Karolinska Institute",
    country: "Sweden",
    region: "Stockholm",
    city: "Stockholm",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Medicine & Health", "Sciences"],
    admissionPeriod: "October - January",
    website: "https://ki.se",
    description: "One of the world's leading medical universities, responsible for awarding the Nobel Prize in Physiology or Medicine. Ranked #1 in Europe for medicine.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 190,000 - 270,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 7600,
    globalRank: 41,
  },
  {
    name: "KTH Royal Institute of Technology",
    country: "Sweden",
    region: "Stockholm",
    city: "Stockholm",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Engineering & Technology", "Sciences", "Architecture"],
    admissionPeriod: "October - January",
    website: "https://kth.se",
    description: "Sweden's largest and oldest technical university. Leading research in engineering, technology, and innovation. Strong industry partnerships.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 155,000 - 295,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 13000,
    globalRank: 73,
  },
  {
    name: "Stockholm University",
    country: "Sweden",
    region: "Stockholm",
    city: "Stockholm",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Sciences", "Social Sciences & Humanities", "Law & Politics", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://su.se",
    description: "One of the largest universities in Scandinavia. Known for research in natural sciences, humanities, and social sciences.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 90,000 - 145,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 33000,
    globalRank: 134,
  },
  {
    name: "Uppsala University",
    country: "Sweden",
    region: "Uppsala",
    city: "Uppsala",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Sciences", "Medicine & Health", "Social Sciences & Humanities", "Law & Politics", "Engineering & Technology"],
    admissionPeriod: "October - January",
    website: "https://uu.se",
    description: "Founded in 1477, Uppsala University is the oldest university in Scandinavia. A world-class research university with a strong tradition of excellence.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 100,000 - 200,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 45000,
    globalRank: 75,
  },
  {
    name: "Lund University",
    country: "Sweden",
    region: "Skåne",
    city: "Lund",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Sciences", "Medicine & Health", "Social Sciences & Humanities", "Engineering & Technology", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://lu.se",
    description: "Founded in 1666, Lund University is one of Northern Europe's leading research universities. Hosts the European Spallation Source (ESS).",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 90,000 - 295,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 42000,
    globalRank: 85,
  },
  {
    name: "Chalmers University of Technology",
    country: "Sweden",
    region: "Västra Götaland",
    city: "Gothenburg",
    type: "Private",
    languages: ["Swedish", "English"],
    domains: ["Engineering & Technology", "Sciences", "Architecture"],
    admissionPeriod: "October - January",
    website: "https://chalmers.se",
    description: "A leading technical university focused on research and innovation. Known for automotive, IT, and sustainable development research.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 160,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 11000,
    globalRank: 125,
  },
  {
    name: "University of Gothenburg",
    country: "Sweden",
    region: "Västra Götaland",
    city: "Gothenburg",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Sciences", "Medicine & Health", "Social Sciences & Humanities", "Arts & Design", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://gu.se",
    description: "Sweden's third-largest university with broad academic programs. Strong in marine sciences, health sciences, and creative arts.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 77,000 - 190,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 37000,
    globalRank: 187,
  },
  {
    name: "Linköping University",
    country: "Sweden",
    region: "Östergötland",
    city: "Linköping",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Engineering & Technology", "Medicine & Health", "Sciences", "Social Sciences & Humanities"],
    admissionPeriod: "October - January",
    website: "https://liu.se",
    description: "Known for innovative educational approaches and strong industry collaboration. Leading in AI, materials science, and medical technology.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 110,000 - 160,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 32000,
    globalRank: 292,
  },
  {
    name: "Umeå University",
    country: "Sweden",
    region: "Västerbotten",
    city: "Umeå",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Sciences", "Medicine & Health", "Social Sciences & Humanities", "Arts & Design"],
    admissionPeriod: "October - January",
    website: "https://umu.se",
    description: "The largest university in northern Sweden. Known for research in ecology, medicine, and design. European Capital of Culture 2014.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 100,000 - 180,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 34000,
    globalRank: 324,
  },
  {
    name: "Stockholm School of Economics",
    country: "Sweden",
    region: "Stockholm",
    city: "Stockholm",
    type: "Private",
    languages: ["Swedish", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://hhs.se",
    description: "One of Europe's leading business schools. Triple-accredited (AMBA, EQUIS, AACSB). Strong alumni network in finance and consulting.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 180,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 2000,
    globalRank: null,
  },
  {
    name: "Luleå University of Technology",
    country: "Sweden",
    region: "Norrbotten",
    city: "Luleå",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Engineering & Technology", "Sciences", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://ltu.se",
    description: "Sweden's northernmost technical university. Strong focus on mining, space technology, and sustainable development in the Arctic region.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 125,000 - 145,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 18000,
    globalRank: 551,
  },
  {
    name: "Örebro University",
    country: "Sweden",
    region: "Örebro",
    city: "Örebro",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Medicine & Health", "Sciences", "Social Sciences & Humanities", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://oru.se",
    description: "A modern university known for research in robotics, hearing science, and food studies. Strong focus on societal impact.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 100,000 - 140,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 17000,
    globalRank: 601,
  },
  {
    name: "Malmö University",
    country: "Sweden",
    region: "Skåne",
    city: "Malmö",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Social Sciences & Humanities", "Arts & Design", "Medicine & Health", "Engineering & Technology"],
    admissionPeriod: "October - January",
    website: "https://mau.se",
    description: "A young, urban university in Sweden's third-largest city. Focus on migration, urban studies, and dental education.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 90,000 - 130,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 24000,
    globalRank: 801,
  },
  {
    name: "Södertörn University",
    country: "Sweden",
    region: "Stockholm",
    city: "Huddinge",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Social Sciences & Humanities", "Sciences", "Media & Communication"],
    admissionPeriod: "October - January",
    website: "https://sh.se",
    description: "Located in southern Stockholm. Known for Baltic and East European studies, environmental science, and media studies.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 90,000 - 110,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 12000,
    globalRank: null,
  },
  {
    name: "Mälardalen University",
    country: "Sweden",
    region: "Västmanland",
    city: "Västerås",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Engineering & Technology", "Medicine & Health", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://mdu.se",
    description: "Strong focus on embedded systems, robotics, and health sciences. Campuses in Västerås and Eskilstuna.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 105,000 - 140,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 18000,
    globalRank: null,
  },
  {
    name: "Jönköping University",
    country: "Sweden",
    region: "Jönköping",
    city: "Jönköping",
    type: "Private",
    languages: ["Swedish", "English"],
    domains: ["Business & Economics", "Engineering & Technology", "Social Sciences & Humanities", "Medicine & Health"],
    admissionPeriod: "October - January",
    website: "https://ju.se",
    description: "Entrepreneurship-focused university with strong international profile. Known for family business research and teacher education.",
    englishPrograms: true,
    tuitionFeeEU: "Free (Public funding)",
    tuitionFeeNonEU: "SEK 95,000 - 140,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 12000,
    globalRank: null,
  },
  {
    name: "Blekinge Institute of Technology",
    country: "Sweden",
    region: "Blekinge",
    city: "Karlskrona",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Engineering & Technology", "Sciences"],
    admissionPeriod: "October - January",
    website: "https://bth.se",
    description: "Specialized in applied IT, software engineering, and sustainable development. Strong industry connections.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 100,000 - 140,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 6000,
    globalRank: null,
  },
  {
    name: "Halmstad University",
    country: "Sweden",
    region: "Halland",
    city: "Halmstad",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Business & Economics", "Engineering & Technology", "Medicine & Health"],
    admissionPeriod: "October - January",
    website: "https://hh.se",
    description: "Known for innovation and entrepreneurship. Strong research in health innovation and smart cities.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 100,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 11000,
    globalRank: null,
  },
  {
    name: "Karlstad University",
    country: "Sweden",
    region: "Värmland",
    city: "Karlstad",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Business & Economics", "Social Sciences & Humanities", "Engineering & Technology", "Medicine & Health"],
    admissionPeriod: "October - January",
    website: "https://kau.se",
    description: "Regional university with strong focus on service research and working life studies. Beautiful campus by Lake Vänern.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 100,000 - 130,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 17000,
    globalRank: null,
  },
  {
    name: "Kristianstad University",
    country: "Sweden",
    region: "Skåne",
    city: "Kristianstad",
    type: "Public",
    languages: ["Swedish", "English"],
    domains: ["Medicine & Health", "Business & Economics", "Social Sciences & Humanities"],
    admissionPeriod: "October - January",
    website: "https://hkr.se",
    description: "Focus on nursing, teacher education, and sustainable development. Strong regional engagement.",
    englishPrograms: true,
    tuitionFeeEU: "Free",
    tuitionFeeNonEU: "SEK 90,000 - 110,000/year",
    tuitionPeriod: "per year",
    totalEnrollment: 14000,
    globalRank: null,
  },
];
