import { db } from "../server/db";
import { universities, costOfLiving, countryProfiles } from "../shared/schema";

const frenchUniversities = [
  // Île-de-France (Paris region)
  {
    name: "Sorbonne University",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Arts & Design", "Social Sciences & Humanities"],
    admissionPeriod: "January - March",
    website: "https://www.sorbonne-universite.fr",
    description: "One of the world's oldest and most prestigious universities, formed in 2018 from the merger of Paris-Sorbonne and Pierre and Marie Curie universities.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 55000,
  },
  {
    name: "Paris Sciences et Lettres University (PSL)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Arts & Design", "Business & Economics", "Social Sciences & Humanities"],
    admissionPeriod: "November - January",
    website: "https://psl.eu",
    description: "A collegiate university bringing together elite institutions including École Normale Supérieure, MINES ParisTech, and Dauphine.",
    englishPrograms: true,
    tuitionFeeEU: "€243 - €4,500",
    tuitionFeeNonEU: "€3,770 - €15,000",
    tuitionPeriod: "per year",
    totalEnrollment: 17000,
  },
  {
    name: "University of Paris (Université Paris Cité)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Medicine & Health", "Sciences", "Social Sciences & Humanities", "Law & Politics"],
    admissionPeriod: "January - March",
    website: "https://u-paris.fr",
    description: "A major research university created in 2019, particularly strong in health sciences and natural sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 63000,
  },
  {
    name: "Sciences Po Paris",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Law & Politics", "Social Sciences & Humanities", "Business & Economics"],
    admissionPeriod: "October - January",
    website: "https://www.sciencespo.fr",
    description: "France's premier institution for political science and international affairs, with a highly international student body.",
    englishPrograms: true,
    tuitionFeeEU: "€0 - €14,500",
    tuitionFeeNonEU: "€11,000 - €22,000",
    tuitionPeriod: "per year",
    totalEnrollment: 14000,
  },
  {
    name: "HEC Paris",
    country: "France",
    region: "Île-de-France",
    city: "Jouy-en-Josas",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - March",
    website: "https://www.hec.edu",
    description: "One of the world's leading business schools, consistently ranked among the top MBA and management programs globally.",
    englishPrograms: true,
    tuitionFeeEU: "€20,000 - €80,000",
    tuitionFeeNonEU: "€20,000 - €80,000",
    tuitionPeriod: "per year",
    totalEnrollment: 5000,
  },
  {
    name: "École Polytechnique",
    country: "France",
    region: "Île-de-France",
    city: "Palaiseau",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering & Technology", "Sciences"],
    admissionPeriod: "November - January",
    website: "https://www.polytechnique.edu",
    description: "France's most prestigious engineering school, a member of Institut Polytechnique de Paris, known for rigorous scientific training.",
    englishPrograms: true,
    tuitionFeeEU: "€12,000 - €15,000",
    tuitionFeeNonEU: "€12,000 - €15,000",
    tuitionPeriod: "per year",
    totalEnrollment: 3000,
  },
  {
    name: "CentraleSupélec",
    country: "France",
    region: "Île-de-France",
    city: "Gif-sur-Yvette",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering & Technology", "Sciences", "Business & Economics"],
    admissionPeriod: "December - March",
    website: "https://www.centralesupelec.fr",
    description: "A leading engineering grande école, part of Paris-Saclay University, known for excellence in applied sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€3,500",
    tuitionFeeNonEU: "€3,500",
    tuitionPeriod: "per year",
    totalEnrollment: 4500,
  },
  {
    name: "Paris-Saclay University",
    country: "France",
    region: "Île-de-France",
    city: "Orsay",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering & Technology", "Medicine & Health", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.universite-paris-saclay.fr",
    description: "A major research-intensive university south of Paris, ranked among the world's best for natural sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 48000,
  },
  {
    name: "ESSEC Business School",
    country: "France",
    region: "Île-de-France",
    city: "Cergy",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - April",
    website: "https://www.essec.edu",
    description: "A top-tier French business school with triple accreditation, known for its management and luxury brand programs.",
    englishPrograms: true,
    tuitionFeeEU: "€17,000 - €48,000",
    tuitionFeeNonEU: "€17,000 - €48,000",
    tuitionPeriod: "per year",
    totalEnrollment: 6000,
  },
  {
    name: "INSEAD",
    country: "France",
    region: "Île-de-France",
    city: "Fontainebleau",
    type: "Private",
    languages: ["English"],
    domains: ["Business & Economics"],
    admissionPeriod: "Year-round",
    website: "https://www.insead.edu",
    description: "One of the world's leading graduate business schools, offering accelerated MBA and executive education programs.",
    englishPrograms: true,
    tuitionFeeEU: "€95,000",
    tuitionFeeNonEU: "€95,000",
    tuitionPeriod: "total program",
    totalEnrollment: 1400,
  },
  {
    name: "École Normale Supérieure (ENS)",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Social Sciences & Humanities", "Arts & Design"],
    admissionPeriod: "December - February",
    website: "https://www.ens.psl.eu",
    description: "France's most elite institution for humanities and sciences, producing numerous Nobel laureates and Fields medalists.",
    englishPrograms: true,
    tuitionFeeEU: "€0 (students receive stipend)",
    tuitionFeeNonEU: "€0 (students receive stipend)",
    tuitionPeriod: "per year",
    totalEnrollment: 2400,
  },
  {
    name: "University Paris 1 Panthéon-Sorbonne",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Law & Politics", "Business & Economics", "Social Sciences & Humanities", "Arts & Design"],
    admissionPeriod: "January - March",
    website: "https://www.pantheonsorbonne.fr",
    description: "A successor of the historic Sorbonne, specializing in law, economics, political science, and humanities.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €243",
    tuitionFeeNonEU: "€2,770",
    tuitionPeriod: "per year",
    totalEnrollment: 45000,
  },
  {
    name: "ESCP Business School",
    country: "France",
    region: "Île-de-France",
    city: "Paris",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "Year-round",
    website: "https://escp.eu",
    description: "The world's oldest business school (1819), with campuses across Europe and triple accreditation.",
    englishPrograms: true,
    tuitionFeeEU: "€17,500 - €36,500",
    tuitionFeeNonEU: "€17,500 - €36,500",
    tuitionPeriod: "per year",
    totalEnrollment: 8000,
  },
  {
    name: "Université Paris-Est Créteil",
    country: "France",
    region: "Île-de-France",
    city: "Créteil",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Medicine & Health", "Sciences", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - March",
    website: "https://www.u-pec.fr",
    description: "A multidisciplinary university in eastern Paris, particularly strong in health sciences and urban studies.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 38000,
  },
  
  // Auvergne-Rhône-Alpes
  {
    name: "University of Lyon (Université de Lyon)",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Lyon",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Engineering & Technology", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.universite-lyon.fr",
    description: "A consortium of universities and grandes écoles in Lyon, France's second-largest academic hub.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 155000,
  },
  {
    name: "Université Claude Bernard Lyon 1",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Villeurbanne",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Sports & Tourism", "Engineering & Technology"],
    admissionPeriod: "January - March",
    website: "https://www.univ-lyon1.fr",
    description: "Lyon's major science and health university, with strong research in biology and medicine.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 47000,
  },
  {
    name: "École Normale Supérieure de Lyon",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Lyon",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Social Sciences & Humanities"],
    admissionPeriod: "December - February",
    website: "https://www.ens-lyon.fr",
    description: "One of France's four ENS institutions, known for excellence in humanities and exact sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€0 (students receive stipend)",
    tuitionFeeNonEU: "€0 (students receive stipend)",
    tuitionPeriod: "per year",
    totalEnrollment: 2200,
  },
  {
    name: "emlyon Business School",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Écully",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://em-lyon.com",
    description: "A top French business school with triple accreditation, pioneering entrepreneurship education.",
    englishPrograms: true,
    tuitionFeeEU: "€18,000 - €42,000",
    tuitionFeeNonEU: "€18,000 - €42,000",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
  },
  {
    name: "Grenoble Alpes University",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Grenoble",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering & Technology", "Medicine & Health", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-grenoble-alpes.fr",
    description: "A major research university in the French Alps, known for physics, computer science, and engineering.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 59000,
  },
  {
    name: "Grenoble INP",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Grenoble",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering & Technology", "Sciences"],
    admissionPeriod: "December - March",
    website: "https://www.grenoble-inp.fr",
    description: "A group of engineering schools in Grenoble, strong in electronics, energy, and computer science.",
    englishPrograms: true,
    tuitionFeeEU: "€601 - €3,500",
    tuitionFeeNonEU: "€3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 8000,
  },
  {
    name: "Grenoble École de Management",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Grenoble",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.grenoble-em.com",
    description: "A triple-accredited business school known for technology management and sustainability programs.",
    englishPrograms: true,
    tuitionFeeEU: "€14,000 - €35,000",
    tuitionFeeNonEU: "€14,000 - €35,000",
    tuitionPeriod: "per year",
    totalEnrollment: 8500,
  },
  {
    name: "Université Clermont Auvergne",
    country: "France",
    region: "Auvergne-Rhône-Alpes",
    city: "Clermont-Ferrand",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Engineering & Technology", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.uca.fr",
    description: "The main university in the Auvergne region, with strength in biological sciences and chemistry.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 35000,
  },
  
  // Provence-Alpes-Côte d'Azur
  {
    name: "Aix-Marseille University",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Marseille",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-amu.fr",
    description: "France's largest university by enrollment, formed from three merged institutions in Marseille and Aix.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 80000,
  },
  {
    name: "Université Côte d'Azur",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Nice",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering & Technology", "Social Sciences & Humanities", "Law & Politics"],
    admissionPeriod: "January - April",
    website: "https://univ-cotedazur.fr",
    description: "A university on the French Riviera, known for research in mathematics, AI, and marine sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 30000,
  },
  {
    name: "SKEMA Business School",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Sophia Antipolis",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - April",
    website: "https://www.skema.edu",
    description: "A global business school with campuses on multiple continents, known for data analytics and luxury management.",
    englishPrograms: true,
    tuitionFeeEU: "€13,000 - €35,000",
    tuitionFeeNonEU: "€13,000 - €35,000",
    tuitionPeriod: "per year",
    totalEnrollment: 9500,
  },
  {
    name: "KEDGE Business School",
    country: "France",
    region: "Provence-Alpes-Côte d'Azur",
    city: "Marseille",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://kedge.edu",
    description: "A triple-accredited business school with strength in supply chain management and wine & spirits management.",
    englishPrograms: true,
    tuitionFeeEU: "€12,000 - €32,000",
    tuitionFeeNonEU: "€12,000 - €32,000",
    tuitionPeriod: "per year",
    totalEnrollment: 14000,
  },
  
  // Occitanie
  {
    name: "University of Toulouse",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering & Technology", "Medicine & Health", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-toulouse.fr",
    description: "A major academic consortium in France's aerospace capital, with strong engineering and science programs.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 120000,
  },
  {
    name: "Toulouse Business School",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.tbs-education.com",
    description: "A triple-accredited business school with expertise in aerospace management and AI for business.",
    englishPrograms: true,
    tuitionFeeEU: "€12,000 - €28,000",
    tuitionFeeNonEU: "€12,000 - €28,000",
    tuitionPeriod: "per year",
    totalEnrollment: 5500,
  },
  {
    name: "ISAE-SUPAERO",
    country: "France",
    region: "Occitanie",
    city: "Toulouse",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering & Technology", "Sciences"],
    admissionPeriod: "November - February",
    website: "https://www.isae-supaero.fr",
    description: "France's premier aerospace engineering school, producing many leaders in the aviation industry.",
    englishPrograms: true,
    tuitionFeeEU: "€3,000 - €15,000",
    tuitionFeeNonEU: "€3,000 - €15,000",
    tuitionPeriod: "per year",
    totalEnrollment: 2000,
  },
  {
    name: "University of Montpellier",
    country: "France",
    region: "Occitanie",
    city: "Montpellier",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Agriculture & Environment"],
    admissionPeriod: "January - April",
    website: "https://www.umontpellier.fr",
    description: "One of the oldest universities in Europe, particularly renowned for medicine and environmental sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 52000,
  },
  {
    name: "Montpellier Business School",
    country: "France",
    region: "Occitanie",
    city: "Montpellier",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.montpellier-bs.com",
    description: "A triple-accredited business school focused on social and environmental responsibility.",
    englishPrograms: true,
    tuitionFeeEU: "€11,500 - €26,000",
    tuitionFeeNonEU: "€11,500 - €26,000",
    tuitionPeriod: "per year",
    totalEnrollment: 4000,
  },
  
  // Nouvelle-Aquitaine
  {
    name: "University of Bordeaux",
    country: "France",
    region: "Nouvelle-Aquitaine",
    city: "Bordeaux",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.u-bordeaux.fr",
    description: "A major research university in southwest France, strong in neuroscience, materials science, and wine studies.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 56000,
  },
  {
    name: "KEDGE Business School Bordeaux",
    country: "France",
    region: "Nouvelle-Aquitaine",
    city: "Bordeaux",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://kedge.edu",
    description: "KEDGE's Bordeaux campus, known for wine & spirits management and international business programs.",
    englishPrograms: true,
    tuitionFeeEU: "€12,000 - €32,000",
    tuitionFeeNonEU: "€12,000 - €32,000",
    tuitionPeriod: "per year",
    totalEnrollment: 6000,
  },
  {
    name: "University of Poitiers",
    country: "France",
    region: "Nouvelle-Aquitaine",
    city: "Poitiers",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Law & Politics", "Social Sciences & Humanities", "Medicine & Health"],
    admissionPeriod: "January - April",
    website: "https://www.univ-poitiers.fr",
    description: "One of France's oldest universities, known for its welcoming approach to international students.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 29000,
  },
  
  // Brittany
  {
    name: "University of Rennes",
    country: "France",
    region: "Brittany",
    city: "Rennes",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-rennes.fr",
    description: "The main university in Brittany, with particular strengths in digital technology and cybersecurity.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 35000,
  },
  {
    name: "Rennes School of Business",
    country: "France",
    region: "Brittany",
    city: "Rennes",
    type: "Private",
    languages: ["English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.rennes-sb.com",
    description: "A fully English-speaking business school with triple accreditation and global focus.",
    englishPrograms: true,
    tuitionFeeEU: "€12,500 - €24,000",
    tuitionFeeNonEU: "€12,500 - €24,000",
    tuitionPeriod: "per year",
    totalEnrollment: 5000,
  },
  {
    name: "University of Brest",
    country: "France",
    region: "Brittany",
    city: "Brest",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Engineering & Technology"],
    admissionPeriod: "January - April",
    website: "https://www.univ-brest.fr",
    description: "A maritime university with expertise in oceanography, marine biology, and naval engineering.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 24000,
  },
  
  // Grand Est
  {
    name: "University of Strasbourg",
    country: "France",
    region: "Grand Est",
    city: "Strasbourg",
    type: "Public",
    languages: ["French", "English", "German"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.unistra.fr",
    description: "A historic university in the European capital, with strong ties to EU institutions and German partners.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 52000,
  },
  {
    name: "EM Strasbourg Business School",
    country: "France",
    region: "Grand Est",
    city: "Strasbourg",
    type: "Public",
    languages: ["French", "English", "German"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.em-strasbourg.com",
    description: "Part of the University of Strasbourg, one of the only public business schools with triple accreditation.",
    englishPrograms: true,
    tuitionFeeEU: "€4,000 - €18,000",
    tuitionFeeNonEU: "€4,000 - €18,000",
    tuitionPeriod: "per year",
    totalEnrollment: 4000,
  },
  {
    name: "University of Lorraine",
    country: "France",
    region: "Grand Est",
    city: "Nancy",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering & Technology", "Medicine & Health", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-lorraine.fr",
    description: "One of France's largest universities, strong in materials science and energy engineering.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 60000,
  },
  {
    name: "ICN Business School",
    country: "France",
    region: "Grand Est",
    city: "Nancy",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.icn-artem.com",
    description: "A triple-accredited business school emphasizing art and design thinking in management education.",
    englishPrograms: true,
    tuitionFeeEU: "€10,500 - €24,000",
    tuitionFeeNonEU: "€10,500 - €24,000",
    tuitionPeriod: "per year",
    totalEnrollment: 3500,
  },
  {
    name: "University of Reims Champagne-Ardenne",
    country: "France",
    region: "Grand Est",
    city: "Reims",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Business & Economics", "Agriculture & Environment"],
    admissionPeriod: "January - April",
    website: "https://www.univ-reims.fr",
    description: "A multidisciplinary university in the Champagne region, known for oenology and vine & wine sciences.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 27000,
  },
  {
    name: "NEOMA Business School",
    country: "France",
    region: "Grand Est",
    city: "Reims",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://neoma-bs.com",
    description: "A triple-accredited business school with campuses in Reims and Rouen, known for marketing and finance.",
    englishPrograms: true,
    tuitionFeeEU: "€14,000 - €34,000",
    tuitionFeeNonEU: "€14,000 - €34,000",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
  },
  
  // Hauts-de-France
  {
    name: "University of Lille",
    country: "France",
    region: "Hauts-de-France",
    city: "Lille",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-lille.fr",
    description: "One of France's largest universities, formed from three merged institutions in northern France.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 74000,
  },
  {
    name: "EDHEC Business School",
    country: "France",
    region: "Hauts-de-France",
    city: "Lille",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - April",
    website: "https://www.edhec.edu",
    description: "A top-tier French business school known for finance and private equity programs.",
    englishPrograms: true,
    tuitionFeeEU: "€17,000 - €42,000",
    tuitionFeeNonEU: "€17,000 - €42,000",
    tuitionPeriod: "per year",
    totalEnrollment: 9000,
  },
  {
    name: "IESEG School of Management",
    country: "France",
    region: "Hauts-de-France",
    city: "Lille",
    type: "Private",
    languages: ["English"],
    domains: ["Business & Economics"],
    admissionPeriod: "Year-round",
    website: "https://www.ieseg.fr",
    description: "A fully English-speaking grande école with triple accreditation, strong in negotiation and CSR.",
    englishPrograms: true,
    tuitionFeeEU: "€12,350 - €22,000",
    tuitionFeeNonEU: "€12,350 - €22,000",
    tuitionPeriod: "per year",
    totalEnrollment: 6500,
  },
  {
    name: "University of Picardy Jules Verne",
    country: "France",
    region: "Hauts-de-France",
    city: "Amiens",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.u-picardie.fr",
    description: "Named after author Jules Verne, a multidisciplinary university serving the Picardy region.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 33000,
  },
  
  // Pays de la Loire
  {
    name: "University of Nantes",
    country: "France",
    region: "Pays de la Loire",
    city: "Nantes",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Engineering & Technology"],
    admissionPeriod: "January - April",
    website: "https://www.univ-nantes.fr",
    description: "A major comprehensive university in western France, strong in marine sciences and renewable energy.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 40000,
  },
  {
    name: "Audencia Business School",
    country: "France",
    region: "Pays de la Loire",
    city: "Nantes",
    type: "Private",
    languages: ["French", "English"],
    domains: ["Business & Economics"],
    admissionPeriod: "September - May",
    website: "https://www.audencia.com",
    description: "A triple-accredited business school with a strong focus on responsible management and sustainability.",
    englishPrograms: true,
    tuitionFeeEU: "€14,000 - €32,000",
    tuitionFeeNonEU: "€14,000 - €32,000",
    tuitionPeriod: "per year",
    totalEnrollment: 6000,
  },
  {
    name: "École Centrale de Nantes",
    country: "France",
    region: "Pays de la Loire",
    city: "Nantes",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Engineering & Technology", "Sciences"],
    admissionPeriod: "December - March",
    website: "https://www.ec-nantes.fr",
    description: "One of France's Centrale engineering schools, known for ocean engineering and renewable energy.",
    englishPrograms: true,
    tuitionFeeEU: "€601 - €3,500",
    tuitionFeeNonEU: "€3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 2500,
  },
  {
    name: "University of Angers",
    country: "France",
    region: "Pays de la Loire",
    city: "Angers",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Agriculture & Environment"],
    admissionPeriod: "January - April",
    website: "https://www.univ-angers.fr",
    description: "A university in the Loire Valley known for plant sciences and sustainable agriculture.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 24000,
  },
  
  // Normandy
  {
    name: "University of Rouen Normandy",
    country: "France",
    region: "Normandy",
    city: "Rouen",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Law & Politics", "Social Sciences & Humanities"],
    admissionPeriod: "January - April",
    website: "https://www.univ-rouen.fr",
    description: "The main university of Upper Normandy, with notable strengths in chemistry and biology.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 32000,
  },
  {
    name: "University of Caen Normandy",
    country: "France",
    region: "Normandy",
    city: "Caen",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Medicine & Health", "Social Sciences & Humanities", "Law & Politics"],
    admissionPeriod: "January - April",
    website: "https://www.unicaen.fr",
    description: "A historic university in Lower Normandy, known for history, D-Day studies, and nuclear physics.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 33000,
  },
  {
    name: "Le Havre University",
    country: "France",
    region: "Normandy",
    city: "Le Havre",
    type: "Public",
    languages: ["French", "English"],
    domains: ["Sciences", "Engineering & Technology", "Business & Economics"],
    admissionPeriod: "January - April",
    website: "https://www.univ-lehavre.fr",
    description: "A port city university with expertise in logistics, maritime studies, and Asian languages.",
    englishPrograms: true,
    tuitionFeeEU: "€170 - €601",
    tuitionFeeNonEU: "€2,770 - €3,770",
    tuitionPeriod: "per year",
    totalEnrollment: 8500,
  },
];

const frenchCities = [
  { country: "France", city: "Paris", rentShared: 750, rentSolo: 1400, utilities: 150, groceries: 350, dining: 200, transport: 85, healthcare: 50, entertainment: 150, currency: "EUR" },
  { country: "France", city: "Lyon", rentShared: 500, rentSolo: 850, utilities: 120, groceries: 300, dining: 150, transport: 65, healthcare: 40, entertainment: 100, currency: "EUR" },
  { country: "France", city: "Marseille", rentShared: 450, rentSolo: 750, utilities: 110, groceries: 280, dining: 140, transport: 55, healthcare: 40, entertainment: 90, currency: "EUR" },
  { country: "France", city: "Toulouse", rentShared: 420, rentSolo: 700, utilities: 110, groceries: 270, dining: 130, transport: 50, healthcare: 40, entertainment: 85, currency: "EUR" },
  { country: "France", city: "Nice", rentShared: 550, rentSolo: 950, utilities: 130, groceries: 320, dining: 160, transport: 50, healthcare: 40, entertainment: 110, currency: "EUR" },
  { country: "France", city: "Bordeaux", rentShared: 480, rentSolo: 800, utilities: 115, groceries: 290, dining: 140, transport: 55, healthcare: 40, entertainment: 95, currency: "EUR" },
  { country: "France", city: "Strasbourg", rentShared: 450, rentSolo: 750, utilities: 120, groceries: 280, dining: 130, transport: 45, healthcare: 40, entertainment: 85, currency: "EUR" },
  { country: "France", city: "Lille", rentShared: 420, rentSolo: 680, utilities: 115, groceries: 270, dining: 120, transport: 55, healthcare: 40, entertainment: 80, currency: "EUR" },
  { country: "France", city: "Nantes", rentShared: 430, rentSolo: 720, utilities: 110, groceries: 275, dining: 130, transport: 50, healthcare: 40, entertainment: 85, currency: "EUR" },
  { country: "France", city: "Rennes", rentShared: 400, rentSolo: 650, utilities: 105, groceries: 260, dining: 120, transport: 45, healthcare: 40, entertainment: 75, currency: "EUR" },
  { country: "France", city: "Grenoble", rentShared: 420, rentSolo: 700, utilities: 120, groceries: 275, dining: 125, transport: 45, healthcare: 40, entertainment: 80, currency: "EUR" },
  { country: "France", city: "Montpellier", rentShared: 430, rentSolo: 720, utilities: 110, groceries: 280, dining: 130, transport: 45, healthcare: 40, entertainment: 90, currency: "EUR" },
];

const franceProfile = {
  country: "France",
  visaType: "VLS-TS (Long-Stay Student Visa)",
  visaProcessingTime: "2-4 weeks",
  visaCost: "€99",
  visaSuccessRate: "~85%",
  financialRequirement: "€615/month (€7,380/year) minimum",
  workHoursAllowed: "20 hours/week (964 hours/year)",
  postStudyWorkVisa: "APS Permit - 1 year job search visa, renewable",
  pathToResidency: "After 5 years of legal residence, or 2 years after master's degree",
  healthInsurance: "Enrolled in French Social Security (Sécurité Sociale)",
  languageRequirement: "B1-B2 French for French-taught programs; IELTS 6.0+ for English programs",
  immigrationPortal: "https://france-visas.gouv.fr",
  ieltsMinimum: "5.5",
  ieltsRecommended: "6.5",
  graduateEmploymentRate: "82%",
  averageSalaryEntry: "€32,000 - €38,000",
  averageSalaryMid: "€45,000 - €60,000",
  topSectors: ["Aerospace", "Luxury Goods", "Technology", "Finance", "Automotive"],
  inDemandJobs: ["Software Engineer", "Data Scientist", "Business Analyst", "Product Manager", "Marketing Manager"],
  languageForWork: "French required for most positions; English sufficient in tech/international companies",
  jobSearchTimeline: "3-6 months average",
  workCulture: "35-hour work week, strong work-life balance, emphasis on formality in business",
  jobPortals: ["LinkedIn", "Indeed France", "Apec.fr", "Welcome to the Jungle", "Glassdoor"],
  officialLanguage: "French",
  currency: "EUR",
  qualityOfLife: "High - excellent healthcare, culture, cuisine, and public services",
};

async function seedFrance() {
  console.log("Starting France seed...");
  
  try {
    // Add universities
    console.log(`Adding ${frenchUniversities.length} French universities...`);
    for (const uni of frenchUniversities) {
      await db.insert(universities).values(uni);
    }
    console.log("Universities added successfully!");
    
    // Add cost of living data
    console.log(`Adding ${frenchCities.length} French cities for cost of living...`);
    for (const city of frenchCities) {
      await db.insert(costOfLiving).values(city);
    }
    console.log("Cost of living data added successfully!");
    
    // Add country profile
    console.log("Adding France country profile...");
    await db.insert(countryProfiles).values(franceProfile);
    console.log("Country profile added successfully!");
    
    console.log("France seed completed successfully!");
  } catch (error) {
    console.error("Error seeding France data:", error);
    throw error;
  }
}

seedFrance().then(() => {
  console.log("Done!");
  process.exit(0);
}).catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
